/*
 Navicat Premium Data Transfer

 Source Server         : 192.168.100.33_1521_XE
 Source Server Type    : Oracle
 Source Server Version : 110200
 Source Host           : 192.168.100.33:1521
 Source Schema         : GANSU

 Target Server Type    : Oracle
 Target Server Version : 110200
 File Encoding         : 65001

 Date: 03/12/2021 15:09:30
*/


-- ----------------------------
-- Table structure for MENU_OPRATION
-- ----------------------------
DROP TABLE "GANSU"."MENU_OPRATION";
CREATE TABLE "GANSU"."MENU_OPRATION" (
  "MENU_ID" VARCHAR2(255 BYTE) ,
  "OP_ID" VARCHAR2(255 BYTE) 
)
TABLESPACE "SYSTEM"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  FREELISTS 1
  FREELIST GROUPS 1
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of MENU_OPRATION
-- ----------------------------
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('28', '1');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('30', '1');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('31', '1');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('32', '1');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('33', '1');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('34', '1');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('35', '1');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('36', '1');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('37', '1');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('39', '1');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('28', '2');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('30', '2');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('31', '2');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('32', '2');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('33', '2');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('34', '2');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('35', '2');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('36', '2');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('39', '2');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('28', '3');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('30', '3');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('31', '3');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('32', '3');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('33', '3');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('34', '3');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('35', '3');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('36', '3');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('37', '3');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('39', '3');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('28', '4');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('30', '4');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('31', '4');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('32', '4');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('33', '4');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('34', '4');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('35', '4');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('36', '4');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('39', '4');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('28', '5');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('30', '5');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('31', '5');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('32', '5');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('33', '5');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('34', '5');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('35', '5');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('36', '5');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('37', '5');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('39', '5');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('28', '6');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('30', '6');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('31', '6');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('32', '6');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('33', '6');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('34', '6');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('35', '6');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('36', '6');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('39', '6');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('28', '7');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('30', '7');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('31', '7');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('32', '7');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('33', '7');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('34', '7');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('35', '7');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('36', '7');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('37', '7');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('39', '7');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('28', '8');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('30', '8');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('31', '8');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('32', '8');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('33', '8');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('34', '8');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('35', '8');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('36', '8');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('39', '8');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('28', '9');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('30', '9');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('31', '9');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('32', '9');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('33', '9');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('34', '9');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('35', '9');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('36', '9');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('39', '9');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('28', '10');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('30', '10');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('31', '10');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('32', '10');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('33', '10');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('34', '10');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('35', '10');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('36', '10');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('37', '10');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('39', '10');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('28', '11');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('30', '11');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('31', '11');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('32', '11');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('33', '11');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('34', '11');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('35', '11');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('36', '11');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('37', '11');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('39', '11');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('28', '12');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('30', '12');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('31', '12');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('32', '12');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('33', '12');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('34', '12');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('35', '12');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('36', '12');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('39', '12');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('28', '13');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('30', '13');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('31', '13');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('32', '13');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('33', '13');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('34', '13');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('35', '13');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('36', '13');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('37', '13');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('39', '13');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('28', '14');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('30', '14');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('31', '14');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('32', '14');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('33', '14');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('34', '14');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('35', '14');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('36', '14');
INSERT INTO "GANSU"."MENU_OPRATION" VALUES ('39', '14');
