/*
 Navicat Premium Data Transfer

 Source Server         : 192.168.100.33_1521_XE
 Source Server Type    : Oracle
 Source Server Version : 110200
 Source Host           : 192.168.100.33:1521
 Source Schema         : GANSU

 Target Server Type    : Oracle
 Target Server Version : 110200
 File Encoding         : 65001

 Date: 03/12/2021 15:09:38
*/


-- ----------------------------
-- Table structure for OPRATION_RESOURCE
-- ----------------------------
DROP TABLE "GANSU"."OPRATION_RESOURCE";
CREATE TABLE "GANSU"."OPRATION_RESOURCE" (
  "OP_ID" VARCHAR2(255 BYTE) ,
  "RESOURCE_ID" VARCHAR2(255 BYTE) 
)
TABLESPACE "SYSTEM"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  FREELISTS 1
  FREELIST GROUPS 1
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of OPRATION_RESOURCE
-- ----------------------------
INSERT INTO "GANSU"."OPRATION_RESOURCE" VALUES ('1', '1');
INSERT INTO "GANSU"."OPRATION_RESOURCE" VALUES ('2', '2');
INSERT INTO "GANSU"."OPRATION_RESOURCE" VALUES ('3', '3');
INSERT INTO "GANSU"."OPRATION_RESOURCE" VALUES ('4', '4');
INSERT INTO "GANSU"."OPRATION_RESOURCE" VALUES ('4', '5');
INSERT INTO "GANSU"."OPRATION_RESOURCE" VALUES ('5', '6');
INSERT INTO "GANSU"."OPRATION_RESOURCE" VALUES ('6', '7');
INSERT INTO "GANSU"."OPRATION_RESOURCE" VALUES ('7', '8');
INSERT INTO "GANSU"."OPRATION_RESOURCE" VALUES ('3', '9');
INSERT INTO "GANSU"."OPRATION_RESOURCE" VALUES ('7', '10');
INSERT INTO "GANSU"."OPRATION_RESOURCE" VALUES ('8', '11');
INSERT INTO "GANSU"."OPRATION_RESOURCE" VALUES ('8', '12');
INSERT INTO "GANSU"."OPRATION_RESOURCE" VALUES ('10', '13');
INSERT INTO "GANSU"."OPRATION_RESOURCE" VALUES ('10', '14');
INSERT INTO "GANSU"."OPRATION_RESOURCE" VALUES ('9', '15');
INSERT INTO "GANSU"."OPRATION_RESOURCE" VALUES ('9', '16');
INSERT INTO "GANSU"."OPRATION_RESOURCE" VALUES ('11', '17');
INSERT INTO "GANSU"."OPRATION_RESOURCE" VALUES ('11', '18');
INSERT INTO "GANSU"."OPRATION_RESOURCE" VALUES ('12', '19');
INSERT INTO "GANSU"."OPRATION_RESOURCE" VALUES ('12', '20');
INSERT INTO "GANSU"."OPRATION_RESOURCE" VALUES ('13', '21');
INSERT INTO "GANSU"."OPRATION_RESOURCE" VALUES ('13', '22');
INSERT INTO "GANSU"."OPRATION_RESOURCE" VALUES ('14', '23');
INSERT INTO "GANSU"."OPRATION_RESOURCE" VALUES ('14', '24');
