/*
 Navicat Premium Data Transfer

 Source Server         : 192.168.100.33_1521_XE
 Source Server Type    : Oracle
 Source Server Version : 110200
 Source Host           : 192.168.100.33:1521
 Source Schema         : GANSU

 Target Server Type    : Oracle
 Target Server Version : 110200
 File Encoding         : 65001

 Date: 03/12/2021 15:09:45
*/


-- ----------------------------
-- Table structure for ORG_ROLE
-- ----------------------------
DROP TABLE "GANSU"."ORG_ROLE";
CREATE TABLE "GANSU"."ORG_ROLE" (
  "ORG_ID" VARCHAR2(255 BYTE) ,
  "ROLE_ID" VARCHAR2(255 BYTE) 
)
TABLESPACE "SYSTEM"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  FREELISTS 1
  FREELIST GROUPS 1
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of ORG_ROLE
-- ----------------------------
INSERT INTO "GANSU"."ORG_ROLE" VALUES ('3', '2');
INSERT INTO "GANSU"."ORG_ROLE" VALUES ('4', '2');
INSERT INTO "GANSU"."ORG_ROLE" VALUES ('6', '2');
INSERT INTO "GANSU"."ORG_ROLE" VALUES ('7', '2');
INSERT INTO "GANSU"."ORG_ROLE" VALUES ('8', '2');
INSERT INTO "GANSU"."ORG_ROLE" VALUES ('9', '2');
INSERT INTO "GANSU"."ORG_ROLE" VALUES ('10', '2');
INSERT INTO "GANSU"."ORG_ROLE" VALUES ('14', '2');
INSERT INTO "GANSU"."ORG_ROLE" VALUES ('32', '2');
INSERT INTO "GANSU"."ORG_ROLE" VALUES ('3', '4');
INSERT INTO "GANSU"."ORG_ROLE" VALUES ('4', '4');
INSERT INTO "GANSU"."ORG_ROLE" VALUES ('6', '4');
INSERT INTO "GANSU"."ORG_ROLE" VALUES ('7', '4');
INSERT INTO "GANSU"."ORG_ROLE" VALUES ('8', '4');
INSERT INTO "GANSU"."ORG_ROLE" VALUES ('9', '4');
INSERT INTO "GANSU"."ORG_ROLE" VALUES ('10', '4');
INSERT INTO "GANSU"."ORG_ROLE" VALUES ('14', '4');
INSERT INTO "GANSU"."ORG_ROLE" VALUES ('37', '4');
INSERT INTO "GANSU"."ORG_ROLE" VALUES ('3', '5');
INSERT INTO "GANSU"."ORG_ROLE" VALUES ('4', '5');
INSERT INTO "GANSU"."ORG_ROLE" VALUES ('6', '5');
INSERT INTO "GANSU"."ORG_ROLE" VALUES ('7', '5');
INSERT INTO "GANSU"."ORG_ROLE" VALUES ('8', '5');
INSERT INTO "GANSU"."ORG_ROLE" VALUES ('9', '5');
INSERT INTO "GANSU"."ORG_ROLE" VALUES ('10', '5');
INSERT INTO "GANSU"."ORG_ROLE" VALUES ('14', '5');
INSERT INTO "GANSU"."ORG_ROLE" VALUES ('35', '5');
INSERT INTO "GANSU"."ORG_ROLE" VALUES ('37', '5');
INSERT INTO "GANSU"."ORG_ROLE" VALUES ('3', '7');
INSERT INTO "GANSU"."ORG_ROLE" VALUES ('4', '7');
INSERT INTO "GANSU"."ORG_ROLE" VALUES ('6', '7');
INSERT INTO "GANSU"."ORG_ROLE" VALUES ('7', '7');
INSERT INTO "GANSU"."ORG_ROLE" VALUES ('8', '7');
INSERT INTO "GANSU"."ORG_ROLE" VALUES ('9', '7');
INSERT INTO "GANSU"."ORG_ROLE" VALUES ('10', '7');
INSERT INTO "GANSU"."ORG_ROLE" VALUES ('14', '7');
INSERT INTO "GANSU"."ORG_ROLE" VALUES ('3', '11');
INSERT INTO "GANSU"."ORG_ROLE" VALUES ('4', '11');
INSERT INTO "GANSU"."ORG_ROLE" VALUES ('6', '11');
INSERT INTO "GANSU"."ORG_ROLE" VALUES ('7', '11');
INSERT INTO "GANSU"."ORG_ROLE" VALUES ('8', '11');
INSERT INTO "GANSU"."ORG_ROLE" VALUES ('9', '11');
INSERT INTO "GANSU"."ORG_ROLE" VALUES ('10', '11');
INSERT INTO "GANSU"."ORG_ROLE" VALUES ('14', '11');
