/*
 Navicat Premium Data Transfer

 Source Server         : 192.168.100.33_1521_XE
 Source Server Type    : Oracle
 Source Server Version : 110200
 Source Host           : 192.168.100.33:1521
 Source Schema         : GANSU

 Target Server Type    : Oracle
 Target Server Version : 110200
 File Encoding         : 65001

 Date: 03/12/2021 15:10:05
*/


-- ----------------------------
-- Table structure for ROLE_MENU
-- ----------------------------
DROP TABLE "GANSU"."ROLE_MENU";
CREATE TABLE "GANSU"."ROLE_MENU" (
  "ROLE_ID" VARCHAR2(255 BYTE) ,
  "MENU_ID" VARCHAR2(255 BYTE) 
)
TABLESPACE "SYSTEM"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  FREELISTS 1
  FREELIST GROUPS 1
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of ROLE_MENU
-- ----------------------------
INSERT INTO "GANSU"."ROLE_MENU" VALUES ('11', '27');
INSERT INTO "GANSU"."ROLE_MENU" VALUES ('2', '28');
INSERT INTO "GANSU"."ROLE_MENU" VALUES ('4', '28');
INSERT INTO "GANSU"."ROLE_MENU" VALUES ('11', '28');
INSERT INTO "GANSU"."ROLE_MENU" VALUES ('11', '29');
INSERT INTO "GANSU"."ROLE_MENU" VALUES ('2', '30');
INSERT INTO "GANSU"."ROLE_MENU" VALUES ('4', '30');
INSERT INTO "GANSU"."ROLE_MENU" VALUES ('11', '30');
INSERT INTO "GANSU"."ROLE_MENU" VALUES ('11', '31');
INSERT INTO "GANSU"."ROLE_MENU" VALUES ('4', '32');
INSERT INTO "GANSU"."ROLE_MENU" VALUES ('11', '32');
INSERT INTO "GANSU"."ROLE_MENU" VALUES ('4', '33');
INSERT INTO "GANSU"."ROLE_MENU" VALUES ('11', '33');
INSERT INTO "GANSU"."ROLE_MENU" VALUES ('4', '34');
INSERT INTO "GANSU"."ROLE_MENU" VALUES ('11', '34');
INSERT INTO "GANSU"."ROLE_MENU" VALUES ('4', '35');
INSERT INTO "GANSU"."ROLE_MENU" VALUES ('11', '35');
INSERT INTO "GANSU"."ROLE_MENU" VALUES ('4', '36');
INSERT INTO "GANSU"."ROLE_MENU" VALUES ('5', '36');
INSERT INTO "GANSU"."ROLE_MENU" VALUES ('11', '36');
INSERT INTO "GANSU"."ROLE_MENU" VALUES ('2', '37');
INSERT INTO "GANSU"."ROLE_MENU" VALUES ('4', '37');
INSERT INTO "GANSU"."ROLE_MENU" VALUES ('5', '37');
INSERT INTO "GANSU"."ROLE_MENU" VALUES ('11', '37');
INSERT INTO "GANSU"."ROLE_MENU" VALUES ('4', '38');
INSERT INTO "GANSU"."ROLE_MENU" VALUES ('5', '38');
INSERT INTO "GANSU"."ROLE_MENU" VALUES ('11', '38');
INSERT INTO "GANSU"."ROLE_MENU" VALUES ('4', '39');
INSERT INTO "GANSU"."ROLE_MENU" VALUES ('5', '39');
INSERT INTO "GANSU"."ROLE_MENU" VALUES ('11', '39');
INSERT INTO "GANSU"."ROLE_MENU" VALUES ('4', '40');
INSERT INTO "GANSU"."ROLE_MENU" VALUES ('11', '40');
INSERT INTO "GANSU"."ROLE_MENU" VALUES ('4', '41');
INSERT INTO "GANSU"."ROLE_MENU" VALUES ('5', '41');
INSERT INTO "GANSU"."ROLE_MENU" VALUES ('11', '41');
INSERT INTO "GANSU"."ROLE_MENU" VALUES ('4', '42');
INSERT INTO "GANSU"."ROLE_MENU" VALUES ('5', '42');
INSERT INTO "GANSU"."ROLE_MENU" VALUES ('11', '42');
INSERT INTO "GANSU"."ROLE_MENU" VALUES ('4', '43');
INSERT INTO "GANSU"."ROLE_MENU" VALUES ('5', '43');
INSERT INTO "GANSU"."ROLE_MENU" VALUES ('11', '43');
INSERT INTO "GANSU"."ROLE_MENU" VALUES ('11', '44');
INSERT INTO "GANSU"."ROLE_MENU" VALUES ('11', '45');
INSERT INTO "GANSU"."ROLE_MENU" VALUES ('11', '46');
INSERT INTO "GANSU"."ROLE_MENU" VALUES ('11', '47');
