INSERT INTO SYSDBA.XXCOLUMN_DEFINITION (ID,TABLEIDENTITY,FIELD,"HEADER","SEQUENCE",EDITABLE,SORTABLE,"TYPE",SELECTURL,"SEARCH",SEARCHTYPE,LINK,ADDABLE,HIDDEN,REFTABLE,REFCOLUMN,REFVALUE,REQUIRED,REG,MINLENGTH,MAXLENGTH,"DISTINCT") VALUES 
(11132,'role','role_id','ID',1,'0','0','text            ','','0','exact   ','0','0','0','','','','0','',NULL,NULL,'0')
,(11133,'role','role_name','名称',2,'1','0','text            ','','1','like    ','0','1','0','','','','0','',2,50,'0')
,(11134,'role','role_create_time','创建时间',3,'0','0','daterange       ','','1','range   ','0','0','0','','','','0','',NULL,NULL,'0')
,(11135,'role','role_update_time','更新时间',4,'0',NULL,'daterange       ','','1','range   ',NULL,'0','0','','','','0','',NULL,NULL,NULL)
,(11136,'user','user_id','ID',1,'0',NULL,'text            ','','0','        ',NULL,'0','1','','','','0','',NULL,NULL,NULL)
,(11137,'user','user_name','用户名',2,'1',NULL,'text            ','','1','like    ',NULL,'1','0','','','','1','',2,50,NULL)
,(11138,'user','user_real_name','真实姓名',3,'1',NULL,'text            ','','0','        ',NULL,'1','0','','','','1','',NULL,NULL,NULL)
,(11139,'user','user_pwd','密码',4,'0',NULL,'text            ','','0','        ',NULL,'0','1','','','','0','',NULL,NULL,NULL)
,(11140,'user','user_tel','手机号码',5,'1',NULL,'text            ','','0','        ',NULL,'1','0','','','','0','',NULL,NULL,NULL)
,(11141,'user','user_email','邮箱',6,'1',NULL,'text            ','','0','        ',NULL,'1','0','','','','0','^[a-zA-Z0-9_-]+@[a-zA-Z0-9_-]+(.[a-zA-Z0-9_-]+)+$',NULL,NULL,NULL)
;
INSERT INTO SYSDBA.XXCOLUMN_DEFINITION (ID,TABLEIDENTITY,FIELD,"HEADER","SEQUENCE",EDITABLE,SORTABLE,"TYPE",SELECTURL,"SEARCH",SEARCHTYPE,LINK,ADDABLE,HIDDEN,REFTABLE,REFCOLUMN,REFVALUE,REQUIRED,REG,MINLENGTH,MAXLENGTH,"DISTINCT") VALUES 
(11142,'user','user_status','用户状态',7,'1',NULL,'select          ','','1','exact   ',NULL,'1','0','user_status','user_status_name','','0','',NULL,NULL,NULL)
,(11143,'user','user_create_time','创建时间',8,'0',NULL,'daterange       ','','1','range   ',NULL,'0','0','','','','0','',NULL,NULL,NULL)
,(11144,'user','user_update_time','最后修改时间',9,'0',NULL,'daterange       ','','1','range   ',NULL,'0','0','','','','0','',NULL,NULL,NULL)
,(11145,'user','user_role','用户角色',7,'0',NULL,'multiSelect     ','','0','        ',NULL,'0','0','','','','0','',NULL,NULL,NULL)
,(11146,'user','user_role_edit','用户角色',10,'1',NULL,'multiSelect     ','/combobox/role','0','        ',NULL,'1','1','','','','0','',NULL,NULL,NULL)
,(11147,'user','user_org','组织机构',7,'0',NULL,'selectCascader  ','','0','        ',NULL,'0','0','','','','0','',NULL,NULL,NULL)
,(11148,'user','user_org_edit','组织机构',11,'1',NULL,'selectCascader  ','/combobox/org/tree','0','        ',NULL,'1','1','','','','0','',NULL,NULL,NULL)
,(11149,'dict','id','字典id',1,'0','0','text            ','','0','        ',NULL,'0','0','','','','0','',NULL,NULL,NULL)
,(11150,'dict','key','字典键',2,'0','1','text            ','','0','exact   ',NULL,'0','0','','','','0','',NULL,NULL,NULL)
,(11151,'dict','value','字典值',3,'0','0','text            ','','0','like    ',NULL,'0','0','','','','0','',NULL,NULL,NULL)
;
INSERT INTO SYSDBA.XXCOLUMN_DEFINITION (ID,TABLEIDENTITY,FIELD,"HEADER","SEQUENCE",EDITABLE,SORTABLE,"TYPE",SELECTURL,"SEARCH",SEARCHTYPE,LINK,ADDABLE,HIDDEN,REFTABLE,REFCOLUMN,REFVALUE,REQUIRED,REG,MINLENGTH,MAXLENGTH,"DISTINCT") VALUES 
(11152,'dict','type','字典类型',4,'0','0','text            ','','0','extra   ',NULL,'0','0','','','','0','',NULL,NULL,NULL)
,(11153,'dict','description','字典描述',5,'0','0','text            ','','0','        ',NULL,'0','0','','','','0','',NULL,NULL,NULL)
,(11154,'param','param_name','参数名称',1,'1','0','text            ','','0','        ',NULL,'1','0','','','','0','',NULL,NULL,NULL)
,(11155,'param','param_key','参数键名',2,'1','1','text            ','','1','like    ',NULL,'1','0','','','','0','',1,NULL,NULL)
,(11156,'param','param_value','参数键值',3,'1','1','text            ','','1','like    ',NULL,'1','0','','','','0','',1,NULL,NULL)
,(11157,'param','param_type','参数类型',4,'0','1','text            ','','0','        ',NULL,'0','0','','','','0','',NULL,NULL,NULL)
,(11158,'param','create_by','创建者',5,'0','0','text            ','','0','        ',NULL,'0','0','','','','0','',NULL,NULL,NULL)
,(11159,'param','create_time','创建时间',6,'0','0','text            ','','0','        ',NULL,'0','0','','','','0','',NULL,NULL,NULL)
,(11160,'param','update_by','更新者',7,'0','0','text            ','','0','        ',NULL,'0','0','','','','0','',NULL,NULL,NULL)
,(11161,'param','update_time','更新时间',8,'0','1','text            ','','0','        ',NULL,'0','0','','','','0','',NULL,NULL,NULL)
;
INSERT INTO SYSDBA.XXCOLUMN_DEFINITION (ID,TABLEIDENTITY,FIELD,"HEADER","SEQUENCE",EDITABLE,SORTABLE,"TYPE",SELECTURL,"SEARCH",SEARCHTYPE,LINK,ADDABLE,HIDDEN,REFTABLE,REFCOLUMN,REFVALUE,REQUIRED,REG,MINLENGTH,MAXLENGTH,"DISTINCT") VALUES 
(11162,'param','param_desc','参数描述',9,'1',NULL,'text            ','','0','        ',NULL,'1','0','','','','0','',NULL,NULL,NULL)
,(11163,'log_info','id','序号',1,'0','1','text            ','','0','        ',NULL,'0','1','','','','0','',NULL,NULL,NULL)
,(11164,'log_info','log_type','日志类型',2,'0',NULL,'text            ','','1','exact   ',NULL,'0','0','','','','0','',NULL,NULL,NULL)
,(11165,'log_info','operate_user','操作用户',3,'0','0','text            ','','1','exact   ',NULL,'0','0','','','','0','',NULL,NULL,NULL)
,(11166,'log_info','operate_type','操作类型',4,'0',NULL,'text            ','','1','exact   ',NULL,'0','0','','','','0','',NULL,NULL,NULL)
,(11167,'log_info','request_url','请求地址',5,'0',NULL,'text            ','','0','        ',NULL,'0','0','','','','0','',NULL,NULL,NULL)
,(11168,'log_info','operate_time','操作时间',6,'0',NULL,'text            ','','0','        ',NULL,'0','0','','','','0','',NULL,NULL,NULL)
,(11169,'log_info','request_took_time','响应时间',7,'0',NULL,'text            ','','0','        ',NULL,'0','0','','','','0','',NULL,NULL,NULL)
,(11170,'ws_data','id','ID',1,'0',NULL,'text            ','','0','        ',NULL,'0','0','','','','0','',NULL,NULL,NULL)
,(11171,'ws_data','type','类型',2,'0',NULL,'text            ','','0','        ',NULL,'0','0','','','','0','',NULL,NULL,NULL)
;
INSERT INTO SYSDBA.XXCOLUMN_DEFINITION (ID,TABLEIDENTITY,FIELD,"HEADER","SEQUENCE",EDITABLE,SORTABLE,"TYPE",SELECTURL,"SEARCH",SEARCHTYPE,LINK,ADDABLE,HIDDEN,REFTABLE,REFCOLUMN,REFVALUE,REQUIRED,REG,MINLENGTH,MAXLENGTH,"DISTINCT") VALUES 
(11172,'log_info','log_desc','日志详情',8,'0',NULL,'text            ','','0','        ',NULL,'0','0','','','','0','',NULL,NULL,NULL)
,(11173,'ws_data','msg_id','消息id',3,'0',NULL,'text            ','','0','        ',NULL,'0','0','','','','0','',NULL,NULL,NULL)
,(11174,'ws_data','user_identify','用户标识',4,'0',NULL,'text            ','','1','like    ',NULL,'0','0','','','','0','',NULL,NULL,NULL)
,(11175,'ws_data','data','数据',5,'0',NULL,'text            ','','0','        ',NULL,'0','0','','','','0','',NULL,NULL,NULL)
,(11176,'ws_data','destination','订阅路径',6,'0',NULL,'text            ','','0','        ',NULL,'0','0','','','','0','',NULL,NULL,NULL)
,(11177,'ws_data','create_time','推送时间',7,'0',NULL,'daterange       ','','1','range   ',NULL,'0','0','','','','0','',NULL,NULL,NULL)
,(11178,'dict_data','dict_label','字典名称',1,'1','1','text            ','','1','like    ',NULL,'1','0','','','','0','',1,NULL,NULL)
,(11179,'dict_data','dict_data_type','数据类型',2,'1','1','text            ','','1','like    ',NULL,'1','0','','','','0','',1,NULL,NULL)
,(11180,'dict_data','dict_type','字典类型',3,'0','1','text            ','','0','        ',NULL,'0','0','','','','0','',NULL,NULL,NULL)
,(11181,'dict_data','create_time','创建时间',4,'0',NULL,'text            ','','0','        ',NULL,'0','0','','','','0','',NULL,NULL,NULL)
;
INSERT INTO SYSDBA.XXCOLUMN_DEFINITION (ID,TABLEIDENTITY,FIELD,"HEADER","SEQUENCE",EDITABLE,SORTABLE,"TYPE",SELECTURL,"SEARCH",SEARCHTYPE,LINK,ADDABLE,HIDDEN,REFTABLE,REFCOLUMN,REFVALUE,REQUIRED,REG,MINLENGTH,MAXLENGTH,"DISTINCT") VALUES 
(11182,'dict_data','create_by','创建者',5,'0','1','text            ','','0','        ',NULL,'0','0','','','','0','',NULL,NULL,NULL)
,(11183,'dict_data','update_time','更新时间',6,'0',NULL,'text            ','','0','        ',NULL,'0','0','','','','0','',NULL,NULL,NULL)
,(11184,'dict_data','update_by','更新者',7,'0','1','text            ','','0','        ',NULL,'0','0','','','','0','',NULL,NULL,NULL)
,(11185,'dict_data','dict_desc','字典描述',8,'1',NULL,'text            ','','0','        ',NULL,'1','0','','','','0','',NULL,NULL,NULL)
,(11186,'dict_data_type','dict_data_type','数据类型',1,'1','0','text            ','','1','exact   ',NULL,'1','0','','','','0','',NULL,NULL,NULL)
,(11187,'dict_data_type','dict_data_key','数据键',2,'1','1','text            ','','1','like    ',NULL,'1','0','','','','0','',1,NULL,NULL)
,(11188,'dict_data_type','dict_data_value','数据值',3,'1',NULL,'text            ','','1','like    ',NULL,'1','0','','','','0','',1,NULL,NULL)
,(11189,'dict_data_type','create_time','创建时间',4,'0',NULL,'text            ','','0','        ',NULL,'0','0','','','','0','',NULL,NULL,NULL)
,(11190,'dict_data_type','create_by','创建者',5,'0',NULL,'text            ','','0','        ',NULL,'0','0','','','','0','',NULL,NULL,NULL)
,(11191,'dict_data_type','update_time','更新时间',6,'0',NULL,'text            ','','0','        ',NULL,'0','0','','','','0','',NULL,NULL,NULL)
;
INSERT INTO SYSDBA.XXCOLUMN_DEFINITION (ID,TABLEIDENTITY,FIELD,"HEADER","SEQUENCE",EDITABLE,SORTABLE,"TYPE",SELECTURL,"SEARCH",SEARCHTYPE,LINK,ADDABLE,HIDDEN,REFTABLE,REFCOLUMN,REFVALUE,REQUIRED,REG,MINLENGTH,MAXLENGTH,"DISTINCT") VALUES 
(11192,'dict_data_type','update_by','更新者',7,'0',NULL,'text            ','','0','        ',NULL,'0','0','','','','0','',NULL,NULL,NULL)
,(11193,'dict_data_type','dict_data_desc','描述',8,'1',NULL,'text            ','','0','        ',NULL,'1','0','','','','0','',NULL,NULL,NULL)
,(1,'TEST','id','编号',1,'0',NULL,NULL,NULL,'0',NULL,NULL,'0','0',NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL)
,(2,'TEST','name','姓名',2,'0',NULL,NULL,NULL,'0',NULL,NULL,'0','0',NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL)
,(3,'TEST','age','年龄',3,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
,(4,'TEST','sex','性别',4,'0',NULL,NULL,NULL,'0',NULL,NULL,'0','0',NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL)
;