// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: calculation.proto

package com.iscas.biz.calculation.grpc;

/**
 * Protobuf type {@code com.iscas.biz.calculation.grpc.AdditionalForceHeadRequest}
 */
public  final class AdditionalForceHeadRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.iscas.biz.calculation.grpc.AdditionalForceHeadRequest)
    AdditionalForceHeadRequestOrBuilder {
  // Use AdditionalForceHeadRequest.newBuilder() to construct.
  private AdditionalForceHeadRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AdditionalForceHeadRequest() {
    freeboard_ = 0D;
    leiweihao_ = 0D;
    cangbiWeizhi_ = 0D;
    isCollision_ = false;
    shuidongYali_ = 0D;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private AdditionalForceHeadRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 9: {

            freeboard_ = input.readDouble();
            break;
          }
          case 17: {

            leiweihao_ = input.readDouble();
            break;
          }
          case 25: {

            cangbiWeizhi_ = input.readDouble();
            break;
          }
          case 32: {

            isCollision_ = input.readBool();
            break;
          }
          case 41: {

            shuidongYali_ = input.readDouble();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.iscas.biz.calculation.grpc.CalculationProto.internal_static_com_iscas_biz_calculation_grpc_AdditionalForceHeadRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.iscas.biz.calculation.grpc.CalculationProto.internal_static_com_iscas_biz_calculation_grpc_AdditionalForceHeadRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.iscas.biz.calculation.grpc.AdditionalForceHeadRequest.class, com.iscas.biz.calculation.grpc.AdditionalForceHeadRequest.Builder.class);
  }

  public static final int FREEBOARD_FIELD_NUMBER = 1;
  private double freeboard_;
  /**
   * <pre>
   *干舷高
   * </pre>
   *
   * <code>double freeboard = 1;</code>
   */
  public double getFreeboard() {
    return freeboard_;
  }

  public static final int LEIWEIHAO_FIELD_NUMBER = 2;
  private double leiweihao_;
  /**
   * <pre>
   *肋位号
   * </pre>
   *
   * <code>double leiweihao = 2;</code>
   */
  public double getLeiweihao() {
    return leiweihao_;
  }

  public static final int CANGBIWEIZHI_FIELD_NUMBER = 3;
  private double cangbiWeizhi_;
  /**
   * <pre>
   *舱壁位置
   * </pre>
   *
   * <code>double cangbiWeizhi = 3;</code>
   */
  public double getCangbiWeizhi() {
    return cangbiWeizhi_;
  }

  public static final int ISCOLLISION_FIELD_NUMBER = 4;
  private boolean isCollision_;
  /**
   * <pre>
   *是否防撞舱壁
   * </pre>
   *
   * <code>bool isCollision = 4;</code>
   */
  public boolean getIsCollision() {
    return isCollision_;
  }

  public static final int SHUIDONGYALI_FIELD_NUMBER = 5;
  private double shuidongYali_;
  /**
   * <pre>
   *水动压力
   * </pre>
   *
   * <code>double shuidongYali = 5;</code>
   */
  public double getShuidongYali() {
    return shuidongYali_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (freeboard_ != 0D) {
      output.writeDouble(1, freeboard_);
    }
    if (leiweihao_ != 0D) {
      output.writeDouble(2, leiweihao_);
    }
    if (cangbiWeizhi_ != 0D) {
      output.writeDouble(3, cangbiWeizhi_);
    }
    if (isCollision_ != false) {
      output.writeBool(4, isCollision_);
    }
    if (shuidongYali_ != 0D) {
      output.writeDouble(5, shuidongYali_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (freeboard_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(1, freeboard_);
    }
    if (leiweihao_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, leiweihao_);
    }
    if (cangbiWeizhi_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(3, cangbiWeizhi_);
    }
    if (isCollision_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, isCollision_);
    }
    if (shuidongYali_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(5, shuidongYali_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.iscas.biz.calculation.grpc.AdditionalForceHeadRequest)) {
      return super.equals(obj);
    }
    com.iscas.biz.calculation.grpc.AdditionalForceHeadRequest other = (com.iscas.biz.calculation.grpc.AdditionalForceHeadRequest) obj;

    boolean result = true;
    result = result && (
        java.lang.Double.doubleToLongBits(getFreeboard())
        == java.lang.Double.doubleToLongBits(
            other.getFreeboard()));
    result = result && (
        java.lang.Double.doubleToLongBits(getLeiweihao())
        == java.lang.Double.doubleToLongBits(
            other.getLeiweihao()));
    result = result && (
        java.lang.Double.doubleToLongBits(getCangbiWeizhi())
        == java.lang.Double.doubleToLongBits(
            other.getCangbiWeizhi()));
    result = result && (getIsCollision()
        == other.getIsCollision());
    result = result && (
        java.lang.Double.doubleToLongBits(getShuidongYali())
        == java.lang.Double.doubleToLongBits(
            other.getShuidongYali()));
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + FREEBOARD_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getFreeboard()));
    hash = (37 * hash) + LEIWEIHAO_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getLeiweihao()));
    hash = (37 * hash) + CANGBIWEIZHI_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getCangbiWeizhi()));
    hash = (37 * hash) + ISCOLLISION_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsCollision());
    hash = (37 * hash) + SHUIDONGYALI_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getShuidongYali()));
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.iscas.biz.calculation.grpc.AdditionalForceHeadRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.iscas.biz.calculation.grpc.AdditionalForceHeadRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.iscas.biz.calculation.grpc.AdditionalForceHeadRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.iscas.biz.calculation.grpc.AdditionalForceHeadRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.iscas.biz.calculation.grpc.AdditionalForceHeadRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.iscas.biz.calculation.grpc.AdditionalForceHeadRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.iscas.biz.calculation.grpc.AdditionalForceHeadRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.iscas.biz.calculation.grpc.AdditionalForceHeadRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.iscas.biz.calculation.grpc.AdditionalForceHeadRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.iscas.biz.calculation.grpc.AdditionalForceHeadRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.iscas.biz.calculation.grpc.AdditionalForceHeadRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.iscas.biz.calculation.grpc.AdditionalForceHeadRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.iscas.biz.calculation.grpc.AdditionalForceHeadRequest)
      com.iscas.biz.calculation.grpc.AdditionalForceHeadRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.iscas.biz.calculation.grpc.CalculationProto.internal_static_com_iscas_biz_calculation_grpc_AdditionalForceHeadRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.iscas.biz.calculation.grpc.CalculationProto.internal_static_com_iscas_biz_calculation_grpc_AdditionalForceHeadRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.iscas.biz.calculation.grpc.AdditionalForceHeadRequest.class, com.iscas.biz.calculation.grpc.AdditionalForceHeadRequest.Builder.class);
    }

    // Construct using com.iscas.biz.calculation.grpc.AdditionalForceHeadRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      freeboard_ = 0D;

      leiweihao_ = 0D;

      cangbiWeizhi_ = 0D;

      isCollision_ = false;

      shuidongYali_ = 0D;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.iscas.biz.calculation.grpc.CalculationProto.internal_static_com_iscas_biz_calculation_grpc_AdditionalForceHeadRequest_descriptor;
    }

    public com.iscas.biz.calculation.grpc.AdditionalForceHeadRequest getDefaultInstanceForType() {
      return com.iscas.biz.calculation.grpc.AdditionalForceHeadRequest.getDefaultInstance();
    }

    public com.iscas.biz.calculation.grpc.AdditionalForceHeadRequest build() {
      com.iscas.biz.calculation.grpc.AdditionalForceHeadRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.iscas.biz.calculation.grpc.AdditionalForceHeadRequest buildPartial() {
      com.iscas.biz.calculation.grpc.AdditionalForceHeadRequest result = new com.iscas.biz.calculation.grpc.AdditionalForceHeadRequest(this);
      result.freeboard_ = freeboard_;
      result.leiweihao_ = leiweihao_;
      result.cangbiWeizhi_ = cangbiWeizhi_;
      result.isCollision_ = isCollision_;
      result.shuidongYali_ = shuidongYali_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.iscas.biz.calculation.grpc.AdditionalForceHeadRequest) {
        return mergeFrom((com.iscas.biz.calculation.grpc.AdditionalForceHeadRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.iscas.biz.calculation.grpc.AdditionalForceHeadRequest other) {
      if (other == com.iscas.biz.calculation.grpc.AdditionalForceHeadRequest.getDefaultInstance()) return this;
      if (other.getFreeboard() != 0D) {
        setFreeboard(other.getFreeboard());
      }
      if (other.getLeiweihao() != 0D) {
        setLeiweihao(other.getLeiweihao());
      }
      if (other.getCangbiWeizhi() != 0D) {
        setCangbiWeizhi(other.getCangbiWeizhi());
      }
      if (other.getIsCollision() != false) {
        setIsCollision(other.getIsCollision());
      }
      if (other.getShuidongYali() != 0D) {
        setShuidongYali(other.getShuidongYali());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.iscas.biz.calculation.grpc.AdditionalForceHeadRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.iscas.biz.calculation.grpc.AdditionalForceHeadRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private double freeboard_ ;
    /**
     * <pre>
     *干舷高
     * </pre>
     *
     * <code>double freeboard = 1;</code>
     */
    public double getFreeboard() {
      return freeboard_;
    }
    /**
     * <pre>
     *干舷高
     * </pre>
     *
     * <code>double freeboard = 1;</code>
     */
    public Builder setFreeboard(double value) {
      
      freeboard_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *干舷高
     * </pre>
     *
     * <code>double freeboard = 1;</code>
     */
    public Builder clearFreeboard() {
      
      freeboard_ = 0D;
      onChanged();
      return this;
    }

    private double leiweihao_ ;
    /**
     * <pre>
     *肋位号
     * </pre>
     *
     * <code>double leiweihao = 2;</code>
     */
    public double getLeiweihao() {
      return leiweihao_;
    }
    /**
     * <pre>
     *肋位号
     * </pre>
     *
     * <code>double leiweihao = 2;</code>
     */
    public Builder setLeiweihao(double value) {
      
      leiweihao_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *肋位号
     * </pre>
     *
     * <code>double leiweihao = 2;</code>
     */
    public Builder clearLeiweihao() {
      
      leiweihao_ = 0D;
      onChanged();
      return this;
    }

    private double cangbiWeizhi_ ;
    /**
     * <pre>
     *舱壁位置
     * </pre>
     *
     * <code>double cangbiWeizhi = 3;</code>
     */
    public double getCangbiWeizhi() {
      return cangbiWeizhi_;
    }
    /**
     * <pre>
     *舱壁位置
     * </pre>
     *
     * <code>double cangbiWeizhi = 3;</code>
     */
    public Builder setCangbiWeizhi(double value) {
      
      cangbiWeizhi_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *舱壁位置
     * </pre>
     *
     * <code>double cangbiWeizhi = 3;</code>
     */
    public Builder clearCangbiWeizhi() {
      
      cangbiWeizhi_ = 0D;
      onChanged();
      return this;
    }

    private boolean isCollision_ ;
    /**
     * <pre>
     *是否防撞舱壁
     * </pre>
     *
     * <code>bool isCollision = 4;</code>
     */
    public boolean getIsCollision() {
      return isCollision_;
    }
    /**
     * <pre>
     *是否防撞舱壁
     * </pre>
     *
     * <code>bool isCollision = 4;</code>
     */
    public Builder setIsCollision(boolean value) {
      
      isCollision_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *是否防撞舱壁
     * </pre>
     *
     * <code>bool isCollision = 4;</code>
     */
    public Builder clearIsCollision() {
      
      isCollision_ = false;
      onChanged();
      return this;
    }

    private double shuidongYali_ ;
    /**
     * <pre>
     *水动压力
     * </pre>
     *
     * <code>double shuidongYali = 5;</code>
     */
    public double getShuidongYali() {
      return shuidongYali_;
    }
    /**
     * <pre>
     *水动压力
     * </pre>
     *
     * <code>double shuidongYali = 5;</code>
     */
    public Builder setShuidongYali(double value) {
      
      shuidongYali_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *水动压力
     * </pre>
     *
     * <code>double shuidongYali = 5;</code>
     */
    public Builder clearShuidongYali() {
      
      shuidongYali_ = 0D;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:com.iscas.biz.calculation.grpc.AdditionalForceHeadRequest)
  }

  // @@protoc_insertion_point(class_scope:com.iscas.biz.calculation.grpc.AdditionalForceHeadRequest)
  private static final com.iscas.biz.calculation.grpc.AdditionalForceHeadRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.iscas.biz.calculation.grpc.AdditionalForceHeadRequest();
  }

  public static com.iscas.biz.calculation.grpc.AdditionalForceHeadRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AdditionalForceHeadRequest>
      PARSER = new com.google.protobuf.AbstractParser<AdditionalForceHeadRequest>() {
    public AdditionalForceHeadRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new AdditionalForceHeadRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AdditionalForceHeadRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AdditionalForceHeadRequest> getParserForType() {
    return PARSER;
  }

  public com.iscas.biz.calculation.grpc.AdditionalForceHeadRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

