// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: calculation.proto

package com.iscas.biz.calculation.grpc;

public interface AdditionalForceHeadRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.iscas.biz.calculation.grpc.AdditionalForceHeadRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *干舷高
   * </pre>
   *
   * <code>double freeboard = 1;</code>
   */
  double getFreeboard();

  /**
   * <pre>
   *肋位号
   * </pre>
   *
   * <code>double leiweihao = 2;</code>
   */
  double getLeiweihao();

  /**
   * <pre>
   *舱壁位置
   * </pre>
   *
   * <code>double cangbiWeizhi = 3;</code>
   */
  double getCangbiWeizhi();

  /**
   * <pre>
   *是否防撞舱壁
   * </pre>
   *
   * <code>bool isCollision = 4;</code>
   */
  boolean getIsCollision();

  /**
   * <pre>
   *水动压力
   * </pre>
   *
   * <code>double shuidongYali = 5;</code>
   */
  double getShuidongYali();
}
