// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: calculation.proto

package com.iscas.biz.calculation.grpc;

/**
 * <pre>
 *球扁钢
 * </pre>
 *
 * Protobuf type {@code com.iscas.biz.calculation.grpc.BulbFlat}
 */
public  final class BulbFlat extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.iscas.biz.calculation.grpc.BulbFlat)
    BulbFlatOrBuilder {
  // Use BulbFlat.newBuilder() to construct.
  private BulbFlat(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BulbFlat() {
    model_ = "";
    height_ = 0D;
    width_ = 0D;
    thickness_ = 0D;
    sectionalArea_ = 0D;
    momentOfInertia_ = 0D;
    centroidPosition_ = 0D;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private BulbFlat(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            model_ = s;
            break;
          }
          case 17: {

            height_ = input.readDouble();
            break;
          }
          case 25: {

            width_ = input.readDouble();
            break;
          }
          case 33: {

            thickness_ = input.readDouble();
            break;
          }
          case 41: {

            sectionalArea_ = input.readDouble();
            break;
          }
          case 49: {

            momentOfInertia_ = input.readDouble();
            break;
          }
          case 57: {

            centroidPosition_ = input.readDouble();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.iscas.biz.calculation.grpc.CalculationProto.internal_static_com_iscas_biz_calculation_grpc_BulbFlat_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.iscas.biz.calculation.grpc.CalculationProto.internal_static_com_iscas_biz_calculation_grpc_BulbFlat_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.iscas.biz.calculation.grpc.BulbFlat.class, com.iscas.biz.calculation.grpc.BulbFlat.Builder.class);
  }

  public static final int MODEL_FIELD_NUMBER = 1;
  private volatile java.lang.Object model_;
  /**
   * <pre>
   *型号
   * </pre>
   *
   * <code>string model = 1;</code>
   */
  public java.lang.String getModel() {
    java.lang.Object ref = model_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      model_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *型号
   * </pre>
   *
   * <code>string model = 1;</code>
   */
  public com.google.protobuf.ByteString
      getModelBytes() {
    java.lang.Object ref = model_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      model_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int HEIGHT_FIELD_NUMBER = 2;
  private double height_;
  /**
   * <pre>
   * 高度(mm)
   * </pre>
   *
   * <code>double height = 2;</code>
   */
  public double getHeight() {
    return height_;
  }

  public static final int WIDTH_FIELD_NUMBER = 3;
  private double width_;
  /**
   * <pre>
   * 宽度(mm)
   * </pre>
   *
   * <code>double width = 3;</code>
   */
  public double getWidth() {
    return width_;
  }

  public static final int THICKNESS_FIELD_NUMBER = 4;
  private double thickness_;
  /**
   * <pre>
   * 厚度(mm)
   * </pre>
   *
   * <code>double thickness = 4;</code>
   */
  public double getThickness() {
    return thickness_;
  }

  public static final int SECTIONALAREA_FIELD_NUMBER = 5;
  private double sectionalArea_;
  /**
   * <pre>
   * 剖面积(cm²)
   * </pre>
   *
   * <code>double sectionalArea = 5;</code>
   */
  public double getSectionalArea() {
    return sectionalArea_;
  }

  public static final int MOMENTOFINERTIA_FIELD_NUMBER = 6;
  private double momentOfInertia_;
  /**
   * <pre>
   * 惯性矩(cm⁴)
   * </pre>
   *
   * <code>double momentOfInertia = 6;</code>
   */
  public double getMomentOfInertia() {
    return momentOfInertia_;
  }

  public static final int CENTROIDPOSITION_FIELD_NUMBER = 7;
  private double centroidPosition_;
  /**
   * <pre>
   * 形心位置(cm)
   * </pre>
   *
   * <code>double centroidPosition = 7;</code>
   */
  public double getCentroidPosition() {
    return centroidPosition_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getModelBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, model_);
    }
    if (height_ != 0D) {
      output.writeDouble(2, height_);
    }
    if (width_ != 0D) {
      output.writeDouble(3, width_);
    }
    if (thickness_ != 0D) {
      output.writeDouble(4, thickness_);
    }
    if (sectionalArea_ != 0D) {
      output.writeDouble(5, sectionalArea_);
    }
    if (momentOfInertia_ != 0D) {
      output.writeDouble(6, momentOfInertia_);
    }
    if (centroidPosition_ != 0D) {
      output.writeDouble(7, centroidPosition_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getModelBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, model_);
    }
    if (height_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, height_);
    }
    if (width_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(3, width_);
    }
    if (thickness_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(4, thickness_);
    }
    if (sectionalArea_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(5, sectionalArea_);
    }
    if (momentOfInertia_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(6, momentOfInertia_);
    }
    if (centroidPosition_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(7, centroidPosition_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.iscas.biz.calculation.grpc.BulbFlat)) {
      return super.equals(obj);
    }
    com.iscas.biz.calculation.grpc.BulbFlat other = (com.iscas.biz.calculation.grpc.BulbFlat) obj;

    boolean result = true;
    result = result && getModel()
        .equals(other.getModel());
    result = result && (
        java.lang.Double.doubleToLongBits(getHeight())
        == java.lang.Double.doubleToLongBits(
            other.getHeight()));
    result = result && (
        java.lang.Double.doubleToLongBits(getWidth())
        == java.lang.Double.doubleToLongBits(
            other.getWidth()));
    result = result && (
        java.lang.Double.doubleToLongBits(getThickness())
        == java.lang.Double.doubleToLongBits(
            other.getThickness()));
    result = result && (
        java.lang.Double.doubleToLongBits(getSectionalArea())
        == java.lang.Double.doubleToLongBits(
            other.getSectionalArea()));
    result = result && (
        java.lang.Double.doubleToLongBits(getMomentOfInertia())
        == java.lang.Double.doubleToLongBits(
            other.getMomentOfInertia()));
    result = result && (
        java.lang.Double.doubleToLongBits(getCentroidPosition())
        == java.lang.Double.doubleToLongBits(
            other.getCentroidPosition()));
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MODEL_FIELD_NUMBER;
    hash = (53 * hash) + getModel().hashCode();
    hash = (37 * hash) + HEIGHT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getHeight()));
    hash = (37 * hash) + WIDTH_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getWidth()));
    hash = (37 * hash) + THICKNESS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getThickness()));
    hash = (37 * hash) + SECTIONALAREA_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getSectionalArea()));
    hash = (37 * hash) + MOMENTOFINERTIA_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getMomentOfInertia()));
    hash = (37 * hash) + CENTROIDPOSITION_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getCentroidPosition()));
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.iscas.biz.calculation.grpc.BulbFlat parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.iscas.biz.calculation.grpc.BulbFlat parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.iscas.biz.calculation.grpc.BulbFlat parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.iscas.biz.calculation.grpc.BulbFlat parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.iscas.biz.calculation.grpc.BulbFlat parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.iscas.biz.calculation.grpc.BulbFlat parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.iscas.biz.calculation.grpc.BulbFlat parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.iscas.biz.calculation.grpc.BulbFlat parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.iscas.biz.calculation.grpc.BulbFlat parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.iscas.biz.calculation.grpc.BulbFlat parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.iscas.biz.calculation.grpc.BulbFlat prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *球扁钢
   * </pre>
   *
   * Protobuf type {@code com.iscas.biz.calculation.grpc.BulbFlat}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.iscas.biz.calculation.grpc.BulbFlat)
      com.iscas.biz.calculation.grpc.BulbFlatOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.iscas.biz.calculation.grpc.CalculationProto.internal_static_com_iscas_biz_calculation_grpc_BulbFlat_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.iscas.biz.calculation.grpc.CalculationProto.internal_static_com_iscas_biz_calculation_grpc_BulbFlat_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.iscas.biz.calculation.grpc.BulbFlat.class, com.iscas.biz.calculation.grpc.BulbFlat.Builder.class);
    }

    // Construct using com.iscas.biz.calculation.grpc.BulbFlat.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      model_ = "";

      height_ = 0D;

      width_ = 0D;

      thickness_ = 0D;

      sectionalArea_ = 0D;

      momentOfInertia_ = 0D;

      centroidPosition_ = 0D;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.iscas.biz.calculation.grpc.CalculationProto.internal_static_com_iscas_biz_calculation_grpc_BulbFlat_descriptor;
    }

    public com.iscas.biz.calculation.grpc.BulbFlat getDefaultInstanceForType() {
      return com.iscas.biz.calculation.grpc.BulbFlat.getDefaultInstance();
    }

    public com.iscas.biz.calculation.grpc.BulbFlat build() {
      com.iscas.biz.calculation.grpc.BulbFlat result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.iscas.biz.calculation.grpc.BulbFlat buildPartial() {
      com.iscas.biz.calculation.grpc.BulbFlat result = new com.iscas.biz.calculation.grpc.BulbFlat(this);
      result.model_ = model_;
      result.height_ = height_;
      result.width_ = width_;
      result.thickness_ = thickness_;
      result.sectionalArea_ = sectionalArea_;
      result.momentOfInertia_ = momentOfInertia_;
      result.centroidPosition_ = centroidPosition_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.iscas.biz.calculation.grpc.BulbFlat) {
        return mergeFrom((com.iscas.biz.calculation.grpc.BulbFlat)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.iscas.biz.calculation.grpc.BulbFlat other) {
      if (other == com.iscas.biz.calculation.grpc.BulbFlat.getDefaultInstance()) return this;
      if (!other.getModel().isEmpty()) {
        model_ = other.model_;
        onChanged();
      }
      if (other.getHeight() != 0D) {
        setHeight(other.getHeight());
      }
      if (other.getWidth() != 0D) {
        setWidth(other.getWidth());
      }
      if (other.getThickness() != 0D) {
        setThickness(other.getThickness());
      }
      if (other.getSectionalArea() != 0D) {
        setSectionalArea(other.getSectionalArea());
      }
      if (other.getMomentOfInertia() != 0D) {
        setMomentOfInertia(other.getMomentOfInertia());
      }
      if (other.getCentroidPosition() != 0D) {
        setCentroidPosition(other.getCentroidPosition());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.iscas.biz.calculation.grpc.BulbFlat parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.iscas.biz.calculation.grpc.BulbFlat) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object model_ = "";
    /**
     * <pre>
     *型号
     * </pre>
     *
     * <code>string model = 1;</code>
     */
    public java.lang.String getModel() {
      java.lang.Object ref = model_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        model_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *型号
     * </pre>
     *
     * <code>string model = 1;</code>
     */
    public com.google.protobuf.ByteString
        getModelBytes() {
      java.lang.Object ref = model_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        model_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *型号
     * </pre>
     *
     * <code>string model = 1;</code>
     */
    public Builder setModel(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      model_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *型号
     * </pre>
     *
     * <code>string model = 1;</code>
     */
    public Builder clearModel() {
      
      model_ = getDefaultInstance().getModel();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *型号
     * </pre>
     *
     * <code>string model = 1;</code>
     */
    public Builder setModelBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      model_ = value;
      onChanged();
      return this;
    }

    private double height_ ;
    /**
     * <pre>
     * 高度(mm)
     * </pre>
     *
     * <code>double height = 2;</code>
     */
    public double getHeight() {
      return height_;
    }
    /**
     * <pre>
     * 高度(mm)
     * </pre>
     *
     * <code>double height = 2;</code>
     */
    public Builder setHeight(double value) {
      
      height_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 高度(mm)
     * </pre>
     *
     * <code>double height = 2;</code>
     */
    public Builder clearHeight() {
      
      height_ = 0D;
      onChanged();
      return this;
    }

    private double width_ ;
    /**
     * <pre>
     * 宽度(mm)
     * </pre>
     *
     * <code>double width = 3;</code>
     */
    public double getWidth() {
      return width_;
    }
    /**
     * <pre>
     * 宽度(mm)
     * </pre>
     *
     * <code>double width = 3;</code>
     */
    public Builder setWidth(double value) {
      
      width_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 宽度(mm)
     * </pre>
     *
     * <code>double width = 3;</code>
     */
    public Builder clearWidth() {
      
      width_ = 0D;
      onChanged();
      return this;
    }

    private double thickness_ ;
    /**
     * <pre>
     * 厚度(mm)
     * </pre>
     *
     * <code>double thickness = 4;</code>
     */
    public double getThickness() {
      return thickness_;
    }
    /**
     * <pre>
     * 厚度(mm)
     * </pre>
     *
     * <code>double thickness = 4;</code>
     */
    public Builder setThickness(double value) {
      
      thickness_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 厚度(mm)
     * </pre>
     *
     * <code>double thickness = 4;</code>
     */
    public Builder clearThickness() {
      
      thickness_ = 0D;
      onChanged();
      return this;
    }

    private double sectionalArea_ ;
    /**
     * <pre>
     * 剖面积(cm²)
     * </pre>
     *
     * <code>double sectionalArea = 5;</code>
     */
    public double getSectionalArea() {
      return sectionalArea_;
    }
    /**
     * <pre>
     * 剖面积(cm²)
     * </pre>
     *
     * <code>double sectionalArea = 5;</code>
     */
    public Builder setSectionalArea(double value) {
      
      sectionalArea_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 剖面积(cm²)
     * </pre>
     *
     * <code>double sectionalArea = 5;</code>
     */
    public Builder clearSectionalArea() {
      
      sectionalArea_ = 0D;
      onChanged();
      return this;
    }

    private double momentOfInertia_ ;
    /**
     * <pre>
     * 惯性矩(cm⁴)
     * </pre>
     *
     * <code>double momentOfInertia = 6;</code>
     */
    public double getMomentOfInertia() {
      return momentOfInertia_;
    }
    /**
     * <pre>
     * 惯性矩(cm⁴)
     * </pre>
     *
     * <code>double momentOfInertia = 6;</code>
     */
    public Builder setMomentOfInertia(double value) {
      
      momentOfInertia_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 惯性矩(cm⁴)
     * </pre>
     *
     * <code>double momentOfInertia = 6;</code>
     */
    public Builder clearMomentOfInertia() {
      
      momentOfInertia_ = 0D;
      onChanged();
      return this;
    }

    private double centroidPosition_ ;
    /**
     * <pre>
     * 形心位置(cm)
     * </pre>
     *
     * <code>double centroidPosition = 7;</code>
     */
    public double getCentroidPosition() {
      return centroidPosition_;
    }
    /**
     * <pre>
     * 形心位置(cm)
     * </pre>
     *
     * <code>double centroidPosition = 7;</code>
     */
    public Builder setCentroidPosition(double value) {
      
      centroidPosition_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 形心位置(cm)
     * </pre>
     *
     * <code>double centroidPosition = 7;</code>
     */
    public Builder clearCentroidPosition() {
      
      centroidPosition_ = 0D;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:com.iscas.biz.calculation.grpc.BulbFlat)
  }

  // @@protoc_insertion_point(class_scope:com.iscas.biz.calculation.grpc.BulbFlat)
  private static final com.iscas.biz.calculation.grpc.BulbFlat DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.iscas.biz.calculation.grpc.BulbFlat();
  }

  public static com.iscas.biz.calculation.grpc.BulbFlat getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BulbFlat>
      PARSER = new com.google.protobuf.AbstractParser<BulbFlat>() {
    public BulbFlat parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new BulbFlat(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<BulbFlat> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BulbFlat> getParserForType() {
    return PARSER;
  }

  public com.iscas.biz.calculation.grpc.BulbFlat getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

