// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: calculation.proto

package com.iscas.biz.calculation.grpc;

public final class CalculationProto {
  private CalculationProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_iscas_biz_calculation_grpc_BuoyancyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_iscas_biz_calculation_grpc_BuoyancyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_iscas_biz_calculation_grpc_BuoyancyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_iscas_biz_calculation_grpc_BuoyancyResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_iscas_biz_calculation_grpc_Buoyant_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_iscas_biz_calculation_grpc_Buoyant_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_iscas_biz_calculation_grpc_ShipParamRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_iscas_biz_calculation_grpc_ShipParamRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_iscas_biz_calculation_grpc_ShipParamResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_iscas_biz_calculation_grpc_ShipParamResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_iscas_biz_calculation_grpc_WeightRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_iscas_biz_calculation_grpc_WeightRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_iscas_biz_calculation_grpc_WeightResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_iscas_biz_calculation_grpc_WeightResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_iscas_biz_calculation_grpc_WeightDistribution_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_iscas_biz_calculation_grpc_WeightDistribution_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_iscas_biz_calculation_grpc_Gravity_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_iscas_biz_calculation_grpc_Gravity_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_iscas_biz_calculation_grpc_SubGravity_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_iscas_biz_calculation_grpc_SubGravity_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_iscas_biz_calculation_grpc_StaticLoadRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_iscas_biz_calculation_grpc_StaticLoadRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_iscas_biz_calculation_grpc_StaticLoadResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_iscas_biz_calculation_grpc_StaticLoadResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_iscas_biz_calculation_grpc_WaveLoadRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_iscas_biz_calculation_grpc_WaveLoadRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_iscas_biz_calculation_grpc_WaveLoadResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_iscas_biz_calculation_grpc_WaveLoadResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_iscas_biz_calculation_grpc_SlamLoadRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_iscas_biz_calculation_grpc_SlamLoadRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_iscas_biz_calculation_grpc_SlamLoadResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_iscas_biz_calculation_grpc_SlamLoadResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_iscas_biz_calculation_grpc_SectionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_iscas_biz_calculation_grpc_SectionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_iscas_biz_calculation_grpc_SectionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_iscas_biz_calculation_grpc_SectionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_iscas_biz_calculation_grpc_GirderStrengthRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_iscas_biz_calculation_grpc_GirderStrengthRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_iscas_biz_calculation_grpc_GirderStrengthResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_iscas_biz_calculation_grpc_GirderStrengthResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_iscas_biz_calculation_grpc_DistRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_iscas_biz_calculation_grpc_DistRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_iscas_biz_calculation_grpc_DistResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_iscas_biz_calculation_grpc_DistResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021calculation.proto\022\036com.iscas.biz.calcu" +
      "lation.grpc\"\220\001\n\017BuoyancyRequest\022\027\n\017broje" +
      "anFilePath\030\001 \001(\t\022\035\n\025buoyancycurveFilePat" +
      "h\030\002 \001(\t\022\021\n\tprecision\030\003 \003(\001\022\016\n\006target\030\004 \001" +
      "(\005\022\n\n\002tm\030\005 \001(\001\022\n\n\002ta\030\006 \001(\001\022\n\n\002tf\030\007 \001(\001\"y" +
      "\n\020BuoyancyResponse\022\014\n\004code\030\001 \001(\005\022\017\n\007mess" +
      "age\030\002 \001(\t\022\r\n\005blist\030\003 \003(\001\0227\n\006calrst\030\004 \003(\013" +
      "2\'.com.iscas.biz.calculation.grpc.Buoyan" +
      "t\"\201\001\n\007Buoyant\022\022\n\nfloatforce\030\001 \001(\001\022\021\n\tflo" +
      "atxpos\030\002 \001(\001\022\n\n\002da\030\003 \001(\001\022\n\n\002dm\030\004 \001(\001\022\n\n\002",
      "df\030\005 \001(\001\022\r\n\005biasf\030\006 \001(\001\022\r\n\005biasx\030\007 \001(\001\022\r" +
      "\n\005index\030\010 \001(\005\"\300\001\n\020ShipParamRequest\022\014\n\004l_" +
      "wl\030\001 \001(\001\022\r\n\005width\030\002 \001(\001\022\r\n\005depth\030\003 \001(\001\022\017" +
      "\n\007draught\030\004 \001(\001\022\014\n\004area\030\005 \001(\005\022\021\n\tcheckTy" +
      "pe\030\006 \001(\005\022\024\n\014displacement\030\007 \001(\001\022\027\n\017portra" +
      "itGravity\030\010 \001(\001\022\021\n\tprinciple\030\n \001(\005\022\014\n\004ty" +
      "pe\030\013 \001(\t\"2\n\021ShipParamResponse\022\014\n\004code\030\001 " +
      "\001(\005\022\017\n\007message\030\002 \001(\t\"(\n\rWeightRequest\022\027\n" +
      "\017loadingFilePath\030\001 \001(\t\"\213\002\n\016WeightRespons" +
      "e\022\014\n\004code\030\001 \001(\005\022\017\n\007message\030\002 \001(\t\022O\n\023weig",
      "htDistributions\030\003 \003(\01322.com.iscas.biz.ca" +
      "lculation.grpc.WeightDistribution\022\016\n\006all" +
      "Dis\030\004 \003(\001\0227\n\006allRst\030\005 \001(\0132\'.com.iscas.bi" +
      "z.calculation.grpc.Gravity\022@\n\014subGraviti" +
      "es\030\006 \003(\0132*.com.iscas.biz.calculation.grp" +
      "c.SubGravity\"7\n\022WeightDistribution\022\014\n\004na" +
      "me\030\001 \001(\014\022\023\n\013weightItems\030\002 \003(\001\"+\n\007Gravity" +
      "\022\024\n\014displacement\030\001 \001(\001\022\n\n\002xg\030\002 \001(\001\"<\n\nSu" +
      "bGravity\022\014\n\004name\030\001 \001(\014\022\024\n\014displacement\030\002" +
      " \001(\001\022\n\n\002xg\030\003 \001(\001\"\023\n\021StaticLoadRequest\"N\n",
      "\022StaticLoadResponse\022\014\n\004nvec\030\001 \003(\001\022\014\n\004mve" +
      "c\030\002 \003(\001\022\r\n\005nvecM\030\003 \003(\001\022\r\n\005mvecM\030\004 \003(\001\"!\n" +
      "\017WaveLoadRequest\022\016\n\006height\030\001 \001(\001\"\264\001\n\020Wav" +
      "eLoadResponse\022\013\n\003mbb\030\001 \003(\001\022\016\n\006nwvecH\030\002 \003" +
      "(\001\022\016\n\006mwvecH\030\003 \003(\001\022\017\n\007nwvecMH\030\004 \003(\001\022\017\n\007m" +
      "wvecMH\030\005 \003(\001\022\017\n\007bdeltaS\030\006 \003(\001\022\016\n\006nwvecS\030" +
      "\007 \003(\001\022\016\n\006mwvecS\030\010 \003(\001\022\017\n\007nwvecMS\030\t \003(\001\022\017" +
      "\n\007mwvecMS\030\n \003(\001\" \n\017SlamLoadRequest\022\r\n\005sp" +
      "eed\030\001 \001(\001\"-\n\020SlamLoadResponse\022\014\n\004pwbm\030\001 " +
      "\003(\001\022\013\n\003nwb\030\002 \003(\001\")\n\016SectionRequest\022\027\n\017pr",
      "ofileFilePath\030\001 \001(\t\"\243\001\n\017SectionResponse\022" +
      "\024\n\014firstMoment0\030\001 \001(\001\022\020\n\010interia0\030\002 \001(\001\022" +
      "\016\n\006zaxisH\030\003 \001(\001\022\021\n\tfirstMomH\030\004 \001(\001\022\020\n\010in" +
      "teriaH\030\005 \001(\001\022\016\n\006zaxisS\030\006 \001(\001\022\021\n\tfirstMom" +
      "S\030\007 \001(\001\022\020\n\010interiaS\030\010 \001(\001\"A\n\025GirderStren" +
      "gthRequest\022\020\n\010kuaChang\030\001 \001(\001\022\026\n\016girderDi" +
      "stance\030\002 \001(\001\"\334\002\n\026GirderStrengthResponse\022" +
      "\020\n\010sigma1SH\030\001 \001(\001\022\022\n\nsigma1MidH\030\002 \001(\001\022\020\n" +
      "\010sigma1SS\030\003 \001(\001\022\022\n\nsigma1MidS\030\004 \001(\001\022\021\n\ts" +
      "tress2SH\030\005 \003(\001\022\023\n\013stress2MidH\030\006 \003(\001\022\022\n\ns",
      "tress3UpH\030\007 \003(\001\022\024\n\014stress3DownH\030\010 \003(\001\022\022\n" +
      "\nstress4UpH\030\t \003(\001\022\024\n\014stress4downH\030\n \003(\001\022" +
      "\021\n\tstress2SS\030\013 \003(\001\022\023\n\013stress2MidS\030\014 \003(\001\022" +
      "\022\n\nstress3UpS\030\r \003(\001\022\024\n\014stress3DownS\030\016 \003(" +
      "\001\022\022\n\nstress4UpS\030\017 \003(\001\022\024\n\014stress4downS\030\020 " +
      "\003(\001\"\r\n\013DistRequest\"2\n\014DistResponse\022\020\n\010ex" +
      "tremeH\030\001 \001(\001\022\020\n\010extremeS\030\002 \001(\0012\254\010\n\013Calcu" +
      "lation\022r\n\tshipParam\0220.com.iscas.biz.calc" +
      "ulation.grpc.ShipParamRequest\0321.com.isca" +
      "s.biz.calculation.grpc.ShipParamResponse",
      "\"\000\022o\n\010buoyancy\022/.com.iscas.biz.calculati" +
      "on.grpc.BuoyancyRequest\0320.com.iscas.biz." +
      "calculation.grpc.BuoyancyResponse\"\000\022v\n\023c" +
      "alWeightDistribute\022-.com.iscas.biz.calcu" +
      "lation.grpc.WeightRequest\032..com.iscas.bi" +
      "z.calculation.grpc.WeightResponse\"\000\022x\n\rc" +
      "alStaticLoad\0221.com.iscas.biz.calculation" +
      ".grpc.StaticLoadRequest\0322.com.iscas.biz." +
      "calculation.grpc.StaticLoadResponse\"\000\022r\n" +
      "\013calWaveLoad\022/.com.iscas.biz.calculation",
      ".grpc.WaveLoadRequest\0320.com.iscas.biz.ca" +
      "lculation.grpc.WaveLoadResponse\"\000\022r\n\013cal" +
      "SlamLoad\022/.com.iscas.biz.calculation.grp" +
      "c.SlamLoadRequest\0320.com.iscas.biz.calcul" +
      "ation.grpc.SlamLoadResponse\"\000\022o\n\ncalSect" +
      "ion\022..com.iscas.biz.calculation.grpc.Sec" +
      "tionRequest\032/.com.iscas.biz.calculation." +
      "grpc.SectionResponse\"\000\022\204\001\n\021calGirderStre" +
      "ngth\0225.com.iscas.biz.calculation.grpc.Gi" +
      "rderStrengthRequest\0326.com.iscas.biz.calc",
      "ulation.grpc.GirderStrengthResponse\"\000\022f\n" +
      "\007calDist\022+.com.iscas.biz.calculation.grp" +
      "c.DistRequest\032,.com.iscas.biz.calculatio" +
      "n.grpc.DistResponse\"\000B4\n\036com.iscas.biz.c" +
      "alculation.grpcB\020CalculationProtoP\001b\006pro" +
      "to3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_iscas_biz_calculation_grpc_BuoyancyRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_iscas_biz_calculation_grpc_BuoyancyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_iscas_biz_calculation_grpc_BuoyancyRequest_descriptor,
        new java.lang.String[] { "BrojeanFilePath", "BuoyancycurveFilePath", "Precision", "Target", "Tm", "Ta", "Tf", });
    internal_static_com_iscas_biz_calculation_grpc_BuoyancyResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_iscas_biz_calculation_grpc_BuoyancyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_iscas_biz_calculation_grpc_BuoyancyResponse_descriptor,
        new java.lang.String[] { "Code", "Message", "Blist", "Calrst", });
    internal_static_com_iscas_biz_calculation_grpc_Buoyant_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_iscas_biz_calculation_grpc_Buoyant_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_iscas_biz_calculation_grpc_Buoyant_descriptor,
        new java.lang.String[] { "Floatforce", "Floatxpos", "Da", "Dm", "Df", "Biasf", "Biasx", "Index", });
    internal_static_com_iscas_biz_calculation_grpc_ShipParamRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_iscas_biz_calculation_grpc_ShipParamRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_iscas_biz_calculation_grpc_ShipParamRequest_descriptor,
        new java.lang.String[] { "LWl", "Width", "Depth", "Draught", "Area", "CheckType", "Displacement", "PortraitGravity", "Principle", "Type", });
    internal_static_com_iscas_biz_calculation_grpc_ShipParamResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_iscas_biz_calculation_grpc_ShipParamResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_iscas_biz_calculation_grpc_ShipParamResponse_descriptor,
        new java.lang.String[] { "Code", "Message", });
    internal_static_com_iscas_biz_calculation_grpc_WeightRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_iscas_biz_calculation_grpc_WeightRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_iscas_biz_calculation_grpc_WeightRequest_descriptor,
        new java.lang.String[] { "LoadingFilePath", });
    internal_static_com_iscas_biz_calculation_grpc_WeightResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_com_iscas_biz_calculation_grpc_WeightResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_iscas_biz_calculation_grpc_WeightResponse_descriptor,
        new java.lang.String[] { "Code", "Message", "WeightDistributions", "AllDis", "AllRst", "SubGravities", });
    internal_static_com_iscas_biz_calculation_grpc_WeightDistribution_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_com_iscas_biz_calculation_grpc_WeightDistribution_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_iscas_biz_calculation_grpc_WeightDistribution_descriptor,
        new java.lang.String[] { "Name", "WeightItems", });
    internal_static_com_iscas_biz_calculation_grpc_Gravity_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_com_iscas_biz_calculation_grpc_Gravity_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_iscas_biz_calculation_grpc_Gravity_descriptor,
        new java.lang.String[] { "Displacement", "Xg", });
    internal_static_com_iscas_biz_calculation_grpc_SubGravity_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_com_iscas_biz_calculation_grpc_SubGravity_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_iscas_biz_calculation_grpc_SubGravity_descriptor,
        new java.lang.String[] { "Name", "Displacement", "Xg", });
    internal_static_com_iscas_biz_calculation_grpc_StaticLoadRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_com_iscas_biz_calculation_grpc_StaticLoadRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_iscas_biz_calculation_grpc_StaticLoadRequest_descriptor,
        new java.lang.String[] { });
    internal_static_com_iscas_biz_calculation_grpc_StaticLoadResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_com_iscas_biz_calculation_grpc_StaticLoadResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_iscas_biz_calculation_grpc_StaticLoadResponse_descriptor,
        new java.lang.String[] { "Nvec", "Mvec", "NvecM", "MvecM", });
    internal_static_com_iscas_biz_calculation_grpc_WaveLoadRequest_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_com_iscas_biz_calculation_grpc_WaveLoadRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_iscas_biz_calculation_grpc_WaveLoadRequest_descriptor,
        new java.lang.String[] { "Height", });
    internal_static_com_iscas_biz_calculation_grpc_WaveLoadResponse_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_com_iscas_biz_calculation_grpc_WaveLoadResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_iscas_biz_calculation_grpc_WaveLoadResponse_descriptor,
        new java.lang.String[] { "Mbb", "NwvecH", "MwvecH", "NwvecMH", "MwvecMH", "BdeltaS", "NwvecS", "MwvecS", "NwvecMS", "MwvecMS", });
    internal_static_com_iscas_biz_calculation_grpc_SlamLoadRequest_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_com_iscas_biz_calculation_grpc_SlamLoadRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_iscas_biz_calculation_grpc_SlamLoadRequest_descriptor,
        new java.lang.String[] { "Speed", });
    internal_static_com_iscas_biz_calculation_grpc_SlamLoadResponse_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_com_iscas_biz_calculation_grpc_SlamLoadResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_iscas_biz_calculation_grpc_SlamLoadResponse_descriptor,
        new java.lang.String[] { "Pwbm", "Nwb", });
    internal_static_com_iscas_biz_calculation_grpc_SectionRequest_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_com_iscas_biz_calculation_grpc_SectionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_iscas_biz_calculation_grpc_SectionRequest_descriptor,
        new java.lang.String[] { "ProfileFilePath", });
    internal_static_com_iscas_biz_calculation_grpc_SectionResponse_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_com_iscas_biz_calculation_grpc_SectionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_iscas_biz_calculation_grpc_SectionResponse_descriptor,
        new java.lang.String[] { "FirstMoment0", "Interia0", "ZaxisH", "FirstMomH", "InteriaH", "ZaxisS", "FirstMomS", "InteriaS", });
    internal_static_com_iscas_biz_calculation_grpc_GirderStrengthRequest_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_com_iscas_biz_calculation_grpc_GirderStrengthRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_iscas_biz_calculation_grpc_GirderStrengthRequest_descriptor,
        new java.lang.String[] { "KuaChang", "GirderDistance", });
    internal_static_com_iscas_biz_calculation_grpc_GirderStrengthResponse_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_com_iscas_biz_calculation_grpc_GirderStrengthResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_iscas_biz_calculation_grpc_GirderStrengthResponse_descriptor,
        new java.lang.String[] { "Sigma1SH", "Sigma1MidH", "Sigma1SS", "Sigma1MidS", "Stress2SH", "Stress2MidH", "Stress3UpH", "Stress3DownH", "Stress4UpH", "Stress4DownH", "Stress2SS", "Stress2MidS", "Stress3UpS", "Stress3DownS", "Stress4UpS", "Stress4DownS", });
    internal_static_com_iscas_biz_calculation_grpc_DistRequest_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_com_iscas_biz_calculation_grpc_DistRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_iscas_biz_calculation_grpc_DistRequest_descriptor,
        new java.lang.String[] { });
    internal_static_com_iscas_biz_calculation_grpc_DistResponse_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_com_iscas_biz_calculation_grpc_DistResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_iscas_biz_calculation_grpc_DistResponse_descriptor,
        new java.lang.String[] { "ExtremeH", "ExtremeS", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
