// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: calculation.proto

package com.iscas.biz.calculation.grpc;

/**
 * <pre>
 *剖面计算输出
 * </pre>
 *
 * Protobuf type {@code com.iscas.biz.calculation.grpc.SectionResponse}
 */
public  final class SectionResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.iscas.biz.calculation.grpc.SectionResponse)
    SectionResponseOrBuilder {
  // Use SectionResponse.newBuilder() to construct.
  private SectionResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SectionResponse() {
    firstMoment0_ = 0D;
    interia0_ = 0D;
    zaxisH_ = 0D;
    firstMomH_ = 0D;
    interiaH_ = 0D;
    zaxisS_ = 0D;
    firstMomS_ = 0D;
    interiaS_ = 0D;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private SectionResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 9: {

            firstMoment0_ = input.readDouble();
            break;
          }
          case 17: {

            interia0_ = input.readDouble();
            break;
          }
          case 25: {

            zaxisH_ = input.readDouble();
            break;
          }
          case 33: {

            firstMomH_ = input.readDouble();
            break;
          }
          case 41: {

            interiaH_ = input.readDouble();
            break;
          }
          case 49: {

            zaxisS_ = input.readDouble();
            break;
          }
          case 57: {

            firstMomS_ = input.readDouble();
            break;
          }
          case 65: {

            interiaS_ = input.readDouble();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.iscas.biz.calculation.grpc.CalculationProto.internal_static_com_iscas_biz_calculation_grpc_SectionResponse_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.iscas.biz.calculation.grpc.CalculationProto.internal_static_com_iscas_biz_calculation_grpc_SectionResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.iscas.biz.calculation.grpc.SectionResponse.class, com.iscas.biz.calculation.grpc.SectionResponse.Builder.class);
  }

  public static final int FIRSTMOMENT0_FIELD_NUMBER = 1;
  private double firstMoment0_;
  /**
   * <pre>
   *初始静矩
   * </pre>
   *
   * <code>double firstMoment0 = 1;</code>
   */
  public double getFirstMoment0() {
    return firstMoment0_;
  }

  public static final int INTERIA0_FIELD_NUMBER = 2;
  private double interia0_;
  /**
   * <pre>
   *惯性矩
   * </pre>
   *
   * <code>double interia0 = 2;</code>
   */
  public double getInteria0() {
    return interia0_;
  }

  public static final int ZAXISH_FIELD_NUMBER = 3;
  private double zaxisH_;
  /**
   * <pre>
   *中拱时的中和轴
   * </pre>
   *
   * <code>double zaxisH = 3;</code>
   */
  public double getZaxisH() {
    return zaxisH_;
  }

  public static final int FIRSTMOMH_FIELD_NUMBER = 4;
  private double firstMomH_;
  /**
   * <pre>
   *中拱时静矩
   * </pre>
   *
   * <code>double firstMomH = 4;</code>
   */
  public double getFirstMomH() {
    return firstMomH_;
  }

  public static final int INTERIAH_FIELD_NUMBER = 5;
  private double interiaH_;
  /**
   * <pre>
   *中拱时惯性矩
   * </pre>
   *
   * <code>double interiaH = 5;</code>
   */
  public double getInteriaH() {
    return interiaH_;
  }

  public static final int ZAXISS_FIELD_NUMBER = 6;
  private double zaxisS_;
  /**
   * <pre>
   *中垂时的中和轴
   * </pre>
   *
   * <code>double zaxisS = 6;</code>
   */
  public double getZaxisS() {
    return zaxisS_;
  }

  public static final int FIRSTMOMS_FIELD_NUMBER = 7;
  private double firstMomS_;
  /**
   * <pre>
   *中垂时静矩
   * </pre>
   *
   * <code>double firstMomS = 7;</code>
   */
  public double getFirstMomS() {
    return firstMomS_;
  }

  public static final int INTERIAS_FIELD_NUMBER = 8;
  private double interiaS_;
  /**
   * <pre>
   *中垂时惯性矩
   * </pre>
   *
   * <code>double interiaS = 8;</code>
   */
  public double getInteriaS() {
    return interiaS_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (firstMoment0_ != 0D) {
      output.writeDouble(1, firstMoment0_);
    }
    if (interia0_ != 0D) {
      output.writeDouble(2, interia0_);
    }
    if (zaxisH_ != 0D) {
      output.writeDouble(3, zaxisH_);
    }
    if (firstMomH_ != 0D) {
      output.writeDouble(4, firstMomH_);
    }
    if (interiaH_ != 0D) {
      output.writeDouble(5, interiaH_);
    }
    if (zaxisS_ != 0D) {
      output.writeDouble(6, zaxisS_);
    }
    if (firstMomS_ != 0D) {
      output.writeDouble(7, firstMomS_);
    }
    if (interiaS_ != 0D) {
      output.writeDouble(8, interiaS_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (firstMoment0_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(1, firstMoment0_);
    }
    if (interia0_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, interia0_);
    }
    if (zaxisH_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(3, zaxisH_);
    }
    if (firstMomH_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(4, firstMomH_);
    }
    if (interiaH_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(5, interiaH_);
    }
    if (zaxisS_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(6, zaxisS_);
    }
    if (firstMomS_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(7, firstMomS_);
    }
    if (interiaS_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(8, interiaS_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.iscas.biz.calculation.grpc.SectionResponse)) {
      return super.equals(obj);
    }
    com.iscas.biz.calculation.grpc.SectionResponse other = (com.iscas.biz.calculation.grpc.SectionResponse) obj;

    boolean result = true;
    result = result && (
        java.lang.Double.doubleToLongBits(getFirstMoment0())
        == java.lang.Double.doubleToLongBits(
            other.getFirstMoment0()));
    result = result && (
        java.lang.Double.doubleToLongBits(getInteria0())
        == java.lang.Double.doubleToLongBits(
            other.getInteria0()));
    result = result && (
        java.lang.Double.doubleToLongBits(getZaxisH())
        == java.lang.Double.doubleToLongBits(
            other.getZaxisH()));
    result = result && (
        java.lang.Double.doubleToLongBits(getFirstMomH())
        == java.lang.Double.doubleToLongBits(
            other.getFirstMomH()));
    result = result && (
        java.lang.Double.doubleToLongBits(getInteriaH())
        == java.lang.Double.doubleToLongBits(
            other.getInteriaH()));
    result = result && (
        java.lang.Double.doubleToLongBits(getZaxisS())
        == java.lang.Double.doubleToLongBits(
            other.getZaxisS()));
    result = result && (
        java.lang.Double.doubleToLongBits(getFirstMomS())
        == java.lang.Double.doubleToLongBits(
            other.getFirstMomS()));
    result = result && (
        java.lang.Double.doubleToLongBits(getInteriaS())
        == java.lang.Double.doubleToLongBits(
            other.getInteriaS()));
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + FIRSTMOMENT0_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getFirstMoment0()));
    hash = (37 * hash) + INTERIA0_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getInteria0()));
    hash = (37 * hash) + ZAXISH_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getZaxisH()));
    hash = (37 * hash) + FIRSTMOMH_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getFirstMomH()));
    hash = (37 * hash) + INTERIAH_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getInteriaH()));
    hash = (37 * hash) + ZAXISS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getZaxisS()));
    hash = (37 * hash) + FIRSTMOMS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getFirstMomS()));
    hash = (37 * hash) + INTERIAS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getInteriaS()));
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.iscas.biz.calculation.grpc.SectionResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.iscas.biz.calculation.grpc.SectionResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.iscas.biz.calculation.grpc.SectionResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.iscas.biz.calculation.grpc.SectionResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.iscas.biz.calculation.grpc.SectionResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.iscas.biz.calculation.grpc.SectionResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.iscas.biz.calculation.grpc.SectionResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.iscas.biz.calculation.grpc.SectionResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.iscas.biz.calculation.grpc.SectionResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.iscas.biz.calculation.grpc.SectionResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.iscas.biz.calculation.grpc.SectionResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *剖面计算输出
   * </pre>
   *
   * Protobuf type {@code com.iscas.biz.calculation.grpc.SectionResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.iscas.biz.calculation.grpc.SectionResponse)
      com.iscas.biz.calculation.grpc.SectionResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.iscas.biz.calculation.grpc.CalculationProto.internal_static_com_iscas_biz_calculation_grpc_SectionResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.iscas.biz.calculation.grpc.CalculationProto.internal_static_com_iscas_biz_calculation_grpc_SectionResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.iscas.biz.calculation.grpc.SectionResponse.class, com.iscas.biz.calculation.grpc.SectionResponse.Builder.class);
    }

    // Construct using com.iscas.biz.calculation.grpc.SectionResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      firstMoment0_ = 0D;

      interia0_ = 0D;

      zaxisH_ = 0D;

      firstMomH_ = 0D;

      interiaH_ = 0D;

      zaxisS_ = 0D;

      firstMomS_ = 0D;

      interiaS_ = 0D;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.iscas.biz.calculation.grpc.CalculationProto.internal_static_com_iscas_biz_calculation_grpc_SectionResponse_descriptor;
    }

    public com.iscas.biz.calculation.grpc.SectionResponse getDefaultInstanceForType() {
      return com.iscas.biz.calculation.grpc.SectionResponse.getDefaultInstance();
    }

    public com.iscas.biz.calculation.grpc.SectionResponse build() {
      com.iscas.biz.calculation.grpc.SectionResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.iscas.biz.calculation.grpc.SectionResponse buildPartial() {
      com.iscas.biz.calculation.grpc.SectionResponse result = new com.iscas.biz.calculation.grpc.SectionResponse(this);
      result.firstMoment0_ = firstMoment0_;
      result.interia0_ = interia0_;
      result.zaxisH_ = zaxisH_;
      result.firstMomH_ = firstMomH_;
      result.interiaH_ = interiaH_;
      result.zaxisS_ = zaxisS_;
      result.firstMomS_ = firstMomS_;
      result.interiaS_ = interiaS_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.iscas.biz.calculation.grpc.SectionResponse) {
        return mergeFrom((com.iscas.biz.calculation.grpc.SectionResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.iscas.biz.calculation.grpc.SectionResponse other) {
      if (other == com.iscas.biz.calculation.grpc.SectionResponse.getDefaultInstance()) return this;
      if (other.getFirstMoment0() != 0D) {
        setFirstMoment0(other.getFirstMoment0());
      }
      if (other.getInteria0() != 0D) {
        setInteria0(other.getInteria0());
      }
      if (other.getZaxisH() != 0D) {
        setZaxisH(other.getZaxisH());
      }
      if (other.getFirstMomH() != 0D) {
        setFirstMomH(other.getFirstMomH());
      }
      if (other.getInteriaH() != 0D) {
        setInteriaH(other.getInteriaH());
      }
      if (other.getZaxisS() != 0D) {
        setZaxisS(other.getZaxisS());
      }
      if (other.getFirstMomS() != 0D) {
        setFirstMomS(other.getFirstMomS());
      }
      if (other.getInteriaS() != 0D) {
        setInteriaS(other.getInteriaS());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.iscas.biz.calculation.grpc.SectionResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.iscas.biz.calculation.grpc.SectionResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private double firstMoment0_ ;
    /**
     * <pre>
     *初始静矩
     * </pre>
     *
     * <code>double firstMoment0 = 1;</code>
     */
    public double getFirstMoment0() {
      return firstMoment0_;
    }
    /**
     * <pre>
     *初始静矩
     * </pre>
     *
     * <code>double firstMoment0 = 1;</code>
     */
    public Builder setFirstMoment0(double value) {
      
      firstMoment0_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *初始静矩
     * </pre>
     *
     * <code>double firstMoment0 = 1;</code>
     */
    public Builder clearFirstMoment0() {
      
      firstMoment0_ = 0D;
      onChanged();
      return this;
    }

    private double interia0_ ;
    /**
     * <pre>
     *惯性矩
     * </pre>
     *
     * <code>double interia0 = 2;</code>
     */
    public double getInteria0() {
      return interia0_;
    }
    /**
     * <pre>
     *惯性矩
     * </pre>
     *
     * <code>double interia0 = 2;</code>
     */
    public Builder setInteria0(double value) {
      
      interia0_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *惯性矩
     * </pre>
     *
     * <code>double interia0 = 2;</code>
     */
    public Builder clearInteria0() {
      
      interia0_ = 0D;
      onChanged();
      return this;
    }

    private double zaxisH_ ;
    /**
     * <pre>
     *中拱时的中和轴
     * </pre>
     *
     * <code>double zaxisH = 3;</code>
     */
    public double getZaxisH() {
      return zaxisH_;
    }
    /**
     * <pre>
     *中拱时的中和轴
     * </pre>
     *
     * <code>double zaxisH = 3;</code>
     */
    public Builder setZaxisH(double value) {
      
      zaxisH_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *中拱时的中和轴
     * </pre>
     *
     * <code>double zaxisH = 3;</code>
     */
    public Builder clearZaxisH() {
      
      zaxisH_ = 0D;
      onChanged();
      return this;
    }

    private double firstMomH_ ;
    /**
     * <pre>
     *中拱时静矩
     * </pre>
     *
     * <code>double firstMomH = 4;</code>
     */
    public double getFirstMomH() {
      return firstMomH_;
    }
    /**
     * <pre>
     *中拱时静矩
     * </pre>
     *
     * <code>double firstMomH = 4;</code>
     */
    public Builder setFirstMomH(double value) {
      
      firstMomH_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *中拱时静矩
     * </pre>
     *
     * <code>double firstMomH = 4;</code>
     */
    public Builder clearFirstMomH() {
      
      firstMomH_ = 0D;
      onChanged();
      return this;
    }

    private double interiaH_ ;
    /**
     * <pre>
     *中拱时惯性矩
     * </pre>
     *
     * <code>double interiaH = 5;</code>
     */
    public double getInteriaH() {
      return interiaH_;
    }
    /**
     * <pre>
     *中拱时惯性矩
     * </pre>
     *
     * <code>double interiaH = 5;</code>
     */
    public Builder setInteriaH(double value) {
      
      interiaH_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *中拱时惯性矩
     * </pre>
     *
     * <code>double interiaH = 5;</code>
     */
    public Builder clearInteriaH() {
      
      interiaH_ = 0D;
      onChanged();
      return this;
    }

    private double zaxisS_ ;
    /**
     * <pre>
     *中垂时的中和轴
     * </pre>
     *
     * <code>double zaxisS = 6;</code>
     */
    public double getZaxisS() {
      return zaxisS_;
    }
    /**
     * <pre>
     *中垂时的中和轴
     * </pre>
     *
     * <code>double zaxisS = 6;</code>
     */
    public Builder setZaxisS(double value) {
      
      zaxisS_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *中垂时的中和轴
     * </pre>
     *
     * <code>double zaxisS = 6;</code>
     */
    public Builder clearZaxisS() {
      
      zaxisS_ = 0D;
      onChanged();
      return this;
    }

    private double firstMomS_ ;
    /**
     * <pre>
     *中垂时静矩
     * </pre>
     *
     * <code>double firstMomS = 7;</code>
     */
    public double getFirstMomS() {
      return firstMomS_;
    }
    /**
     * <pre>
     *中垂时静矩
     * </pre>
     *
     * <code>double firstMomS = 7;</code>
     */
    public Builder setFirstMomS(double value) {
      
      firstMomS_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *中垂时静矩
     * </pre>
     *
     * <code>double firstMomS = 7;</code>
     */
    public Builder clearFirstMomS() {
      
      firstMomS_ = 0D;
      onChanged();
      return this;
    }

    private double interiaS_ ;
    /**
     * <pre>
     *中垂时惯性矩
     * </pre>
     *
     * <code>double interiaS = 8;</code>
     */
    public double getInteriaS() {
      return interiaS_;
    }
    /**
     * <pre>
     *中垂时惯性矩
     * </pre>
     *
     * <code>double interiaS = 8;</code>
     */
    public Builder setInteriaS(double value) {
      
      interiaS_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *中垂时惯性矩
     * </pre>
     *
     * <code>double interiaS = 8;</code>
     */
    public Builder clearInteriaS() {
      
      interiaS_ = 0D;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:com.iscas.biz.calculation.grpc.SectionResponse)
  }

  // @@protoc_insertion_point(class_scope:com.iscas.biz.calculation.grpc.SectionResponse)
  private static final com.iscas.biz.calculation.grpc.SectionResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.iscas.biz.calculation.grpc.SectionResponse();
  }

  public static com.iscas.biz.calculation.grpc.SectionResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SectionResponse>
      PARSER = new com.google.protobuf.AbstractParser<SectionResponse>() {
    public SectionResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new SectionResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SectionResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SectionResponse> getParserForType() {
    return PARSER;
  }

  public com.iscas.biz.calculation.grpc.SectionResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

