// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: calculation.proto

package com.iscas.biz.calculation.grpc;

/**
 * <pre>
 *剖面计算输入
 * </pre>
 *
 * Protobuf type {@code com.iscas.biz.calculation.grpc.SectionRequest}
 */
public  final class SectionRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.iscas.biz.calculation.grpc.SectionRequest)
    SectionRequestOrBuilder {
  // Use SectionRequest.newBuilder() to construct.
  private SectionRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SectionRequest() {
    profileFilePath_ = "";
    ribNumber_ = 0D;
    bulbFlats_ = java.util.Collections.emptyList();
    tProfiles_ = java.util.Collections.emptyList();
    isHalfProfile_ = false;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private SectionRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            profileFilePath_ = s;
            break;
          }
          case 17: {

            ribNumber_ = input.readDouble();
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              bulbFlats_ = new java.util.ArrayList<com.iscas.biz.calculation.grpc.BulbFlat>();
              mutable_bitField0_ |= 0x00000004;
            }
            bulbFlats_.add(
                input.readMessage(com.iscas.biz.calculation.grpc.BulbFlat.parser(), extensionRegistry));
            break;
          }
          case 34: {
            if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
              tProfiles_ = new java.util.ArrayList<com.iscas.biz.calculation.grpc.TProfile>();
              mutable_bitField0_ |= 0x00000008;
            }
            tProfiles_.add(
                input.readMessage(com.iscas.biz.calculation.grpc.TProfile.parser(), extensionRegistry));
            break;
          }
          case 40: {

            isHalfProfile_ = input.readBool();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
        bulbFlats_ = java.util.Collections.unmodifiableList(bulbFlats_);
      }
      if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
        tProfiles_ = java.util.Collections.unmodifiableList(tProfiles_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.iscas.biz.calculation.grpc.CalculationProto.internal_static_com_iscas_biz_calculation_grpc_SectionRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.iscas.biz.calculation.grpc.CalculationProto.internal_static_com_iscas_biz_calculation_grpc_SectionRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.iscas.biz.calculation.grpc.SectionRequest.class, com.iscas.biz.calculation.grpc.SectionRequest.Builder.class);
  }

  private int bitField0_;
  public static final int PROFILEFILEPATH_FIELD_NUMBER = 1;
  private volatile java.lang.Object profileFilePath_;
  /**
   * <pre>
   *剖面文件路径
   * </pre>
   *
   * <code>string profileFilePath = 1;</code>
   */
  public java.lang.String getProfileFilePath() {
    java.lang.Object ref = profileFilePath_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      profileFilePath_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *剖面文件路径
   * </pre>
   *
   * <code>string profileFilePath = 1;</code>
   */
  public com.google.protobuf.ByteString
      getProfileFilePathBytes() {
    java.lang.Object ref = profileFilePath_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      profileFilePath_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RIBNUMBER_FIELD_NUMBER = 2;
  private double ribNumber_;
  /**
   * <pre>
   *肋位号
   * </pre>
   *
   * <code>double ribNumber = 2;</code>
   */
  public double getRibNumber() {
    return ribNumber_;
  }

  public static final int BULBFLATS_FIELD_NUMBER = 3;
  private java.util.List<com.iscas.biz.calculation.grpc.BulbFlat> bulbFlats_;
  /**
   * <pre>
   *球扁钢数组
   * </pre>
   *
   * <code>repeated .com.iscas.biz.calculation.grpc.BulbFlat bulbFlats = 3;</code>
   */
  public java.util.List<com.iscas.biz.calculation.grpc.BulbFlat> getBulbFlatsList() {
    return bulbFlats_;
  }
  /**
   * <pre>
   *球扁钢数组
   * </pre>
   *
   * <code>repeated .com.iscas.biz.calculation.grpc.BulbFlat bulbFlats = 3;</code>
   */
  public java.util.List<? extends com.iscas.biz.calculation.grpc.BulbFlatOrBuilder> 
      getBulbFlatsOrBuilderList() {
    return bulbFlats_;
  }
  /**
   * <pre>
   *球扁钢数组
   * </pre>
   *
   * <code>repeated .com.iscas.biz.calculation.grpc.BulbFlat bulbFlats = 3;</code>
   */
  public int getBulbFlatsCount() {
    return bulbFlats_.size();
  }
  /**
   * <pre>
   *球扁钢数组
   * </pre>
   *
   * <code>repeated .com.iscas.biz.calculation.grpc.BulbFlat bulbFlats = 3;</code>
   */
  public com.iscas.biz.calculation.grpc.BulbFlat getBulbFlats(int index) {
    return bulbFlats_.get(index);
  }
  /**
   * <pre>
   *球扁钢数组
   * </pre>
   *
   * <code>repeated .com.iscas.biz.calculation.grpc.BulbFlat bulbFlats = 3;</code>
   */
  public com.iscas.biz.calculation.grpc.BulbFlatOrBuilder getBulbFlatsOrBuilder(
      int index) {
    return bulbFlats_.get(index);
  }

  public static final int TPROFILES_FIELD_NUMBER = 4;
  private java.util.List<com.iscas.biz.calculation.grpc.TProfile> tProfiles_;
  /**
   * <pre>
   *T型材数组
   * </pre>
   *
   * <code>repeated .com.iscas.biz.calculation.grpc.TProfile tProfiles = 4;</code>
   */
  public java.util.List<com.iscas.biz.calculation.grpc.TProfile> getTProfilesList() {
    return tProfiles_;
  }
  /**
   * <pre>
   *T型材数组
   * </pre>
   *
   * <code>repeated .com.iscas.biz.calculation.grpc.TProfile tProfiles = 4;</code>
   */
  public java.util.List<? extends com.iscas.biz.calculation.grpc.TProfileOrBuilder> 
      getTProfilesOrBuilderList() {
    return tProfiles_;
  }
  /**
   * <pre>
   *T型材数组
   * </pre>
   *
   * <code>repeated .com.iscas.biz.calculation.grpc.TProfile tProfiles = 4;</code>
   */
  public int getTProfilesCount() {
    return tProfiles_.size();
  }
  /**
   * <pre>
   *T型材数组
   * </pre>
   *
   * <code>repeated .com.iscas.biz.calculation.grpc.TProfile tProfiles = 4;</code>
   */
  public com.iscas.biz.calculation.grpc.TProfile getTProfiles(int index) {
    return tProfiles_.get(index);
  }
  /**
   * <pre>
   *T型材数组
   * </pre>
   *
   * <code>repeated .com.iscas.biz.calculation.grpc.TProfile tProfiles = 4;</code>
   */
  public com.iscas.biz.calculation.grpc.TProfileOrBuilder getTProfilesOrBuilder(
      int index) {
    return tProfiles_.get(index);
  }

  public static final int ISHALFPROFILE_FIELD_NUMBER = 5;
  private boolean isHalfProfile_;
  /**
   * <pre>
   *new614----------------
   *是否半剖面
   * </pre>
   *
   * <code>bool isHalfProfile = 5;</code>
   */
  public boolean getIsHalfProfile() {
    return isHalfProfile_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getProfileFilePathBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, profileFilePath_);
    }
    if (ribNumber_ != 0D) {
      output.writeDouble(2, ribNumber_);
    }
    for (int i = 0; i < bulbFlats_.size(); i++) {
      output.writeMessage(3, bulbFlats_.get(i));
    }
    for (int i = 0; i < tProfiles_.size(); i++) {
      output.writeMessage(4, tProfiles_.get(i));
    }
    if (isHalfProfile_ != false) {
      output.writeBool(5, isHalfProfile_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getProfileFilePathBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, profileFilePath_);
    }
    if (ribNumber_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, ribNumber_);
    }
    for (int i = 0; i < bulbFlats_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, bulbFlats_.get(i));
    }
    for (int i = 0; i < tProfiles_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, tProfiles_.get(i));
    }
    if (isHalfProfile_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(5, isHalfProfile_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.iscas.biz.calculation.grpc.SectionRequest)) {
      return super.equals(obj);
    }
    com.iscas.biz.calculation.grpc.SectionRequest other = (com.iscas.biz.calculation.grpc.SectionRequest) obj;

    boolean result = true;
    result = result && getProfileFilePath()
        .equals(other.getProfileFilePath());
    result = result && (
        java.lang.Double.doubleToLongBits(getRibNumber())
        == java.lang.Double.doubleToLongBits(
            other.getRibNumber()));
    result = result && getBulbFlatsList()
        .equals(other.getBulbFlatsList());
    result = result && getTProfilesList()
        .equals(other.getTProfilesList());
    result = result && (getIsHalfProfile()
        == other.getIsHalfProfile());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PROFILEFILEPATH_FIELD_NUMBER;
    hash = (53 * hash) + getProfileFilePath().hashCode();
    hash = (37 * hash) + RIBNUMBER_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getRibNumber()));
    if (getBulbFlatsCount() > 0) {
      hash = (37 * hash) + BULBFLATS_FIELD_NUMBER;
      hash = (53 * hash) + getBulbFlatsList().hashCode();
    }
    if (getTProfilesCount() > 0) {
      hash = (37 * hash) + TPROFILES_FIELD_NUMBER;
      hash = (53 * hash) + getTProfilesList().hashCode();
    }
    hash = (37 * hash) + ISHALFPROFILE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsHalfProfile());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.iscas.biz.calculation.grpc.SectionRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.iscas.biz.calculation.grpc.SectionRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.iscas.biz.calculation.grpc.SectionRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.iscas.biz.calculation.grpc.SectionRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.iscas.biz.calculation.grpc.SectionRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.iscas.biz.calculation.grpc.SectionRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.iscas.biz.calculation.grpc.SectionRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.iscas.biz.calculation.grpc.SectionRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.iscas.biz.calculation.grpc.SectionRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.iscas.biz.calculation.grpc.SectionRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.iscas.biz.calculation.grpc.SectionRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *剖面计算输入
   * </pre>
   *
   * Protobuf type {@code com.iscas.biz.calculation.grpc.SectionRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.iscas.biz.calculation.grpc.SectionRequest)
      com.iscas.biz.calculation.grpc.SectionRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.iscas.biz.calculation.grpc.CalculationProto.internal_static_com_iscas_biz_calculation_grpc_SectionRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.iscas.biz.calculation.grpc.CalculationProto.internal_static_com_iscas_biz_calculation_grpc_SectionRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.iscas.biz.calculation.grpc.SectionRequest.class, com.iscas.biz.calculation.grpc.SectionRequest.Builder.class);
    }

    // Construct using com.iscas.biz.calculation.grpc.SectionRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getBulbFlatsFieldBuilder();
        getTProfilesFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      profileFilePath_ = "";

      ribNumber_ = 0D;

      if (bulbFlatsBuilder_ == null) {
        bulbFlats_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
      } else {
        bulbFlatsBuilder_.clear();
      }
      if (tProfilesBuilder_ == null) {
        tProfiles_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
      } else {
        tProfilesBuilder_.clear();
      }
      isHalfProfile_ = false;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.iscas.biz.calculation.grpc.CalculationProto.internal_static_com_iscas_biz_calculation_grpc_SectionRequest_descriptor;
    }

    public com.iscas.biz.calculation.grpc.SectionRequest getDefaultInstanceForType() {
      return com.iscas.biz.calculation.grpc.SectionRequest.getDefaultInstance();
    }

    public com.iscas.biz.calculation.grpc.SectionRequest build() {
      com.iscas.biz.calculation.grpc.SectionRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.iscas.biz.calculation.grpc.SectionRequest buildPartial() {
      com.iscas.biz.calculation.grpc.SectionRequest result = new com.iscas.biz.calculation.grpc.SectionRequest(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.profileFilePath_ = profileFilePath_;
      result.ribNumber_ = ribNumber_;
      if (bulbFlatsBuilder_ == null) {
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          bulbFlats_ = java.util.Collections.unmodifiableList(bulbFlats_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.bulbFlats_ = bulbFlats_;
      } else {
        result.bulbFlats_ = bulbFlatsBuilder_.build();
      }
      if (tProfilesBuilder_ == null) {
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          tProfiles_ = java.util.Collections.unmodifiableList(tProfiles_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.tProfiles_ = tProfiles_;
      } else {
        result.tProfiles_ = tProfilesBuilder_.build();
      }
      result.isHalfProfile_ = isHalfProfile_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.iscas.biz.calculation.grpc.SectionRequest) {
        return mergeFrom((com.iscas.biz.calculation.grpc.SectionRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.iscas.biz.calculation.grpc.SectionRequest other) {
      if (other == com.iscas.biz.calculation.grpc.SectionRequest.getDefaultInstance()) return this;
      if (!other.getProfileFilePath().isEmpty()) {
        profileFilePath_ = other.profileFilePath_;
        onChanged();
      }
      if (other.getRibNumber() != 0D) {
        setRibNumber(other.getRibNumber());
      }
      if (bulbFlatsBuilder_ == null) {
        if (!other.bulbFlats_.isEmpty()) {
          if (bulbFlats_.isEmpty()) {
            bulbFlats_ = other.bulbFlats_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureBulbFlatsIsMutable();
            bulbFlats_.addAll(other.bulbFlats_);
          }
          onChanged();
        }
      } else {
        if (!other.bulbFlats_.isEmpty()) {
          if (bulbFlatsBuilder_.isEmpty()) {
            bulbFlatsBuilder_.dispose();
            bulbFlatsBuilder_ = null;
            bulbFlats_ = other.bulbFlats_;
            bitField0_ = (bitField0_ & ~0x00000004);
            bulbFlatsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getBulbFlatsFieldBuilder() : null;
          } else {
            bulbFlatsBuilder_.addAllMessages(other.bulbFlats_);
          }
        }
      }
      if (tProfilesBuilder_ == null) {
        if (!other.tProfiles_.isEmpty()) {
          if (tProfiles_.isEmpty()) {
            tProfiles_ = other.tProfiles_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureTProfilesIsMutable();
            tProfiles_.addAll(other.tProfiles_);
          }
          onChanged();
        }
      } else {
        if (!other.tProfiles_.isEmpty()) {
          if (tProfilesBuilder_.isEmpty()) {
            tProfilesBuilder_.dispose();
            tProfilesBuilder_ = null;
            tProfiles_ = other.tProfiles_;
            bitField0_ = (bitField0_ & ~0x00000008);
            tProfilesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getTProfilesFieldBuilder() : null;
          } else {
            tProfilesBuilder_.addAllMessages(other.tProfiles_);
          }
        }
      }
      if (other.getIsHalfProfile() != false) {
        setIsHalfProfile(other.getIsHalfProfile());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.iscas.biz.calculation.grpc.SectionRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.iscas.biz.calculation.grpc.SectionRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object profileFilePath_ = "";
    /**
     * <pre>
     *剖面文件路径
     * </pre>
     *
     * <code>string profileFilePath = 1;</code>
     */
    public java.lang.String getProfileFilePath() {
      java.lang.Object ref = profileFilePath_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        profileFilePath_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *剖面文件路径
     * </pre>
     *
     * <code>string profileFilePath = 1;</code>
     */
    public com.google.protobuf.ByteString
        getProfileFilePathBytes() {
      java.lang.Object ref = profileFilePath_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        profileFilePath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *剖面文件路径
     * </pre>
     *
     * <code>string profileFilePath = 1;</code>
     */
    public Builder setProfileFilePath(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      profileFilePath_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *剖面文件路径
     * </pre>
     *
     * <code>string profileFilePath = 1;</code>
     */
    public Builder clearProfileFilePath() {
      
      profileFilePath_ = getDefaultInstance().getProfileFilePath();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *剖面文件路径
     * </pre>
     *
     * <code>string profileFilePath = 1;</code>
     */
    public Builder setProfileFilePathBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      profileFilePath_ = value;
      onChanged();
      return this;
    }

    private double ribNumber_ ;
    /**
     * <pre>
     *肋位号
     * </pre>
     *
     * <code>double ribNumber = 2;</code>
     */
    public double getRibNumber() {
      return ribNumber_;
    }
    /**
     * <pre>
     *肋位号
     * </pre>
     *
     * <code>double ribNumber = 2;</code>
     */
    public Builder setRibNumber(double value) {
      
      ribNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *肋位号
     * </pre>
     *
     * <code>double ribNumber = 2;</code>
     */
    public Builder clearRibNumber() {
      
      ribNumber_ = 0D;
      onChanged();
      return this;
    }

    private java.util.List<com.iscas.biz.calculation.grpc.BulbFlat> bulbFlats_ =
      java.util.Collections.emptyList();
    private void ensureBulbFlatsIsMutable() {
      if (!((bitField0_ & 0x00000004) == 0x00000004)) {
        bulbFlats_ = new java.util.ArrayList<com.iscas.biz.calculation.grpc.BulbFlat>(bulbFlats_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.iscas.biz.calculation.grpc.BulbFlat, com.iscas.biz.calculation.grpc.BulbFlat.Builder, com.iscas.biz.calculation.grpc.BulbFlatOrBuilder> bulbFlatsBuilder_;

    /**
     * <pre>
     *球扁钢数组
     * </pre>
     *
     * <code>repeated .com.iscas.biz.calculation.grpc.BulbFlat bulbFlats = 3;</code>
     */
    public java.util.List<com.iscas.biz.calculation.grpc.BulbFlat> getBulbFlatsList() {
      if (bulbFlatsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(bulbFlats_);
      } else {
        return bulbFlatsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     *球扁钢数组
     * </pre>
     *
     * <code>repeated .com.iscas.biz.calculation.grpc.BulbFlat bulbFlats = 3;</code>
     */
    public int getBulbFlatsCount() {
      if (bulbFlatsBuilder_ == null) {
        return bulbFlats_.size();
      } else {
        return bulbFlatsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     *球扁钢数组
     * </pre>
     *
     * <code>repeated .com.iscas.biz.calculation.grpc.BulbFlat bulbFlats = 3;</code>
     */
    public com.iscas.biz.calculation.grpc.BulbFlat getBulbFlats(int index) {
      if (bulbFlatsBuilder_ == null) {
        return bulbFlats_.get(index);
      } else {
        return bulbFlatsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     *球扁钢数组
     * </pre>
     *
     * <code>repeated .com.iscas.biz.calculation.grpc.BulbFlat bulbFlats = 3;</code>
     */
    public Builder setBulbFlats(
        int index, com.iscas.biz.calculation.grpc.BulbFlat value) {
      if (bulbFlatsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBulbFlatsIsMutable();
        bulbFlats_.set(index, value);
        onChanged();
      } else {
        bulbFlatsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     *球扁钢数组
     * </pre>
     *
     * <code>repeated .com.iscas.biz.calculation.grpc.BulbFlat bulbFlats = 3;</code>
     */
    public Builder setBulbFlats(
        int index, com.iscas.biz.calculation.grpc.BulbFlat.Builder builderForValue) {
      if (bulbFlatsBuilder_ == null) {
        ensureBulbFlatsIsMutable();
        bulbFlats_.set(index, builderForValue.build());
        onChanged();
      } else {
        bulbFlatsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *球扁钢数组
     * </pre>
     *
     * <code>repeated .com.iscas.biz.calculation.grpc.BulbFlat bulbFlats = 3;</code>
     */
    public Builder addBulbFlats(com.iscas.biz.calculation.grpc.BulbFlat value) {
      if (bulbFlatsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBulbFlatsIsMutable();
        bulbFlats_.add(value);
        onChanged();
      } else {
        bulbFlatsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     *球扁钢数组
     * </pre>
     *
     * <code>repeated .com.iscas.biz.calculation.grpc.BulbFlat bulbFlats = 3;</code>
     */
    public Builder addBulbFlats(
        int index, com.iscas.biz.calculation.grpc.BulbFlat value) {
      if (bulbFlatsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBulbFlatsIsMutable();
        bulbFlats_.add(index, value);
        onChanged();
      } else {
        bulbFlatsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     *球扁钢数组
     * </pre>
     *
     * <code>repeated .com.iscas.biz.calculation.grpc.BulbFlat bulbFlats = 3;</code>
     */
    public Builder addBulbFlats(
        com.iscas.biz.calculation.grpc.BulbFlat.Builder builderForValue) {
      if (bulbFlatsBuilder_ == null) {
        ensureBulbFlatsIsMutable();
        bulbFlats_.add(builderForValue.build());
        onChanged();
      } else {
        bulbFlatsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *球扁钢数组
     * </pre>
     *
     * <code>repeated .com.iscas.biz.calculation.grpc.BulbFlat bulbFlats = 3;</code>
     */
    public Builder addBulbFlats(
        int index, com.iscas.biz.calculation.grpc.BulbFlat.Builder builderForValue) {
      if (bulbFlatsBuilder_ == null) {
        ensureBulbFlatsIsMutable();
        bulbFlats_.add(index, builderForValue.build());
        onChanged();
      } else {
        bulbFlatsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *球扁钢数组
     * </pre>
     *
     * <code>repeated .com.iscas.biz.calculation.grpc.BulbFlat bulbFlats = 3;</code>
     */
    public Builder addAllBulbFlats(
        java.lang.Iterable<? extends com.iscas.biz.calculation.grpc.BulbFlat> values) {
      if (bulbFlatsBuilder_ == null) {
        ensureBulbFlatsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, bulbFlats_);
        onChanged();
      } else {
        bulbFlatsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     *球扁钢数组
     * </pre>
     *
     * <code>repeated .com.iscas.biz.calculation.grpc.BulbFlat bulbFlats = 3;</code>
     */
    public Builder clearBulbFlats() {
      if (bulbFlatsBuilder_ == null) {
        bulbFlats_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        bulbFlatsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     *球扁钢数组
     * </pre>
     *
     * <code>repeated .com.iscas.biz.calculation.grpc.BulbFlat bulbFlats = 3;</code>
     */
    public Builder removeBulbFlats(int index) {
      if (bulbFlatsBuilder_ == null) {
        ensureBulbFlatsIsMutable();
        bulbFlats_.remove(index);
        onChanged();
      } else {
        bulbFlatsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     *球扁钢数组
     * </pre>
     *
     * <code>repeated .com.iscas.biz.calculation.grpc.BulbFlat bulbFlats = 3;</code>
     */
    public com.iscas.biz.calculation.grpc.BulbFlat.Builder getBulbFlatsBuilder(
        int index) {
      return getBulbFlatsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     *球扁钢数组
     * </pre>
     *
     * <code>repeated .com.iscas.biz.calculation.grpc.BulbFlat bulbFlats = 3;</code>
     */
    public com.iscas.biz.calculation.grpc.BulbFlatOrBuilder getBulbFlatsOrBuilder(
        int index) {
      if (bulbFlatsBuilder_ == null) {
        return bulbFlats_.get(index);  } else {
        return bulbFlatsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     *球扁钢数组
     * </pre>
     *
     * <code>repeated .com.iscas.biz.calculation.grpc.BulbFlat bulbFlats = 3;</code>
     */
    public java.util.List<? extends com.iscas.biz.calculation.grpc.BulbFlatOrBuilder> 
         getBulbFlatsOrBuilderList() {
      if (bulbFlatsBuilder_ != null) {
        return bulbFlatsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(bulbFlats_);
      }
    }
    /**
     * <pre>
     *球扁钢数组
     * </pre>
     *
     * <code>repeated .com.iscas.biz.calculation.grpc.BulbFlat bulbFlats = 3;</code>
     */
    public com.iscas.biz.calculation.grpc.BulbFlat.Builder addBulbFlatsBuilder() {
      return getBulbFlatsFieldBuilder().addBuilder(
          com.iscas.biz.calculation.grpc.BulbFlat.getDefaultInstance());
    }
    /**
     * <pre>
     *球扁钢数组
     * </pre>
     *
     * <code>repeated .com.iscas.biz.calculation.grpc.BulbFlat bulbFlats = 3;</code>
     */
    public com.iscas.biz.calculation.grpc.BulbFlat.Builder addBulbFlatsBuilder(
        int index) {
      return getBulbFlatsFieldBuilder().addBuilder(
          index, com.iscas.biz.calculation.grpc.BulbFlat.getDefaultInstance());
    }
    /**
     * <pre>
     *球扁钢数组
     * </pre>
     *
     * <code>repeated .com.iscas.biz.calculation.grpc.BulbFlat bulbFlats = 3;</code>
     */
    public java.util.List<com.iscas.biz.calculation.grpc.BulbFlat.Builder> 
         getBulbFlatsBuilderList() {
      return getBulbFlatsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.iscas.biz.calculation.grpc.BulbFlat, com.iscas.biz.calculation.grpc.BulbFlat.Builder, com.iscas.biz.calculation.grpc.BulbFlatOrBuilder> 
        getBulbFlatsFieldBuilder() {
      if (bulbFlatsBuilder_ == null) {
        bulbFlatsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.iscas.biz.calculation.grpc.BulbFlat, com.iscas.biz.calculation.grpc.BulbFlat.Builder, com.iscas.biz.calculation.grpc.BulbFlatOrBuilder>(
                bulbFlats_,
                ((bitField0_ & 0x00000004) == 0x00000004),
                getParentForChildren(),
                isClean());
        bulbFlats_ = null;
      }
      return bulbFlatsBuilder_;
    }

    private java.util.List<com.iscas.biz.calculation.grpc.TProfile> tProfiles_ =
      java.util.Collections.emptyList();
    private void ensureTProfilesIsMutable() {
      if (!((bitField0_ & 0x00000008) == 0x00000008)) {
        tProfiles_ = new java.util.ArrayList<com.iscas.biz.calculation.grpc.TProfile>(tProfiles_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.iscas.biz.calculation.grpc.TProfile, com.iscas.biz.calculation.grpc.TProfile.Builder, com.iscas.biz.calculation.grpc.TProfileOrBuilder> tProfilesBuilder_;

    /**
     * <pre>
     *T型材数组
     * </pre>
     *
     * <code>repeated .com.iscas.biz.calculation.grpc.TProfile tProfiles = 4;</code>
     */
    public java.util.List<com.iscas.biz.calculation.grpc.TProfile> getTProfilesList() {
      if (tProfilesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(tProfiles_);
      } else {
        return tProfilesBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     *T型材数组
     * </pre>
     *
     * <code>repeated .com.iscas.biz.calculation.grpc.TProfile tProfiles = 4;</code>
     */
    public int getTProfilesCount() {
      if (tProfilesBuilder_ == null) {
        return tProfiles_.size();
      } else {
        return tProfilesBuilder_.getCount();
      }
    }
    /**
     * <pre>
     *T型材数组
     * </pre>
     *
     * <code>repeated .com.iscas.biz.calculation.grpc.TProfile tProfiles = 4;</code>
     */
    public com.iscas.biz.calculation.grpc.TProfile getTProfiles(int index) {
      if (tProfilesBuilder_ == null) {
        return tProfiles_.get(index);
      } else {
        return tProfilesBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     *T型材数组
     * </pre>
     *
     * <code>repeated .com.iscas.biz.calculation.grpc.TProfile tProfiles = 4;</code>
     */
    public Builder setTProfiles(
        int index, com.iscas.biz.calculation.grpc.TProfile value) {
      if (tProfilesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTProfilesIsMutable();
        tProfiles_.set(index, value);
        onChanged();
      } else {
        tProfilesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     *T型材数组
     * </pre>
     *
     * <code>repeated .com.iscas.biz.calculation.grpc.TProfile tProfiles = 4;</code>
     */
    public Builder setTProfiles(
        int index, com.iscas.biz.calculation.grpc.TProfile.Builder builderForValue) {
      if (tProfilesBuilder_ == null) {
        ensureTProfilesIsMutable();
        tProfiles_.set(index, builderForValue.build());
        onChanged();
      } else {
        tProfilesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *T型材数组
     * </pre>
     *
     * <code>repeated .com.iscas.biz.calculation.grpc.TProfile tProfiles = 4;</code>
     */
    public Builder addTProfiles(com.iscas.biz.calculation.grpc.TProfile value) {
      if (tProfilesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTProfilesIsMutable();
        tProfiles_.add(value);
        onChanged();
      } else {
        tProfilesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     *T型材数组
     * </pre>
     *
     * <code>repeated .com.iscas.biz.calculation.grpc.TProfile tProfiles = 4;</code>
     */
    public Builder addTProfiles(
        int index, com.iscas.biz.calculation.grpc.TProfile value) {
      if (tProfilesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTProfilesIsMutable();
        tProfiles_.add(index, value);
        onChanged();
      } else {
        tProfilesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     *T型材数组
     * </pre>
     *
     * <code>repeated .com.iscas.biz.calculation.grpc.TProfile tProfiles = 4;</code>
     */
    public Builder addTProfiles(
        com.iscas.biz.calculation.grpc.TProfile.Builder builderForValue) {
      if (tProfilesBuilder_ == null) {
        ensureTProfilesIsMutable();
        tProfiles_.add(builderForValue.build());
        onChanged();
      } else {
        tProfilesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *T型材数组
     * </pre>
     *
     * <code>repeated .com.iscas.biz.calculation.grpc.TProfile tProfiles = 4;</code>
     */
    public Builder addTProfiles(
        int index, com.iscas.biz.calculation.grpc.TProfile.Builder builderForValue) {
      if (tProfilesBuilder_ == null) {
        ensureTProfilesIsMutable();
        tProfiles_.add(index, builderForValue.build());
        onChanged();
      } else {
        tProfilesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *T型材数组
     * </pre>
     *
     * <code>repeated .com.iscas.biz.calculation.grpc.TProfile tProfiles = 4;</code>
     */
    public Builder addAllTProfiles(
        java.lang.Iterable<? extends com.iscas.biz.calculation.grpc.TProfile> values) {
      if (tProfilesBuilder_ == null) {
        ensureTProfilesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, tProfiles_);
        onChanged();
      } else {
        tProfilesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     *T型材数组
     * </pre>
     *
     * <code>repeated .com.iscas.biz.calculation.grpc.TProfile tProfiles = 4;</code>
     */
    public Builder clearTProfiles() {
      if (tProfilesBuilder_ == null) {
        tProfiles_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        tProfilesBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     *T型材数组
     * </pre>
     *
     * <code>repeated .com.iscas.biz.calculation.grpc.TProfile tProfiles = 4;</code>
     */
    public Builder removeTProfiles(int index) {
      if (tProfilesBuilder_ == null) {
        ensureTProfilesIsMutable();
        tProfiles_.remove(index);
        onChanged();
      } else {
        tProfilesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     *T型材数组
     * </pre>
     *
     * <code>repeated .com.iscas.biz.calculation.grpc.TProfile tProfiles = 4;</code>
     */
    public com.iscas.biz.calculation.grpc.TProfile.Builder getTProfilesBuilder(
        int index) {
      return getTProfilesFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     *T型材数组
     * </pre>
     *
     * <code>repeated .com.iscas.biz.calculation.grpc.TProfile tProfiles = 4;</code>
     */
    public com.iscas.biz.calculation.grpc.TProfileOrBuilder getTProfilesOrBuilder(
        int index) {
      if (tProfilesBuilder_ == null) {
        return tProfiles_.get(index);  } else {
        return tProfilesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     *T型材数组
     * </pre>
     *
     * <code>repeated .com.iscas.biz.calculation.grpc.TProfile tProfiles = 4;</code>
     */
    public java.util.List<? extends com.iscas.biz.calculation.grpc.TProfileOrBuilder> 
         getTProfilesOrBuilderList() {
      if (tProfilesBuilder_ != null) {
        return tProfilesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(tProfiles_);
      }
    }
    /**
     * <pre>
     *T型材数组
     * </pre>
     *
     * <code>repeated .com.iscas.biz.calculation.grpc.TProfile tProfiles = 4;</code>
     */
    public com.iscas.biz.calculation.grpc.TProfile.Builder addTProfilesBuilder() {
      return getTProfilesFieldBuilder().addBuilder(
          com.iscas.biz.calculation.grpc.TProfile.getDefaultInstance());
    }
    /**
     * <pre>
     *T型材数组
     * </pre>
     *
     * <code>repeated .com.iscas.biz.calculation.grpc.TProfile tProfiles = 4;</code>
     */
    public com.iscas.biz.calculation.grpc.TProfile.Builder addTProfilesBuilder(
        int index) {
      return getTProfilesFieldBuilder().addBuilder(
          index, com.iscas.biz.calculation.grpc.TProfile.getDefaultInstance());
    }
    /**
     * <pre>
     *T型材数组
     * </pre>
     *
     * <code>repeated .com.iscas.biz.calculation.grpc.TProfile tProfiles = 4;</code>
     */
    public java.util.List<com.iscas.biz.calculation.grpc.TProfile.Builder> 
         getTProfilesBuilderList() {
      return getTProfilesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.iscas.biz.calculation.grpc.TProfile, com.iscas.biz.calculation.grpc.TProfile.Builder, com.iscas.biz.calculation.grpc.TProfileOrBuilder> 
        getTProfilesFieldBuilder() {
      if (tProfilesBuilder_ == null) {
        tProfilesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.iscas.biz.calculation.grpc.TProfile, com.iscas.biz.calculation.grpc.TProfile.Builder, com.iscas.biz.calculation.grpc.TProfileOrBuilder>(
                tProfiles_,
                ((bitField0_ & 0x00000008) == 0x00000008),
                getParentForChildren(),
                isClean());
        tProfiles_ = null;
      }
      return tProfilesBuilder_;
    }

    private boolean isHalfProfile_ ;
    /**
     * <pre>
     *new614----------------
     *是否半剖面
     * </pre>
     *
     * <code>bool isHalfProfile = 5;</code>
     */
    public boolean getIsHalfProfile() {
      return isHalfProfile_;
    }
    /**
     * <pre>
     *new614----------------
     *是否半剖面
     * </pre>
     *
     * <code>bool isHalfProfile = 5;</code>
     */
    public Builder setIsHalfProfile(boolean value) {
      
      isHalfProfile_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *new614----------------
     *是否半剖面
     * </pre>
     *
     * <code>bool isHalfProfile = 5;</code>
     */
    public Builder clearIsHalfProfile() {
      
      isHalfProfile_ = false;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:com.iscas.biz.calculation.grpc.SectionRequest)
  }

  // @@protoc_insertion_point(class_scope:com.iscas.biz.calculation.grpc.SectionRequest)
  private static final com.iscas.biz.calculation.grpc.SectionRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.iscas.biz.calculation.grpc.SectionRequest();
  }

  public static com.iscas.biz.calculation.grpc.SectionRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SectionRequest>
      PARSER = new com.google.protobuf.AbstractParser<SectionRequest>() {
    public SectionRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new SectionRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SectionRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SectionRequest> getParserForType() {
    return PARSER;
  }

  public com.iscas.biz.calculation.grpc.SectionRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

