// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: calculation.proto

package com.iscas.biz.calculation.grpc;

public interface Sigma3ResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.iscas.biz.calculation.grpc.Sigma3Response)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.iscas.biz.calculation.grpc.Sigma2Entity sigma3 = 1;</code>
   */
  java.util.List<com.iscas.biz.calculation.grpc.Sigma2Entity> 
      getSigma3List();
  /**
   * <code>repeated .com.iscas.biz.calculation.grpc.Sigma2Entity sigma3 = 1;</code>
   */
  com.iscas.biz.calculation.grpc.Sigma2Entity getSigma3(int index);
  /**
   * <code>repeated .com.iscas.biz.calculation.grpc.Sigma2Entity sigma3 = 1;</code>
   */
  int getSigma3Count();
  /**
   * <code>repeated .com.iscas.biz.calculation.grpc.Sigma2Entity sigma3 = 1;</code>
   */
  java.util.List<? extends com.iscas.biz.calculation.grpc.Sigma2EntityOrBuilder> 
      getSigma3OrBuilderList();
  /**
   * <code>repeated .com.iscas.biz.calculation.grpc.Sigma2Entity sigma3 = 1;</code>
   */
  com.iscas.biz.calculation.grpc.Sigma2EntityOrBuilder getSigma3OrBuilder(
      int index);

  /**
   * <pre>
   *0-正常 1-异常
   * </pre>
   *
   * <code>int32 code = 2;</code>
   */
  int getCode();
}
