// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: calculation.proto

package com.iscas.biz.calculation.grpc;

/**
 * Protobuf type {@code com.iscas.biz.calculation.grpc.Sigma4Entity}
 */
public  final class Sigma4Entity extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.iscas.biz.calculation.grpc.Sigma4Entity)
    Sigma4EntityOrBuilder {
  // Use Sigma4Entity.newBuilder() to construct.
  private Sigma4Entity(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Sigma4Entity() {
    zhonggongZhizuo_ = 0D;
    zhonggongKuazhong_ = 0D;
    zhongchuiZhizuo_ = 0D;
    zhongchuiKuazhong_ = 0D;
    allowStress_ = 0D;
    combineAllowStress_ = 0D;
    combineZhonggongZhizuoShang_ = 0D;
    combineZhonggongZhizuoXia_ = 0D;
    combineZhonggongKuazhongShang_ = 0D;
    combineZhonggongKuazhongXia_ = 0D;
    combineZhongchuiZhizuoShang_ = 0D;
    combineZhongchuiZhizuoXia_ = 0D;
    combineZhongchuiKuazhongShang_ = 0D;
    combineZhongchuiKuazhongXia_ = 0D;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private Sigma4Entity(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 9: {

            zhonggongZhizuo_ = input.readDouble();
            break;
          }
          case 17: {

            zhonggongKuazhong_ = input.readDouble();
            break;
          }
          case 25: {

            zhongchuiZhizuo_ = input.readDouble();
            break;
          }
          case 33: {

            zhongchuiKuazhong_ = input.readDouble();
            break;
          }
          case 41: {

            allowStress_ = input.readDouble();
            break;
          }
          case 49: {

            combineAllowStress_ = input.readDouble();
            break;
          }
          case 57: {

            combineZhonggongZhizuoShang_ = input.readDouble();
            break;
          }
          case 65: {

            combineZhonggongZhizuoXia_ = input.readDouble();
            break;
          }
          case 73: {

            combineZhonggongKuazhongShang_ = input.readDouble();
            break;
          }
          case 81: {

            combineZhonggongKuazhongXia_ = input.readDouble();
            break;
          }
          case 89: {

            combineZhongchuiZhizuoShang_ = input.readDouble();
            break;
          }
          case 97: {

            combineZhongchuiZhizuoXia_ = input.readDouble();
            break;
          }
          case 105: {

            combineZhongchuiKuazhongShang_ = input.readDouble();
            break;
          }
          case 113: {

            combineZhongchuiKuazhongXia_ = input.readDouble();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.iscas.biz.calculation.grpc.CalculationProto.internal_static_com_iscas_biz_calculation_grpc_Sigma4Entity_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.iscas.biz.calculation.grpc.CalculationProto.internal_static_com_iscas_biz_calculation_grpc_Sigma4Entity_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.iscas.biz.calculation.grpc.Sigma4Entity.class, com.iscas.biz.calculation.grpc.Sigma4Entity.Builder.class);
  }

  public static final int ZHONGGONGZHIZUO_FIELD_NUMBER = 1;
  private double zhonggongZhizuo_;
  /**
   * <pre>
   *中拱支座
   * </pre>
   *
   * <code>double zhonggongZhizuo = 1;</code>
   */
  public double getZhonggongZhizuo() {
    return zhonggongZhizuo_;
  }

  public static final int ZHONGGONGKUAZHONG_FIELD_NUMBER = 2;
  private double zhonggongKuazhong_;
  /**
   * <pre>
   *中拱跨中
   * </pre>
   *
   * <code>double zhonggongKuazhong = 2;</code>
   */
  public double getZhonggongKuazhong() {
    return zhonggongKuazhong_;
  }

  public static final int ZHONGCHUIZHIZUO_FIELD_NUMBER = 3;
  private double zhongchuiZhizuo_;
  /**
   * <pre>
   *中垂支座
   * </pre>
   *
   * <code>double zhongchuiZhizuo = 3;</code>
   */
  public double getZhongchuiZhizuo() {
    return zhongchuiZhizuo_;
  }

  public static final int ZHONGCHUIKUAZHONG_FIELD_NUMBER = 4;
  private double zhongchuiKuazhong_;
  /**
   * <pre>
   *中垂跨中
   * </pre>
   *
   * <code>double zhongchuiKuazhong = 4;</code>
   */
  public double getZhongchuiKuazhong() {
    return zhongchuiKuazhong_;
  }

  public static final int ALLOWSTRESS_FIELD_NUMBER = 5;
  private double allowStress_;
  /**
   * <pre>
   *许用应力
   * </pre>
   *
   * <code>double allowStress = 5;</code>
   */
  public double getAllowStress() {
    return allowStress_;
  }

  public static final int COMBINEALLOWSTRESS_FIELD_NUMBER = 6;
  private double combineAllowStress_;
  /**
   * <pre>
   *合成许用应力
   * </pre>
   *
   * <code>double combineAllowStress = 6;</code>
   */
  public double getCombineAllowStress() {
    return combineAllowStress_;
  }

  public static final int COMBINEZHONGGONGZHIZUOSHANG_FIELD_NUMBER = 7;
  private double combineZhonggongZhizuoShang_;
  /**
   * <pre>
   *合成中拱支座上纤维
   * </pre>
   *
   * <code>double combineZhonggongZhizuoShang = 7;</code>
   */
  public double getCombineZhonggongZhizuoShang() {
    return combineZhonggongZhizuoShang_;
  }

  public static final int COMBINEZHONGGONGZHIZUOXIA_FIELD_NUMBER = 8;
  private double combineZhonggongZhizuoXia_;
  /**
   * <pre>
   *合成中拱支座下纤维
   * </pre>
   *
   * <code>double combineZhonggongZhizuoXia = 8;</code>
   */
  public double getCombineZhonggongZhizuoXia() {
    return combineZhonggongZhizuoXia_;
  }

  public static final int COMBINEZHONGGONGKUAZHONGSHANG_FIELD_NUMBER = 9;
  private double combineZhonggongKuazhongShang_;
  /**
   * <pre>
   *合成中拱跨中上纤维
   * </pre>
   *
   * <code>double combineZhonggongKuazhongShang = 9;</code>
   */
  public double getCombineZhonggongKuazhongShang() {
    return combineZhonggongKuazhongShang_;
  }

  public static final int COMBINEZHONGGONGKUAZHONGXIA_FIELD_NUMBER = 10;
  private double combineZhonggongKuazhongXia_;
  /**
   * <pre>
   *合成中拱跨中下纤维
   * </pre>
   *
   * <code>double combineZhonggongKuazhongXia = 10;</code>
   */
  public double getCombineZhonggongKuazhongXia() {
    return combineZhonggongKuazhongXia_;
  }

  public static final int COMBINEZHONGCHUIZHIZUOSHANG_FIELD_NUMBER = 11;
  private double combineZhongchuiZhizuoShang_;
  /**
   * <pre>
   *合成中垂支座上纤维
   * </pre>
   *
   * <code>double combineZhongchuiZhizuoShang = 11;</code>
   */
  public double getCombineZhongchuiZhizuoShang() {
    return combineZhongchuiZhizuoShang_;
  }

  public static final int COMBINEZHONGCHUIZHIZUOXIA_FIELD_NUMBER = 12;
  private double combineZhongchuiZhizuoXia_;
  /**
   * <pre>
   *合成中垂支座下纤维
   * </pre>
   *
   * <code>double combineZhongchuiZhizuoXia = 12;</code>
   */
  public double getCombineZhongchuiZhizuoXia() {
    return combineZhongchuiZhizuoXia_;
  }

  public static final int COMBINEZHONGCHUIKUAZHONGSHANG_FIELD_NUMBER = 13;
  private double combineZhongchuiKuazhongShang_;
  /**
   * <pre>
   *合成中垂跨中上纤维
   * </pre>
   *
   * <code>double combineZhongchuiKuazhongShang = 13;</code>
   */
  public double getCombineZhongchuiKuazhongShang() {
    return combineZhongchuiKuazhongShang_;
  }

  public static final int COMBINEZHONGCHUIKUAZHONGXIA_FIELD_NUMBER = 14;
  private double combineZhongchuiKuazhongXia_;
  /**
   * <pre>
   *合成中垂跨中下纤维
   * </pre>
   *
   * <code>double combineZhongchuiKuazhongXia = 14;</code>
   */
  public double getCombineZhongchuiKuazhongXia() {
    return combineZhongchuiKuazhongXia_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (zhonggongZhizuo_ != 0D) {
      output.writeDouble(1, zhonggongZhizuo_);
    }
    if (zhonggongKuazhong_ != 0D) {
      output.writeDouble(2, zhonggongKuazhong_);
    }
    if (zhongchuiZhizuo_ != 0D) {
      output.writeDouble(3, zhongchuiZhizuo_);
    }
    if (zhongchuiKuazhong_ != 0D) {
      output.writeDouble(4, zhongchuiKuazhong_);
    }
    if (allowStress_ != 0D) {
      output.writeDouble(5, allowStress_);
    }
    if (combineAllowStress_ != 0D) {
      output.writeDouble(6, combineAllowStress_);
    }
    if (combineZhonggongZhizuoShang_ != 0D) {
      output.writeDouble(7, combineZhonggongZhizuoShang_);
    }
    if (combineZhonggongZhizuoXia_ != 0D) {
      output.writeDouble(8, combineZhonggongZhizuoXia_);
    }
    if (combineZhonggongKuazhongShang_ != 0D) {
      output.writeDouble(9, combineZhonggongKuazhongShang_);
    }
    if (combineZhonggongKuazhongXia_ != 0D) {
      output.writeDouble(10, combineZhonggongKuazhongXia_);
    }
    if (combineZhongchuiZhizuoShang_ != 0D) {
      output.writeDouble(11, combineZhongchuiZhizuoShang_);
    }
    if (combineZhongchuiZhizuoXia_ != 0D) {
      output.writeDouble(12, combineZhongchuiZhizuoXia_);
    }
    if (combineZhongchuiKuazhongShang_ != 0D) {
      output.writeDouble(13, combineZhongchuiKuazhongShang_);
    }
    if (combineZhongchuiKuazhongXia_ != 0D) {
      output.writeDouble(14, combineZhongchuiKuazhongXia_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (zhonggongZhizuo_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(1, zhonggongZhizuo_);
    }
    if (zhonggongKuazhong_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, zhonggongKuazhong_);
    }
    if (zhongchuiZhizuo_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(3, zhongchuiZhizuo_);
    }
    if (zhongchuiKuazhong_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(4, zhongchuiKuazhong_);
    }
    if (allowStress_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(5, allowStress_);
    }
    if (combineAllowStress_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(6, combineAllowStress_);
    }
    if (combineZhonggongZhizuoShang_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(7, combineZhonggongZhizuoShang_);
    }
    if (combineZhonggongZhizuoXia_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(8, combineZhonggongZhizuoXia_);
    }
    if (combineZhonggongKuazhongShang_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(9, combineZhonggongKuazhongShang_);
    }
    if (combineZhonggongKuazhongXia_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(10, combineZhonggongKuazhongXia_);
    }
    if (combineZhongchuiZhizuoShang_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(11, combineZhongchuiZhizuoShang_);
    }
    if (combineZhongchuiZhizuoXia_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(12, combineZhongchuiZhizuoXia_);
    }
    if (combineZhongchuiKuazhongShang_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(13, combineZhongchuiKuazhongShang_);
    }
    if (combineZhongchuiKuazhongXia_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(14, combineZhongchuiKuazhongXia_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.iscas.biz.calculation.grpc.Sigma4Entity)) {
      return super.equals(obj);
    }
    com.iscas.biz.calculation.grpc.Sigma4Entity other = (com.iscas.biz.calculation.grpc.Sigma4Entity) obj;

    boolean result = true;
    result = result && (
        java.lang.Double.doubleToLongBits(getZhonggongZhizuo())
        == java.lang.Double.doubleToLongBits(
            other.getZhonggongZhizuo()));
    result = result && (
        java.lang.Double.doubleToLongBits(getZhonggongKuazhong())
        == java.lang.Double.doubleToLongBits(
            other.getZhonggongKuazhong()));
    result = result && (
        java.lang.Double.doubleToLongBits(getZhongchuiZhizuo())
        == java.lang.Double.doubleToLongBits(
            other.getZhongchuiZhizuo()));
    result = result && (
        java.lang.Double.doubleToLongBits(getZhongchuiKuazhong())
        == java.lang.Double.doubleToLongBits(
            other.getZhongchuiKuazhong()));
    result = result && (
        java.lang.Double.doubleToLongBits(getAllowStress())
        == java.lang.Double.doubleToLongBits(
            other.getAllowStress()));
    result = result && (
        java.lang.Double.doubleToLongBits(getCombineAllowStress())
        == java.lang.Double.doubleToLongBits(
            other.getCombineAllowStress()));
    result = result && (
        java.lang.Double.doubleToLongBits(getCombineZhonggongZhizuoShang())
        == java.lang.Double.doubleToLongBits(
            other.getCombineZhonggongZhizuoShang()));
    result = result && (
        java.lang.Double.doubleToLongBits(getCombineZhonggongZhizuoXia())
        == java.lang.Double.doubleToLongBits(
            other.getCombineZhonggongZhizuoXia()));
    result = result && (
        java.lang.Double.doubleToLongBits(getCombineZhonggongKuazhongShang())
        == java.lang.Double.doubleToLongBits(
            other.getCombineZhonggongKuazhongShang()));
    result = result && (
        java.lang.Double.doubleToLongBits(getCombineZhonggongKuazhongXia())
        == java.lang.Double.doubleToLongBits(
            other.getCombineZhonggongKuazhongXia()));
    result = result && (
        java.lang.Double.doubleToLongBits(getCombineZhongchuiZhizuoShang())
        == java.lang.Double.doubleToLongBits(
            other.getCombineZhongchuiZhizuoShang()));
    result = result && (
        java.lang.Double.doubleToLongBits(getCombineZhongchuiZhizuoXia())
        == java.lang.Double.doubleToLongBits(
            other.getCombineZhongchuiZhizuoXia()));
    result = result && (
        java.lang.Double.doubleToLongBits(getCombineZhongchuiKuazhongShang())
        == java.lang.Double.doubleToLongBits(
            other.getCombineZhongchuiKuazhongShang()));
    result = result && (
        java.lang.Double.doubleToLongBits(getCombineZhongchuiKuazhongXia())
        == java.lang.Double.doubleToLongBits(
            other.getCombineZhongchuiKuazhongXia()));
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ZHONGGONGZHIZUO_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getZhonggongZhizuo()));
    hash = (37 * hash) + ZHONGGONGKUAZHONG_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getZhonggongKuazhong()));
    hash = (37 * hash) + ZHONGCHUIZHIZUO_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getZhongchuiZhizuo()));
    hash = (37 * hash) + ZHONGCHUIKUAZHONG_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getZhongchuiKuazhong()));
    hash = (37 * hash) + ALLOWSTRESS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getAllowStress()));
    hash = (37 * hash) + COMBINEALLOWSTRESS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getCombineAllowStress()));
    hash = (37 * hash) + COMBINEZHONGGONGZHIZUOSHANG_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getCombineZhonggongZhizuoShang()));
    hash = (37 * hash) + COMBINEZHONGGONGZHIZUOXIA_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getCombineZhonggongZhizuoXia()));
    hash = (37 * hash) + COMBINEZHONGGONGKUAZHONGSHANG_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getCombineZhonggongKuazhongShang()));
    hash = (37 * hash) + COMBINEZHONGGONGKUAZHONGXIA_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getCombineZhonggongKuazhongXia()));
    hash = (37 * hash) + COMBINEZHONGCHUIZHIZUOSHANG_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getCombineZhongchuiZhizuoShang()));
    hash = (37 * hash) + COMBINEZHONGCHUIZHIZUOXIA_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getCombineZhongchuiZhizuoXia()));
    hash = (37 * hash) + COMBINEZHONGCHUIKUAZHONGSHANG_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getCombineZhongchuiKuazhongShang()));
    hash = (37 * hash) + COMBINEZHONGCHUIKUAZHONGXIA_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getCombineZhongchuiKuazhongXia()));
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.iscas.biz.calculation.grpc.Sigma4Entity parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.iscas.biz.calculation.grpc.Sigma4Entity parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.iscas.biz.calculation.grpc.Sigma4Entity parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.iscas.biz.calculation.grpc.Sigma4Entity parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.iscas.biz.calculation.grpc.Sigma4Entity parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.iscas.biz.calculation.grpc.Sigma4Entity parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.iscas.biz.calculation.grpc.Sigma4Entity parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.iscas.biz.calculation.grpc.Sigma4Entity parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.iscas.biz.calculation.grpc.Sigma4Entity parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.iscas.biz.calculation.grpc.Sigma4Entity parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.iscas.biz.calculation.grpc.Sigma4Entity prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.iscas.biz.calculation.grpc.Sigma4Entity}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.iscas.biz.calculation.grpc.Sigma4Entity)
      com.iscas.biz.calculation.grpc.Sigma4EntityOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.iscas.biz.calculation.grpc.CalculationProto.internal_static_com_iscas_biz_calculation_grpc_Sigma4Entity_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.iscas.biz.calculation.grpc.CalculationProto.internal_static_com_iscas_biz_calculation_grpc_Sigma4Entity_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.iscas.biz.calculation.grpc.Sigma4Entity.class, com.iscas.biz.calculation.grpc.Sigma4Entity.Builder.class);
    }

    // Construct using com.iscas.biz.calculation.grpc.Sigma4Entity.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      zhonggongZhizuo_ = 0D;

      zhonggongKuazhong_ = 0D;

      zhongchuiZhizuo_ = 0D;

      zhongchuiKuazhong_ = 0D;

      allowStress_ = 0D;

      combineAllowStress_ = 0D;

      combineZhonggongZhizuoShang_ = 0D;

      combineZhonggongZhizuoXia_ = 0D;

      combineZhonggongKuazhongShang_ = 0D;

      combineZhonggongKuazhongXia_ = 0D;

      combineZhongchuiZhizuoShang_ = 0D;

      combineZhongchuiZhizuoXia_ = 0D;

      combineZhongchuiKuazhongShang_ = 0D;

      combineZhongchuiKuazhongXia_ = 0D;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.iscas.biz.calculation.grpc.CalculationProto.internal_static_com_iscas_biz_calculation_grpc_Sigma4Entity_descriptor;
    }

    public com.iscas.biz.calculation.grpc.Sigma4Entity getDefaultInstanceForType() {
      return com.iscas.biz.calculation.grpc.Sigma4Entity.getDefaultInstance();
    }

    public com.iscas.biz.calculation.grpc.Sigma4Entity build() {
      com.iscas.biz.calculation.grpc.Sigma4Entity result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.iscas.biz.calculation.grpc.Sigma4Entity buildPartial() {
      com.iscas.biz.calculation.grpc.Sigma4Entity result = new com.iscas.biz.calculation.grpc.Sigma4Entity(this);
      result.zhonggongZhizuo_ = zhonggongZhizuo_;
      result.zhonggongKuazhong_ = zhonggongKuazhong_;
      result.zhongchuiZhizuo_ = zhongchuiZhizuo_;
      result.zhongchuiKuazhong_ = zhongchuiKuazhong_;
      result.allowStress_ = allowStress_;
      result.combineAllowStress_ = combineAllowStress_;
      result.combineZhonggongZhizuoShang_ = combineZhonggongZhizuoShang_;
      result.combineZhonggongZhizuoXia_ = combineZhonggongZhizuoXia_;
      result.combineZhonggongKuazhongShang_ = combineZhonggongKuazhongShang_;
      result.combineZhonggongKuazhongXia_ = combineZhonggongKuazhongXia_;
      result.combineZhongchuiZhizuoShang_ = combineZhongchuiZhizuoShang_;
      result.combineZhongchuiZhizuoXia_ = combineZhongchuiZhizuoXia_;
      result.combineZhongchuiKuazhongShang_ = combineZhongchuiKuazhongShang_;
      result.combineZhongchuiKuazhongXia_ = combineZhongchuiKuazhongXia_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.iscas.biz.calculation.grpc.Sigma4Entity) {
        return mergeFrom((com.iscas.biz.calculation.grpc.Sigma4Entity)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.iscas.biz.calculation.grpc.Sigma4Entity other) {
      if (other == com.iscas.biz.calculation.grpc.Sigma4Entity.getDefaultInstance()) return this;
      if (other.getZhonggongZhizuo() != 0D) {
        setZhonggongZhizuo(other.getZhonggongZhizuo());
      }
      if (other.getZhonggongKuazhong() != 0D) {
        setZhonggongKuazhong(other.getZhonggongKuazhong());
      }
      if (other.getZhongchuiZhizuo() != 0D) {
        setZhongchuiZhizuo(other.getZhongchuiZhizuo());
      }
      if (other.getZhongchuiKuazhong() != 0D) {
        setZhongchuiKuazhong(other.getZhongchuiKuazhong());
      }
      if (other.getAllowStress() != 0D) {
        setAllowStress(other.getAllowStress());
      }
      if (other.getCombineAllowStress() != 0D) {
        setCombineAllowStress(other.getCombineAllowStress());
      }
      if (other.getCombineZhonggongZhizuoShang() != 0D) {
        setCombineZhonggongZhizuoShang(other.getCombineZhonggongZhizuoShang());
      }
      if (other.getCombineZhonggongZhizuoXia() != 0D) {
        setCombineZhonggongZhizuoXia(other.getCombineZhonggongZhizuoXia());
      }
      if (other.getCombineZhonggongKuazhongShang() != 0D) {
        setCombineZhonggongKuazhongShang(other.getCombineZhonggongKuazhongShang());
      }
      if (other.getCombineZhonggongKuazhongXia() != 0D) {
        setCombineZhonggongKuazhongXia(other.getCombineZhonggongKuazhongXia());
      }
      if (other.getCombineZhongchuiZhizuoShang() != 0D) {
        setCombineZhongchuiZhizuoShang(other.getCombineZhongchuiZhizuoShang());
      }
      if (other.getCombineZhongchuiZhizuoXia() != 0D) {
        setCombineZhongchuiZhizuoXia(other.getCombineZhongchuiZhizuoXia());
      }
      if (other.getCombineZhongchuiKuazhongShang() != 0D) {
        setCombineZhongchuiKuazhongShang(other.getCombineZhongchuiKuazhongShang());
      }
      if (other.getCombineZhongchuiKuazhongXia() != 0D) {
        setCombineZhongchuiKuazhongXia(other.getCombineZhongchuiKuazhongXia());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.iscas.biz.calculation.grpc.Sigma4Entity parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.iscas.biz.calculation.grpc.Sigma4Entity) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private double zhonggongZhizuo_ ;
    /**
     * <pre>
     *中拱支座
     * </pre>
     *
     * <code>double zhonggongZhizuo = 1;</code>
     */
    public double getZhonggongZhizuo() {
      return zhonggongZhizuo_;
    }
    /**
     * <pre>
     *中拱支座
     * </pre>
     *
     * <code>double zhonggongZhizuo = 1;</code>
     */
    public Builder setZhonggongZhizuo(double value) {
      
      zhonggongZhizuo_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *中拱支座
     * </pre>
     *
     * <code>double zhonggongZhizuo = 1;</code>
     */
    public Builder clearZhonggongZhizuo() {
      
      zhonggongZhizuo_ = 0D;
      onChanged();
      return this;
    }

    private double zhonggongKuazhong_ ;
    /**
     * <pre>
     *中拱跨中
     * </pre>
     *
     * <code>double zhonggongKuazhong = 2;</code>
     */
    public double getZhonggongKuazhong() {
      return zhonggongKuazhong_;
    }
    /**
     * <pre>
     *中拱跨中
     * </pre>
     *
     * <code>double zhonggongKuazhong = 2;</code>
     */
    public Builder setZhonggongKuazhong(double value) {
      
      zhonggongKuazhong_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *中拱跨中
     * </pre>
     *
     * <code>double zhonggongKuazhong = 2;</code>
     */
    public Builder clearZhonggongKuazhong() {
      
      zhonggongKuazhong_ = 0D;
      onChanged();
      return this;
    }

    private double zhongchuiZhizuo_ ;
    /**
     * <pre>
     *中垂支座
     * </pre>
     *
     * <code>double zhongchuiZhizuo = 3;</code>
     */
    public double getZhongchuiZhizuo() {
      return zhongchuiZhizuo_;
    }
    /**
     * <pre>
     *中垂支座
     * </pre>
     *
     * <code>double zhongchuiZhizuo = 3;</code>
     */
    public Builder setZhongchuiZhizuo(double value) {
      
      zhongchuiZhizuo_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *中垂支座
     * </pre>
     *
     * <code>double zhongchuiZhizuo = 3;</code>
     */
    public Builder clearZhongchuiZhizuo() {
      
      zhongchuiZhizuo_ = 0D;
      onChanged();
      return this;
    }

    private double zhongchuiKuazhong_ ;
    /**
     * <pre>
     *中垂跨中
     * </pre>
     *
     * <code>double zhongchuiKuazhong = 4;</code>
     */
    public double getZhongchuiKuazhong() {
      return zhongchuiKuazhong_;
    }
    /**
     * <pre>
     *中垂跨中
     * </pre>
     *
     * <code>double zhongchuiKuazhong = 4;</code>
     */
    public Builder setZhongchuiKuazhong(double value) {
      
      zhongchuiKuazhong_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *中垂跨中
     * </pre>
     *
     * <code>double zhongchuiKuazhong = 4;</code>
     */
    public Builder clearZhongchuiKuazhong() {
      
      zhongchuiKuazhong_ = 0D;
      onChanged();
      return this;
    }

    private double allowStress_ ;
    /**
     * <pre>
     *许用应力
     * </pre>
     *
     * <code>double allowStress = 5;</code>
     */
    public double getAllowStress() {
      return allowStress_;
    }
    /**
     * <pre>
     *许用应力
     * </pre>
     *
     * <code>double allowStress = 5;</code>
     */
    public Builder setAllowStress(double value) {
      
      allowStress_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *许用应力
     * </pre>
     *
     * <code>double allowStress = 5;</code>
     */
    public Builder clearAllowStress() {
      
      allowStress_ = 0D;
      onChanged();
      return this;
    }

    private double combineAllowStress_ ;
    /**
     * <pre>
     *合成许用应力
     * </pre>
     *
     * <code>double combineAllowStress = 6;</code>
     */
    public double getCombineAllowStress() {
      return combineAllowStress_;
    }
    /**
     * <pre>
     *合成许用应力
     * </pre>
     *
     * <code>double combineAllowStress = 6;</code>
     */
    public Builder setCombineAllowStress(double value) {
      
      combineAllowStress_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *合成许用应力
     * </pre>
     *
     * <code>double combineAllowStress = 6;</code>
     */
    public Builder clearCombineAllowStress() {
      
      combineAllowStress_ = 0D;
      onChanged();
      return this;
    }

    private double combineZhonggongZhizuoShang_ ;
    /**
     * <pre>
     *合成中拱支座上纤维
     * </pre>
     *
     * <code>double combineZhonggongZhizuoShang = 7;</code>
     */
    public double getCombineZhonggongZhizuoShang() {
      return combineZhonggongZhizuoShang_;
    }
    /**
     * <pre>
     *合成中拱支座上纤维
     * </pre>
     *
     * <code>double combineZhonggongZhizuoShang = 7;</code>
     */
    public Builder setCombineZhonggongZhizuoShang(double value) {
      
      combineZhonggongZhizuoShang_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *合成中拱支座上纤维
     * </pre>
     *
     * <code>double combineZhonggongZhizuoShang = 7;</code>
     */
    public Builder clearCombineZhonggongZhizuoShang() {
      
      combineZhonggongZhizuoShang_ = 0D;
      onChanged();
      return this;
    }

    private double combineZhonggongZhizuoXia_ ;
    /**
     * <pre>
     *合成中拱支座下纤维
     * </pre>
     *
     * <code>double combineZhonggongZhizuoXia = 8;</code>
     */
    public double getCombineZhonggongZhizuoXia() {
      return combineZhonggongZhizuoXia_;
    }
    /**
     * <pre>
     *合成中拱支座下纤维
     * </pre>
     *
     * <code>double combineZhonggongZhizuoXia = 8;</code>
     */
    public Builder setCombineZhonggongZhizuoXia(double value) {
      
      combineZhonggongZhizuoXia_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *合成中拱支座下纤维
     * </pre>
     *
     * <code>double combineZhonggongZhizuoXia = 8;</code>
     */
    public Builder clearCombineZhonggongZhizuoXia() {
      
      combineZhonggongZhizuoXia_ = 0D;
      onChanged();
      return this;
    }

    private double combineZhonggongKuazhongShang_ ;
    /**
     * <pre>
     *合成中拱跨中上纤维
     * </pre>
     *
     * <code>double combineZhonggongKuazhongShang = 9;</code>
     */
    public double getCombineZhonggongKuazhongShang() {
      return combineZhonggongKuazhongShang_;
    }
    /**
     * <pre>
     *合成中拱跨中上纤维
     * </pre>
     *
     * <code>double combineZhonggongKuazhongShang = 9;</code>
     */
    public Builder setCombineZhonggongKuazhongShang(double value) {
      
      combineZhonggongKuazhongShang_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *合成中拱跨中上纤维
     * </pre>
     *
     * <code>double combineZhonggongKuazhongShang = 9;</code>
     */
    public Builder clearCombineZhonggongKuazhongShang() {
      
      combineZhonggongKuazhongShang_ = 0D;
      onChanged();
      return this;
    }

    private double combineZhonggongKuazhongXia_ ;
    /**
     * <pre>
     *合成中拱跨中下纤维
     * </pre>
     *
     * <code>double combineZhonggongKuazhongXia = 10;</code>
     */
    public double getCombineZhonggongKuazhongXia() {
      return combineZhonggongKuazhongXia_;
    }
    /**
     * <pre>
     *合成中拱跨中下纤维
     * </pre>
     *
     * <code>double combineZhonggongKuazhongXia = 10;</code>
     */
    public Builder setCombineZhonggongKuazhongXia(double value) {
      
      combineZhonggongKuazhongXia_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *合成中拱跨中下纤维
     * </pre>
     *
     * <code>double combineZhonggongKuazhongXia = 10;</code>
     */
    public Builder clearCombineZhonggongKuazhongXia() {
      
      combineZhonggongKuazhongXia_ = 0D;
      onChanged();
      return this;
    }

    private double combineZhongchuiZhizuoShang_ ;
    /**
     * <pre>
     *合成中垂支座上纤维
     * </pre>
     *
     * <code>double combineZhongchuiZhizuoShang = 11;</code>
     */
    public double getCombineZhongchuiZhizuoShang() {
      return combineZhongchuiZhizuoShang_;
    }
    /**
     * <pre>
     *合成中垂支座上纤维
     * </pre>
     *
     * <code>double combineZhongchuiZhizuoShang = 11;</code>
     */
    public Builder setCombineZhongchuiZhizuoShang(double value) {
      
      combineZhongchuiZhizuoShang_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *合成中垂支座上纤维
     * </pre>
     *
     * <code>double combineZhongchuiZhizuoShang = 11;</code>
     */
    public Builder clearCombineZhongchuiZhizuoShang() {
      
      combineZhongchuiZhizuoShang_ = 0D;
      onChanged();
      return this;
    }

    private double combineZhongchuiZhizuoXia_ ;
    /**
     * <pre>
     *合成中垂支座下纤维
     * </pre>
     *
     * <code>double combineZhongchuiZhizuoXia = 12;</code>
     */
    public double getCombineZhongchuiZhizuoXia() {
      return combineZhongchuiZhizuoXia_;
    }
    /**
     * <pre>
     *合成中垂支座下纤维
     * </pre>
     *
     * <code>double combineZhongchuiZhizuoXia = 12;</code>
     */
    public Builder setCombineZhongchuiZhizuoXia(double value) {
      
      combineZhongchuiZhizuoXia_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *合成中垂支座下纤维
     * </pre>
     *
     * <code>double combineZhongchuiZhizuoXia = 12;</code>
     */
    public Builder clearCombineZhongchuiZhizuoXia() {
      
      combineZhongchuiZhizuoXia_ = 0D;
      onChanged();
      return this;
    }

    private double combineZhongchuiKuazhongShang_ ;
    /**
     * <pre>
     *合成中垂跨中上纤维
     * </pre>
     *
     * <code>double combineZhongchuiKuazhongShang = 13;</code>
     */
    public double getCombineZhongchuiKuazhongShang() {
      return combineZhongchuiKuazhongShang_;
    }
    /**
     * <pre>
     *合成中垂跨中上纤维
     * </pre>
     *
     * <code>double combineZhongchuiKuazhongShang = 13;</code>
     */
    public Builder setCombineZhongchuiKuazhongShang(double value) {
      
      combineZhongchuiKuazhongShang_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *合成中垂跨中上纤维
     * </pre>
     *
     * <code>double combineZhongchuiKuazhongShang = 13;</code>
     */
    public Builder clearCombineZhongchuiKuazhongShang() {
      
      combineZhongchuiKuazhongShang_ = 0D;
      onChanged();
      return this;
    }

    private double combineZhongchuiKuazhongXia_ ;
    /**
     * <pre>
     *合成中垂跨中下纤维
     * </pre>
     *
     * <code>double combineZhongchuiKuazhongXia = 14;</code>
     */
    public double getCombineZhongchuiKuazhongXia() {
      return combineZhongchuiKuazhongXia_;
    }
    /**
     * <pre>
     *合成中垂跨中下纤维
     * </pre>
     *
     * <code>double combineZhongchuiKuazhongXia = 14;</code>
     */
    public Builder setCombineZhongchuiKuazhongXia(double value) {
      
      combineZhongchuiKuazhongXia_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *合成中垂跨中下纤维
     * </pre>
     *
     * <code>double combineZhongchuiKuazhongXia = 14;</code>
     */
    public Builder clearCombineZhongchuiKuazhongXia() {
      
      combineZhongchuiKuazhongXia_ = 0D;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:com.iscas.biz.calculation.grpc.Sigma4Entity)
  }

  // @@protoc_insertion_point(class_scope:com.iscas.biz.calculation.grpc.Sigma4Entity)
  private static final com.iscas.biz.calculation.grpc.Sigma4Entity DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.iscas.biz.calculation.grpc.Sigma4Entity();
  }

  public static com.iscas.biz.calculation.grpc.Sigma4Entity getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Sigma4Entity>
      PARSER = new com.google.protobuf.AbstractParser<Sigma4Entity>() {
    public Sigma4Entity parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new Sigma4Entity(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Sigma4Entity> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Sigma4Entity> getParserForType() {
    return PARSER;
  }

  public com.iscas.biz.calculation.grpc.Sigma4Entity getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

