// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: calculation.proto

package com.iscas.biz.calculation.grpc;

/**
 * Protobuf type {@code com.iscas.biz.calculation.grpc.Sigma1Request}
 */
public  final class Sigma1Request extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.iscas.biz.calculation.grpc.Sigma1Request)
    Sigma1RequestOrBuilder {
  // Use Sigma1Request.newBuilder() to construct.
  private Sigma1Request(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Sigma1Request() {
    kuaChang_ = java.util.Collections.emptyList();
    girderDistance_ = 0D;
    frDistance_ = 0D;
    trusswidth_ = 0D;
    frGuige_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    plateThick_ = java.util.Collections.emptyList();
    deviceWeight_ = 0D;
    girderWidth_ = java.util.Collections.emptyList();
    materialYieldLimit_ = 0D;
    isCustomLoad_ = false;
    midArchWaveMoment_ = 0D;
    midArchImpactMoment_ = 0D;
    midArchShear_ = 0D;
    midArchDraught_ = 0D;
    midVerticalWaveMoment_ = 0D;
    midVerticalImpactMoment_ = 0D;
    midVerticalShear_ = 0D;
    midVerticalDraught_ = 0D;
    xiancethick_ = java.util.Collections.emptyList();
    numGirder_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private Sigma1Request(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 9: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              kuaChang_ = new java.util.ArrayList<java.lang.Double>();
              mutable_bitField0_ |= 0x00000001;
            }
            kuaChang_.add(input.readDouble());
            break;
          }
          case 10: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
              kuaChang_ = new java.util.ArrayList<java.lang.Double>();
              mutable_bitField0_ |= 0x00000001;
            }
            while (input.getBytesUntilLimit() > 0) {
              kuaChang_.add(input.readDouble());
            }
            input.popLimit(limit);
            break;
          }
          case 17: {

            girderDistance_ = input.readDouble();
            break;
          }
          case 25: {

            frDistance_ = input.readDouble();
            break;
          }
          case 33: {

            trusswidth_ = input.readDouble();
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
              frGuige_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000010;
            }
            frGuige_.add(s);
            break;
          }
          case 49: {
            if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
              plateThick_ = new java.util.ArrayList<java.lang.Double>();
              mutable_bitField0_ |= 0x00000020;
            }
            plateThick_.add(input.readDouble());
            break;
          }
          case 50: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000020) == 0x00000020) && input.getBytesUntilLimit() > 0) {
              plateThick_ = new java.util.ArrayList<java.lang.Double>();
              mutable_bitField0_ |= 0x00000020;
            }
            while (input.getBytesUntilLimit() > 0) {
              plateThick_.add(input.readDouble());
            }
            input.popLimit(limit);
            break;
          }
          case 57: {

            deviceWeight_ = input.readDouble();
            break;
          }
          case 65: {
            if (!((mutable_bitField0_ & 0x00000080) == 0x00000080)) {
              girderWidth_ = new java.util.ArrayList<java.lang.Double>();
              mutable_bitField0_ |= 0x00000080;
            }
            girderWidth_.add(input.readDouble());
            break;
          }
          case 66: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000080) == 0x00000080) && input.getBytesUntilLimit() > 0) {
              girderWidth_ = new java.util.ArrayList<java.lang.Double>();
              mutable_bitField0_ |= 0x00000080;
            }
            while (input.getBytesUntilLimit() > 0) {
              girderWidth_.add(input.readDouble());
            }
            input.popLimit(limit);
            break;
          }
          case 73: {

            materialYieldLimit_ = input.readDouble();
            break;
          }
          case 80: {

            isCustomLoad_ = input.readBool();
            break;
          }
          case 89: {

            midArchWaveMoment_ = input.readDouble();
            break;
          }
          case 97: {

            midArchImpactMoment_ = input.readDouble();
            break;
          }
          case 105: {

            midArchShear_ = input.readDouble();
            break;
          }
          case 113: {

            midArchDraught_ = input.readDouble();
            break;
          }
          case 121: {

            midVerticalWaveMoment_ = input.readDouble();
            break;
          }
          case 129: {

            midVerticalImpactMoment_ = input.readDouble();
            break;
          }
          case 137: {

            midVerticalShear_ = input.readDouble();
            break;
          }
          case 145: {

            midVerticalDraught_ = input.readDouble();
            break;
          }
          case 153: {
            if (!((mutable_bitField0_ & 0x00040000) == 0x00040000)) {
              xiancethick_ = new java.util.ArrayList<java.lang.Double>();
              mutable_bitField0_ |= 0x00040000;
            }
            xiancethick_.add(input.readDouble());
            break;
          }
          case 154: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00040000) == 0x00040000) && input.getBytesUntilLimit() > 0) {
              xiancethick_ = new java.util.ArrayList<java.lang.Double>();
              mutable_bitField0_ |= 0x00040000;
            }
            while (input.getBytesUntilLimit() > 0) {
              xiancethick_.add(input.readDouble());
            }
            input.popLimit(limit);
            break;
          }
          case 160: {

            numGirder_ = input.readInt32();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        kuaChang_ = java.util.Collections.unmodifiableList(kuaChang_);
      }
      if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
        frGuige_ = frGuige_.getUnmodifiableView();
      }
      if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
        plateThick_ = java.util.Collections.unmodifiableList(plateThick_);
      }
      if (((mutable_bitField0_ & 0x00000080) == 0x00000080)) {
        girderWidth_ = java.util.Collections.unmodifiableList(girderWidth_);
      }
      if (((mutable_bitField0_ & 0x00040000) == 0x00040000)) {
        xiancethick_ = java.util.Collections.unmodifiableList(xiancethick_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.iscas.biz.calculation.grpc.CalculationProto.internal_static_com_iscas_biz_calculation_grpc_Sigma1Request_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.iscas.biz.calculation.grpc.CalculationProto.internal_static_com_iscas_biz_calculation_grpc_Sigma1Request_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.iscas.biz.calculation.grpc.Sigma1Request.class, com.iscas.biz.calculation.grpc.Sigma1Request.Builder.class);
  }

  private int bitField0_;
  public static final int KUACHANG_FIELD_NUMBER = 1;
  private java.util.List<java.lang.Double> kuaChang_;
  /**
   * <pre>
   *构件跨距-龙骨跨距 跨距
   * </pre>
   *
   * <code>repeated double kuaChang = 1;</code>
   */
  public java.util.List<java.lang.Double>
      getKuaChangList() {
    return kuaChang_;
  }
  /**
   * <pre>
   *构件跨距-龙骨跨距 跨距
   * </pre>
   *
   * <code>repeated double kuaChang = 1;</code>
   */
  public int getKuaChangCount() {
    return kuaChang_.size();
  }
  /**
   * <pre>
   *构件跨距-龙骨跨距 跨距
   * </pre>
   *
   * <code>repeated double kuaChang = 1;</code>
   */
  public double getKuaChang(int index) {
    return kuaChang_.get(index);
  }
  private int kuaChangMemoizedSerializedSize = -1;

  public static final int GIRDERDISTANCE_FIELD_NUMBER = 2;
  private double girderDistance_;
  /**
   * <pre>
   *剖面位置x-肋板间距
   * </pre>
   *
   * <code>double girderDistance = 2;</code>
   */
  public double getGirderDistance() {
    return girderDistance_;
  }

  public static final int FRDISTANCE_FIELD_NUMBER = 3;
  private double frDistance_;
  /**
   * <pre>
   *纵骨间距
   * </pre>
   *
   * <code>double frDistance = 3;</code>
   */
  public double getFrDistance() {
    return frDistance_;
  }

  public static final int TRUSSWIDTH_FIELD_NUMBER = 4;
  private double trusswidth_;
  /**
   * <pre>
   *板架宽度 添加614
   * </pre>
   *
   * <code>double trusswidth = 4;</code>
   */
  public double getTrusswidth() {
    return trusswidth_;
  }

  public static final int FRGUIGE_FIELD_NUMBER = 5;
  private com.google.protobuf.LazyStringList frGuige_;
  /**
   * <pre>
   *纵骨规格 每个的规格
   *修改614 double-&gt;string
   * </pre>
   *
   * <code>repeated string frGuige = 5;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getFrGuigeList() {
    return frGuige_;
  }
  /**
   * <pre>
   *纵骨规格 每个的规格
   *修改614 double-&gt;string
   * </pre>
   *
   * <code>repeated string frGuige = 5;</code>
   */
  public int getFrGuigeCount() {
    return frGuige_.size();
  }
  /**
   * <pre>
   *纵骨规格 每个的规格
   *修改614 double-&gt;string
   * </pre>
   *
   * <code>repeated string frGuige = 5;</code>
   */
  public java.lang.String getFrGuige(int index) {
    return frGuige_.get(index);
  }
  /**
   * <pre>
   *纵骨规格 每个的规格
   *修改614 double-&gt;string
   * </pre>
   *
   * <code>repeated string frGuige = 5;</code>
   */
  public com.google.protobuf.ByteString
      getFrGuigeBytes(int index) {
    return frGuige_.getByteString(index);
  }

  public static final int PLATETHICK_FIELD_NUMBER = 6;
  private java.util.List<java.lang.Double> plateThick_;
  /**
   * <pre>
   *外底板厚 每个板材的厚度
   * </pre>
   *
   * <code>repeated double plateThick = 6;</code>
   */
  public java.util.List<java.lang.Double>
      getPlateThickList() {
    return plateThick_;
  }
  /**
   * <pre>
   *外底板厚 每个板材的厚度
   * </pre>
   *
   * <code>repeated double plateThick = 6;</code>
   */
  public int getPlateThickCount() {
    return plateThick_.size();
  }
  /**
   * <pre>
   *外底板厚 每个板材的厚度
   * </pre>
   *
   * <code>repeated double plateThick = 6;</code>
   */
  public double getPlateThick(int index) {
    return plateThick_.get(index);
  }
  private int plateThickMemoizedSerializedSize = -1;

  public static final int DEVICEWEIGHT_FIELD_NUMBER = 7;
  private double deviceWeight_;
  /**
   * <pre>
   *设备重量(t)
   * </pre>
   *
   * <code>double deviceWeight = 7;</code>
   */
  public double getDeviceWeight() {
    return deviceWeight_;
  }

  public static final int GIRDERWIDTH_FIELD_NUMBER = 8;
  private java.util.List<java.lang.Double> girderWidth_;
  /**
   * <pre>
   *外底板宽度 修改614为数组
   * </pre>
   *
   * <code>repeated double girderWidth = 8;</code>
   */
  public java.util.List<java.lang.Double>
      getGirderWidthList() {
    return girderWidth_;
  }
  /**
   * <pre>
   *外底板宽度 修改614为数组
   * </pre>
   *
   * <code>repeated double girderWidth = 8;</code>
   */
  public int getGirderWidthCount() {
    return girderWidth_.size();
  }
  /**
   * <pre>
   *外底板宽度 修改614为数组
   * </pre>
   *
   * <code>repeated double girderWidth = 8;</code>
   */
  public double getGirderWidth(int index) {
    return girderWidth_.get(index);
  }
  private int girderWidthMemoizedSerializedSize = -1;

  public static final int MATERIALYIELDLIMIT_FIELD_NUMBER = 9;
  private double materialYieldLimit_;
  /**
   * <pre>
   *new614----------------
   *材料类型 改为材料屈服极限
   * </pre>
   *
   * <code>double materialYieldLimit = 9;</code>
   */
  public double getMaterialYieldLimit() {
    return materialYieldLimit_;
  }

  public static final int ISCUSTOMLOAD_FIELD_NUMBER = 10;
  private boolean isCustomLoad_;
  /**
   * <pre>
   *new614----------------
   *是否采用自定义载荷
   * </pre>
   *
   * <code>bool isCustomLoad = 10;</code>
   */
  public boolean getIsCustomLoad() {
    return isCustomLoad_;
  }

  public static final int MIDARCHWAVEMOMENT_FIELD_NUMBER = 11;
  private double midArchWaveMoment_;
  /**
   * <pre>
   **
   * 中拱-波浪弯矩
   * </pre>
   *
   * <code>double midArchWaveMoment = 11;</code>
   */
  public double getMidArchWaveMoment() {
    return midArchWaveMoment_;
  }

  public static final int MIDARCHIMPACTMOMENT_FIELD_NUMBER = 12;
  private double midArchImpactMoment_;
  /**
   * <pre>
   **
   * 中拱-砰击弯矩
   * </pre>
   *
   * <code>double midArchImpactMoment = 12;</code>
   */
  public double getMidArchImpactMoment() {
    return midArchImpactMoment_;
  }

  public static final int MIDARCHSHEAR_FIELD_NUMBER = 13;
  private double midArchShear_;
  /**
   * <pre>
   **
   * 中拱-剪力
   * </pre>
   *
   * <code>double midArchShear = 13;</code>
   */
  public double getMidArchShear() {
    return midArchShear_;
  }

  public static final int MIDARCHDRAUGHT_FIELD_NUMBER = 14;
  private double midArchDraught_;
  /**
   * <pre>
   **添加614
   * 中拱-吃水
   * </pre>
   *
   * <code>double midArchDraught = 14;</code>
   */
  public double getMidArchDraught() {
    return midArchDraught_;
  }

  public static final int MIDVERTICALWAVEMOMENT_FIELD_NUMBER = 15;
  private double midVerticalWaveMoment_;
  /**
   * <pre>
   **
   * 中垂-波浪弯矩
   * </pre>
   *
   * <code>double midVerticalWaveMoment = 15;</code>
   */
  public double getMidVerticalWaveMoment() {
    return midVerticalWaveMoment_;
  }

  public static final int MIDVERTICALIMPACTMOMENT_FIELD_NUMBER = 16;
  private double midVerticalImpactMoment_;
  /**
   * <pre>
   **
   * 中垂-砰击弯矩
   * </pre>
   *
   * <code>double midVerticalImpactMoment = 16;</code>
   */
  public double getMidVerticalImpactMoment() {
    return midVerticalImpactMoment_;
  }

  public static final int MIDVERTICALSHEAR_FIELD_NUMBER = 17;
  private double midVerticalShear_;
  /**
   * <pre>
   **
   * 中垂-剪力
   * </pre>
   *
   * <code>double midVerticalShear = 17;</code>
   */
  public double getMidVerticalShear() {
    return midVerticalShear_;
  }

  public static final int MIDVERTICALDRAUGHT_FIELD_NUMBER = 18;
  private double midVerticalDraught_;
  /**
   * <pre>
   **添加614
   * 中垂-吃水
   * </pre>
   *
   * <code>double midVerticalDraught = 18;</code>
   */
  public double getMidVerticalDraught() {
    return midVerticalDraught_;
  }

  public static final int XIANCETHICK_FIELD_NUMBER = 19;
  private java.util.List<java.lang.Double> xiancethick_;
  /**
   * <pre>
   **添加614
   * 舷侧中和轴附近板的厚度
   * </pre>
   *
   * <code>repeated double xiancethick = 19;</code>
   */
  public java.util.List<java.lang.Double>
      getXiancethickList() {
    return xiancethick_;
  }
  /**
   * <pre>
   **添加614
   * 舷侧中和轴附近板的厚度
   * </pre>
   *
   * <code>repeated double xiancethick = 19;</code>
   */
  public int getXiancethickCount() {
    return xiancethick_.size();
  }
  /**
   * <pre>
   **添加614
   * 舷侧中和轴附近板的厚度
   * </pre>
   *
   * <code>repeated double xiancethick = 19;</code>
   */
  public double getXiancethick(int index) {
    return xiancethick_.get(index);
  }
  private int xiancethickMemoizedSerializedSize = -1;

  public static final int NUMGIRDER_FIELD_NUMBER = 20;
  private int numGirder_;
  /**
   * <pre>
   *龙骨数量
   * </pre>
   *
   * <code>int32 numGirder = 20;</code>
   */
  public int getNumGirder() {
    return numGirder_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (getKuaChangList().size() > 0) {
      output.writeUInt32NoTag(10);
      output.writeUInt32NoTag(kuaChangMemoizedSerializedSize);
    }
    for (int i = 0; i < kuaChang_.size(); i++) {
      output.writeDoubleNoTag(kuaChang_.get(i));
    }
    if (girderDistance_ != 0D) {
      output.writeDouble(2, girderDistance_);
    }
    if (frDistance_ != 0D) {
      output.writeDouble(3, frDistance_);
    }
    if (trusswidth_ != 0D) {
      output.writeDouble(4, trusswidth_);
    }
    for (int i = 0; i < frGuige_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, frGuige_.getRaw(i));
    }
    if (getPlateThickList().size() > 0) {
      output.writeUInt32NoTag(50);
      output.writeUInt32NoTag(plateThickMemoizedSerializedSize);
    }
    for (int i = 0; i < plateThick_.size(); i++) {
      output.writeDoubleNoTag(plateThick_.get(i));
    }
    if (deviceWeight_ != 0D) {
      output.writeDouble(7, deviceWeight_);
    }
    if (getGirderWidthList().size() > 0) {
      output.writeUInt32NoTag(66);
      output.writeUInt32NoTag(girderWidthMemoizedSerializedSize);
    }
    for (int i = 0; i < girderWidth_.size(); i++) {
      output.writeDoubleNoTag(girderWidth_.get(i));
    }
    if (materialYieldLimit_ != 0D) {
      output.writeDouble(9, materialYieldLimit_);
    }
    if (isCustomLoad_ != false) {
      output.writeBool(10, isCustomLoad_);
    }
    if (midArchWaveMoment_ != 0D) {
      output.writeDouble(11, midArchWaveMoment_);
    }
    if (midArchImpactMoment_ != 0D) {
      output.writeDouble(12, midArchImpactMoment_);
    }
    if (midArchShear_ != 0D) {
      output.writeDouble(13, midArchShear_);
    }
    if (midArchDraught_ != 0D) {
      output.writeDouble(14, midArchDraught_);
    }
    if (midVerticalWaveMoment_ != 0D) {
      output.writeDouble(15, midVerticalWaveMoment_);
    }
    if (midVerticalImpactMoment_ != 0D) {
      output.writeDouble(16, midVerticalImpactMoment_);
    }
    if (midVerticalShear_ != 0D) {
      output.writeDouble(17, midVerticalShear_);
    }
    if (midVerticalDraught_ != 0D) {
      output.writeDouble(18, midVerticalDraught_);
    }
    if (getXiancethickList().size() > 0) {
      output.writeUInt32NoTag(154);
      output.writeUInt32NoTag(xiancethickMemoizedSerializedSize);
    }
    for (int i = 0; i < xiancethick_.size(); i++) {
      output.writeDoubleNoTag(xiancethick_.get(i));
    }
    if (numGirder_ != 0) {
      output.writeInt32(20, numGirder_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      dataSize = 8 * getKuaChangList().size();
      size += dataSize;
      if (!getKuaChangList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      kuaChangMemoizedSerializedSize = dataSize;
    }
    if (girderDistance_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, girderDistance_);
    }
    if (frDistance_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(3, frDistance_);
    }
    if (trusswidth_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(4, trusswidth_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < frGuige_.size(); i++) {
        dataSize += computeStringSizeNoTag(frGuige_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getFrGuigeList().size();
    }
    {
      int dataSize = 0;
      dataSize = 8 * getPlateThickList().size();
      size += dataSize;
      if (!getPlateThickList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      plateThickMemoizedSerializedSize = dataSize;
    }
    if (deviceWeight_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(7, deviceWeight_);
    }
    {
      int dataSize = 0;
      dataSize = 8 * getGirderWidthList().size();
      size += dataSize;
      if (!getGirderWidthList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      girderWidthMemoizedSerializedSize = dataSize;
    }
    if (materialYieldLimit_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(9, materialYieldLimit_);
    }
    if (isCustomLoad_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(10, isCustomLoad_);
    }
    if (midArchWaveMoment_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(11, midArchWaveMoment_);
    }
    if (midArchImpactMoment_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(12, midArchImpactMoment_);
    }
    if (midArchShear_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(13, midArchShear_);
    }
    if (midArchDraught_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(14, midArchDraught_);
    }
    if (midVerticalWaveMoment_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(15, midVerticalWaveMoment_);
    }
    if (midVerticalImpactMoment_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(16, midVerticalImpactMoment_);
    }
    if (midVerticalShear_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(17, midVerticalShear_);
    }
    if (midVerticalDraught_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(18, midVerticalDraught_);
    }
    {
      int dataSize = 0;
      dataSize = 8 * getXiancethickList().size();
      size += dataSize;
      if (!getXiancethickList().isEmpty()) {
        size += 2;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      xiancethickMemoizedSerializedSize = dataSize;
    }
    if (numGirder_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(20, numGirder_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.iscas.biz.calculation.grpc.Sigma1Request)) {
      return super.equals(obj);
    }
    com.iscas.biz.calculation.grpc.Sigma1Request other = (com.iscas.biz.calculation.grpc.Sigma1Request) obj;

    boolean result = true;
    result = result && getKuaChangList()
        .equals(other.getKuaChangList());
    result = result && (
        java.lang.Double.doubleToLongBits(getGirderDistance())
        == java.lang.Double.doubleToLongBits(
            other.getGirderDistance()));
    result = result && (
        java.lang.Double.doubleToLongBits(getFrDistance())
        == java.lang.Double.doubleToLongBits(
            other.getFrDistance()));
    result = result && (
        java.lang.Double.doubleToLongBits(getTrusswidth())
        == java.lang.Double.doubleToLongBits(
            other.getTrusswidth()));
    result = result && getFrGuigeList()
        .equals(other.getFrGuigeList());
    result = result && getPlateThickList()
        .equals(other.getPlateThickList());
    result = result && (
        java.lang.Double.doubleToLongBits(getDeviceWeight())
        == java.lang.Double.doubleToLongBits(
            other.getDeviceWeight()));
    result = result && getGirderWidthList()
        .equals(other.getGirderWidthList());
    result = result && (
        java.lang.Double.doubleToLongBits(getMaterialYieldLimit())
        == java.lang.Double.doubleToLongBits(
            other.getMaterialYieldLimit()));
    result = result && (getIsCustomLoad()
        == other.getIsCustomLoad());
    result = result && (
        java.lang.Double.doubleToLongBits(getMidArchWaveMoment())
        == java.lang.Double.doubleToLongBits(
            other.getMidArchWaveMoment()));
    result = result && (
        java.lang.Double.doubleToLongBits(getMidArchImpactMoment())
        == java.lang.Double.doubleToLongBits(
            other.getMidArchImpactMoment()));
    result = result && (
        java.lang.Double.doubleToLongBits(getMidArchShear())
        == java.lang.Double.doubleToLongBits(
            other.getMidArchShear()));
    result = result && (
        java.lang.Double.doubleToLongBits(getMidArchDraught())
        == java.lang.Double.doubleToLongBits(
            other.getMidArchDraught()));
    result = result && (
        java.lang.Double.doubleToLongBits(getMidVerticalWaveMoment())
        == java.lang.Double.doubleToLongBits(
            other.getMidVerticalWaveMoment()));
    result = result && (
        java.lang.Double.doubleToLongBits(getMidVerticalImpactMoment())
        == java.lang.Double.doubleToLongBits(
            other.getMidVerticalImpactMoment()));
    result = result && (
        java.lang.Double.doubleToLongBits(getMidVerticalShear())
        == java.lang.Double.doubleToLongBits(
            other.getMidVerticalShear()));
    result = result && (
        java.lang.Double.doubleToLongBits(getMidVerticalDraught())
        == java.lang.Double.doubleToLongBits(
            other.getMidVerticalDraught()));
    result = result && getXiancethickList()
        .equals(other.getXiancethickList());
    result = result && (getNumGirder()
        == other.getNumGirder());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getKuaChangCount() > 0) {
      hash = (37 * hash) + KUACHANG_FIELD_NUMBER;
      hash = (53 * hash) + getKuaChangList().hashCode();
    }
    hash = (37 * hash) + GIRDERDISTANCE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getGirderDistance()));
    hash = (37 * hash) + FRDISTANCE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getFrDistance()));
    hash = (37 * hash) + TRUSSWIDTH_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getTrusswidth()));
    if (getFrGuigeCount() > 0) {
      hash = (37 * hash) + FRGUIGE_FIELD_NUMBER;
      hash = (53 * hash) + getFrGuigeList().hashCode();
    }
    if (getPlateThickCount() > 0) {
      hash = (37 * hash) + PLATETHICK_FIELD_NUMBER;
      hash = (53 * hash) + getPlateThickList().hashCode();
    }
    hash = (37 * hash) + DEVICEWEIGHT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getDeviceWeight()));
    if (getGirderWidthCount() > 0) {
      hash = (37 * hash) + GIRDERWIDTH_FIELD_NUMBER;
      hash = (53 * hash) + getGirderWidthList().hashCode();
    }
    hash = (37 * hash) + MATERIALYIELDLIMIT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getMaterialYieldLimit()));
    hash = (37 * hash) + ISCUSTOMLOAD_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsCustomLoad());
    hash = (37 * hash) + MIDARCHWAVEMOMENT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getMidArchWaveMoment()));
    hash = (37 * hash) + MIDARCHIMPACTMOMENT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getMidArchImpactMoment()));
    hash = (37 * hash) + MIDARCHSHEAR_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getMidArchShear()));
    hash = (37 * hash) + MIDARCHDRAUGHT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getMidArchDraught()));
    hash = (37 * hash) + MIDVERTICALWAVEMOMENT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getMidVerticalWaveMoment()));
    hash = (37 * hash) + MIDVERTICALIMPACTMOMENT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getMidVerticalImpactMoment()));
    hash = (37 * hash) + MIDVERTICALSHEAR_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getMidVerticalShear()));
    hash = (37 * hash) + MIDVERTICALDRAUGHT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getMidVerticalDraught()));
    if (getXiancethickCount() > 0) {
      hash = (37 * hash) + XIANCETHICK_FIELD_NUMBER;
      hash = (53 * hash) + getXiancethickList().hashCode();
    }
    hash = (37 * hash) + NUMGIRDER_FIELD_NUMBER;
    hash = (53 * hash) + getNumGirder();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.iscas.biz.calculation.grpc.Sigma1Request parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.iscas.biz.calculation.grpc.Sigma1Request parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.iscas.biz.calculation.grpc.Sigma1Request parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.iscas.biz.calculation.grpc.Sigma1Request parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.iscas.biz.calculation.grpc.Sigma1Request parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.iscas.biz.calculation.grpc.Sigma1Request parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.iscas.biz.calculation.grpc.Sigma1Request parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.iscas.biz.calculation.grpc.Sigma1Request parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.iscas.biz.calculation.grpc.Sigma1Request parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.iscas.biz.calculation.grpc.Sigma1Request parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.iscas.biz.calculation.grpc.Sigma1Request prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.iscas.biz.calculation.grpc.Sigma1Request}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.iscas.biz.calculation.grpc.Sigma1Request)
      com.iscas.biz.calculation.grpc.Sigma1RequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.iscas.biz.calculation.grpc.CalculationProto.internal_static_com_iscas_biz_calculation_grpc_Sigma1Request_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.iscas.biz.calculation.grpc.CalculationProto.internal_static_com_iscas_biz_calculation_grpc_Sigma1Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.iscas.biz.calculation.grpc.Sigma1Request.class, com.iscas.biz.calculation.grpc.Sigma1Request.Builder.class);
    }

    // Construct using com.iscas.biz.calculation.grpc.Sigma1Request.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      kuaChang_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);
      girderDistance_ = 0D;

      frDistance_ = 0D;

      trusswidth_ = 0D;

      frGuige_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000010);
      plateThick_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000020);
      deviceWeight_ = 0D;

      girderWidth_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000080);
      materialYieldLimit_ = 0D;

      isCustomLoad_ = false;

      midArchWaveMoment_ = 0D;

      midArchImpactMoment_ = 0D;

      midArchShear_ = 0D;

      midArchDraught_ = 0D;

      midVerticalWaveMoment_ = 0D;

      midVerticalImpactMoment_ = 0D;

      midVerticalShear_ = 0D;

      midVerticalDraught_ = 0D;

      xiancethick_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00040000);
      numGirder_ = 0;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.iscas.biz.calculation.grpc.CalculationProto.internal_static_com_iscas_biz_calculation_grpc_Sigma1Request_descriptor;
    }

    public com.iscas.biz.calculation.grpc.Sigma1Request getDefaultInstanceForType() {
      return com.iscas.biz.calculation.grpc.Sigma1Request.getDefaultInstance();
    }

    public com.iscas.biz.calculation.grpc.Sigma1Request build() {
      com.iscas.biz.calculation.grpc.Sigma1Request result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.iscas.biz.calculation.grpc.Sigma1Request buildPartial() {
      com.iscas.biz.calculation.grpc.Sigma1Request result = new com.iscas.biz.calculation.grpc.Sigma1Request(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        kuaChang_ = java.util.Collections.unmodifiableList(kuaChang_);
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.kuaChang_ = kuaChang_;
      result.girderDistance_ = girderDistance_;
      result.frDistance_ = frDistance_;
      result.trusswidth_ = trusswidth_;
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        frGuige_ = frGuige_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000010);
      }
      result.frGuige_ = frGuige_;
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        plateThick_ = java.util.Collections.unmodifiableList(plateThick_);
        bitField0_ = (bitField0_ & ~0x00000020);
      }
      result.plateThick_ = plateThick_;
      result.deviceWeight_ = deviceWeight_;
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        girderWidth_ = java.util.Collections.unmodifiableList(girderWidth_);
        bitField0_ = (bitField0_ & ~0x00000080);
      }
      result.girderWidth_ = girderWidth_;
      result.materialYieldLimit_ = materialYieldLimit_;
      result.isCustomLoad_ = isCustomLoad_;
      result.midArchWaveMoment_ = midArchWaveMoment_;
      result.midArchImpactMoment_ = midArchImpactMoment_;
      result.midArchShear_ = midArchShear_;
      result.midArchDraught_ = midArchDraught_;
      result.midVerticalWaveMoment_ = midVerticalWaveMoment_;
      result.midVerticalImpactMoment_ = midVerticalImpactMoment_;
      result.midVerticalShear_ = midVerticalShear_;
      result.midVerticalDraught_ = midVerticalDraught_;
      if (((bitField0_ & 0x00040000) == 0x00040000)) {
        xiancethick_ = java.util.Collections.unmodifiableList(xiancethick_);
        bitField0_ = (bitField0_ & ~0x00040000);
      }
      result.xiancethick_ = xiancethick_;
      result.numGirder_ = numGirder_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.iscas.biz.calculation.grpc.Sigma1Request) {
        return mergeFrom((com.iscas.biz.calculation.grpc.Sigma1Request)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.iscas.biz.calculation.grpc.Sigma1Request other) {
      if (other == com.iscas.biz.calculation.grpc.Sigma1Request.getDefaultInstance()) return this;
      if (!other.kuaChang_.isEmpty()) {
        if (kuaChang_.isEmpty()) {
          kuaChang_ = other.kuaChang_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureKuaChangIsMutable();
          kuaChang_.addAll(other.kuaChang_);
        }
        onChanged();
      }
      if (other.getGirderDistance() != 0D) {
        setGirderDistance(other.getGirderDistance());
      }
      if (other.getFrDistance() != 0D) {
        setFrDistance(other.getFrDistance());
      }
      if (other.getTrusswidth() != 0D) {
        setTrusswidth(other.getTrusswidth());
      }
      if (!other.frGuige_.isEmpty()) {
        if (frGuige_.isEmpty()) {
          frGuige_ = other.frGuige_;
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          ensureFrGuigeIsMutable();
          frGuige_.addAll(other.frGuige_);
        }
        onChanged();
      }
      if (!other.plateThick_.isEmpty()) {
        if (plateThick_.isEmpty()) {
          plateThick_ = other.plateThick_;
          bitField0_ = (bitField0_ & ~0x00000020);
        } else {
          ensurePlateThickIsMutable();
          plateThick_.addAll(other.plateThick_);
        }
        onChanged();
      }
      if (other.getDeviceWeight() != 0D) {
        setDeviceWeight(other.getDeviceWeight());
      }
      if (!other.girderWidth_.isEmpty()) {
        if (girderWidth_.isEmpty()) {
          girderWidth_ = other.girderWidth_;
          bitField0_ = (bitField0_ & ~0x00000080);
        } else {
          ensureGirderWidthIsMutable();
          girderWidth_.addAll(other.girderWidth_);
        }
        onChanged();
      }
      if (other.getMaterialYieldLimit() != 0D) {
        setMaterialYieldLimit(other.getMaterialYieldLimit());
      }
      if (other.getIsCustomLoad() != false) {
        setIsCustomLoad(other.getIsCustomLoad());
      }
      if (other.getMidArchWaveMoment() != 0D) {
        setMidArchWaveMoment(other.getMidArchWaveMoment());
      }
      if (other.getMidArchImpactMoment() != 0D) {
        setMidArchImpactMoment(other.getMidArchImpactMoment());
      }
      if (other.getMidArchShear() != 0D) {
        setMidArchShear(other.getMidArchShear());
      }
      if (other.getMidArchDraught() != 0D) {
        setMidArchDraught(other.getMidArchDraught());
      }
      if (other.getMidVerticalWaveMoment() != 0D) {
        setMidVerticalWaveMoment(other.getMidVerticalWaveMoment());
      }
      if (other.getMidVerticalImpactMoment() != 0D) {
        setMidVerticalImpactMoment(other.getMidVerticalImpactMoment());
      }
      if (other.getMidVerticalShear() != 0D) {
        setMidVerticalShear(other.getMidVerticalShear());
      }
      if (other.getMidVerticalDraught() != 0D) {
        setMidVerticalDraught(other.getMidVerticalDraught());
      }
      if (!other.xiancethick_.isEmpty()) {
        if (xiancethick_.isEmpty()) {
          xiancethick_ = other.xiancethick_;
          bitField0_ = (bitField0_ & ~0x00040000);
        } else {
          ensureXiancethickIsMutable();
          xiancethick_.addAll(other.xiancethick_);
        }
        onChanged();
      }
      if (other.getNumGirder() != 0) {
        setNumGirder(other.getNumGirder());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.iscas.biz.calculation.grpc.Sigma1Request parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.iscas.biz.calculation.grpc.Sigma1Request) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<java.lang.Double> kuaChang_ = java.util.Collections.emptyList();
    private void ensureKuaChangIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        kuaChang_ = new java.util.ArrayList<java.lang.Double>(kuaChang_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <pre>
     *构件跨距-龙骨跨距 跨距
     * </pre>
     *
     * <code>repeated double kuaChang = 1;</code>
     */
    public java.util.List<java.lang.Double>
        getKuaChangList() {
      return java.util.Collections.unmodifiableList(kuaChang_);
    }
    /**
     * <pre>
     *构件跨距-龙骨跨距 跨距
     * </pre>
     *
     * <code>repeated double kuaChang = 1;</code>
     */
    public int getKuaChangCount() {
      return kuaChang_.size();
    }
    /**
     * <pre>
     *构件跨距-龙骨跨距 跨距
     * </pre>
     *
     * <code>repeated double kuaChang = 1;</code>
     */
    public double getKuaChang(int index) {
      return kuaChang_.get(index);
    }
    /**
     * <pre>
     *构件跨距-龙骨跨距 跨距
     * </pre>
     *
     * <code>repeated double kuaChang = 1;</code>
     */
    public Builder setKuaChang(
        int index, double value) {
      ensureKuaChangIsMutable();
      kuaChang_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *构件跨距-龙骨跨距 跨距
     * </pre>
     *
     * <code>repeated double kuaChang = 1;</code>
     */
    public Builder addKuaChang(double value) {
      ensureKuaChangIsMutable();
      kuaChang_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *构件跨距-龙骨跨距 跨距
     * </pre>
     *
     * <code>repeated double kuaChang = 1;</code>
     */
    public Builder addAllKuaChang(
        java.lang.Iterable<? extends java.lang.Double> values) {
      ensureKuaChangIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, kuaChang_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *构件跨距-龙骨跨距 跨距
     * </pre>
     *
     * <code>repeated double kuaChang = 1;</code>
     */
    public Builder clearKuaChang() {
      kuaChang_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }

    private double girderDistance_ ;
    /**
     * <pre>
     *剖面位置x-肋板间距
     * </pre>
     *
     * <code>double girderDistance = 2;</code>
     */
    public double getGirderDistance() {
      return girderDistance_;
    }
    /**
     * <pre>
     *剖面位置x-肋板间距
     * </pre>
     *
     * <code>double girderDistance = 2;</code>
     */
    public Builder setGirderDistance(double value) {
      
      girderDistance_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *剖面位置x-肋板间距
     * </pre>
     *
     * <code>double girderDistance = 2;</code>
     */
    public Builder clearGirderDistance() {
      
      girderDistance_ = 0D;
      onChanged();
      return this;
    }

    private double frDistance_ ;
    /**
     * <pre>
     *纵骨间距
     * </pre>
     *
     * <code>double frDistance = 3;</code>
     */
    public double getFrDistance() {
      return frDistance_;
    }
    /**
     * <pre>
     *纵骨间距
     * </pre>
     *
     * <code>double frDistance = 3;</code>
     */
    public Builder setFrDistance(double value) {
      
      frDistance_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *纵骨间距
     * </pre>
     *
     * <code>double frDistance = 3;</code>
     */
    public Builder clearFrDistance() {
      
      frDistance_ = 0D;
      onChanged();
      return this;
    }

    private double trusswidth_ ;
    /**
     * <pre>
     *板架宽度 添加614
     * </pre>
     *
     * <code>double trusswidth = 4;</code>
     */
    public double getTrusswidth() {
      return trusswidth_;
    }
    /**
     * <pre>
     *板架宽度 添加614
     * </pre>
     *
     * <code>double trusswidth = 4;</code>
     */
    public Builder setTrusswidth(double value) {
      
      trusswidth_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *板架宽度 添加614
     * </pre>
     *
     * <code>double trusswidth = 4;</code>
     */
    public Builder clearTrusswidth() {
      
      trusswidth_ = 0D;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList frGuige_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureFrGuigeIsMutable() {
      if (!((bitField0_ & 0x00000010) == 0x00000010)) {
        frGuige_ = new com.google.protobuf.LazyStringArrayList(frGuige_);
        bitField0_ |= 0x00000010;
       }
    }
    /**
     * <pre>
     *纵骨规格 每个的规格
     *修改614 double-&gt;string
     * </pre>
     *
     * <code>repeated string frGuige = 5;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getFrGuigeList() {
      return frGuige_.getUnmodifiableView();
    }
    /**
     * <pre>
     *纵骨规格 每个的规格
     *修改614 double-&gt;string
     * </pre>
     *
     * <code>repeated string frGuige = 5;</code>
     */
    public int getFrGuigeCount() {
      return frGuige_.size();
    }
    /**
     * <pre>
     *纵骨规格 每个的规格
     *修改614 double-&gt;string
     * </pre>
     *
     * <code>repeated string frGuige = 5;</code>
     */
    public java.lang.String getFrGuige(int index) {
      return frGuige_.get(index);
    }
    /**
     * <pre>
     *纵骨规格 每个的规格
     *修改614 double-&gt;string
     * </pre>
     *
     * <code>repeated string frGuige = 5;</code>
     */
    public com.google.protobuf.ByteString
        getFrGuigeBytes(int index) {
      return frGuige_.getByteString(index);
    }
    /**
     * <pre>
     *纵骨规格 每个的规格
     *修改614 double-&gt;string
     * </pre>
     *
     * <code>repeated string frGuige = 5;</code>
     */
    public Builder setFrGuige(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureFrGuigeIsMutable();
      frGuige_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *纵骨规格 每个的规格
     *修改614 double-&gt;string
     * </pre>
     *
     * <code>repeated string frGuige = 5;</code>
     */
    public Builder addFrGuige(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureFrGuigeIsMutable();
      frGuige_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *纵骨规格 每个的规格
     *修改614 double-&gt;string
     * </pre>
     *
     * <code>repeated string frGuige = 5;</code>
     */
    public Builder addAllFrGuige(
        java.lang.Iterable<java.lang.String> values) {
      ensureFrGuigeIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, frGuige_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *纵骨规格 每个的规格
     *修改614 double-&gt;string
     * </pre>
     *
     * <code>repeated string frGuige = 5;</code>
     */
    public Builder clearFrGuige() {
      frGuige_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *纵骨规格 每个的规格
     *修改614 double-&gt;string
     * </pre>
     *
     * <code>repeated string frGuige = 5;</code>
     */
    public Builder addFrGuigeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureFrGuigeIsMutable();
      frGuige_.add(value);
      onChanged();
      return this;
    }

    private java.util.List<java.lang.Double> plateThick_ = java.util.Collections.emptyList();
    private void ensurePlateThickIsMutable() {
      if (!((bitField0_ & 0x00000020) == 0x00000020)) {
        plateThick_ = new java.util.ArrayList<java.lang.Double>(plateThick_);
        bitField0_ |= 0x00000020;
       }
    }
    /**
     * <pre>
     *外底板厚 每个板材的厚度
     * </pre>
     *
     * <code>repeated double plateThick = 6;</code>
     */
    public java.util.List<java.lang.Double>
        getPlateThickList() {
      return java.util.Collections.unmodifiableList(plateThick_);
    }
    /**
     * <pre>
     *外底板厚 每个板材的厚度
     * </pre>
     *
     * <code>repeated double plateThick = 6;</code>
     */
    public int getPlateThickCount() {
      return plateThick_.size();
    }
    /**
     * <pre>
     *外底板厚 每个板材的厚度
     * </pre>
     *
     * <code>repeated double plateThick = 6;</code>
     */
    public double getPlateThick(int index) {
      return plateThick_.get(index);
    }
    /**
     * <pre>
     *外底板厚 每个板材的厚度
     * </pre>
     *
     * <code>repeated double plateThick = 6;</code>
     */
    public Builder setPlateThick(
        int index, double value) {
      ensurePlateThickIsMutable();
      plateThick_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *外底板厚 每个板材的厚度
     * </pre>
     *
     * <code>repeated double plateThick = 6;</code>
     */
    public Builder addPlateThick(double value) {
      ensurePlateThickIsMutable();
      plateThick_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *外底板厚 每个板材的厚度
     * </pre>
     *
     * <code>repeated double plateThick = 6;</code>
     */
    public Builder addAllPlateThick(
        java.lang.Iterable<? extends java.lang.Double> values) {
      ensurePlateThickIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, plateThick_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *外底板厚 每个板材的厚度
     * </pre>
     *
     * <code>repeated double plateThick = 6;</code>
     */
    public Builder clearPlateThick() {
      plateThick_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }

    private double deviceWeight_ ;
    /**
     * <pre>
     *设备重量(t)
     * </pre>
     *
     * <code>double deviceWeight = 7;</code>
     */
    public double getDeviceWeight() {
      return deviceWeight_;
    }
    /**
     * <pre>
     *设备重量(t)
     * </pre>
     *
     * <code>double deviceWeight = 7;</code>
     */
    public Builder setDeviceWeight(double value) {
      
      deviceWeight_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *设备重量(t)
     * </pre>
     *
     * <code>double deviceWeight = 7;</code>
     */
    public Builder clearDeviceWeight() {
      
      deviceWeight_ = 0D;
      onChanged();
      return this;
    }

    private java.util.List<java.lang.Double> girderWidth_ = java.util.Collections.emptyList();
    private void ensureGirderWidthIsMutable() {
      if (!((bitField0_ & 0x00000080) == 0x00000080)) {
        girderWidth_ = new java.util.ArrayList<java.lang.Double>(girderWidth_);
        bitField0_ |= 0x00000080;
       }
    }
    /**
     * <pre>
     *外底板宽度 修改614为数组
     * </pre>
     *
     * <code>repeated double girderWidth = 8;</code>
     */
    public java.util.List<java.lang.Double>
        getGirderWidthList() {
      return java.util.Collections.unmodifiableList(girderWidth_);
    }
    /**
     * <pre>
     *外底板宽度 修改614为数组
     * </pre>
     *
     * <code>repeated double girderWidth = 8;</code>
     */
    public int getGirderWidthCount() {
      return girderWidth_.size();
    }
    /**
     * <pre>
     *外底板宽度 修改614为数组
     * </pre>
     *
     * <code>repeated double girderWidth = 8;</code>
     */
    public double getGirderWidth(int index) {
      return girderWidth_.get(index);
    }
    /**
     * <pre>
     *外底板宽度 修改614为数组
     * </pre>
     *
     * <code>repeated double girderWidth = 8;</code>
     */
    public Builder setGirderWidth(
        int index, double value) {
      ensureGirderWidthIsMutable();
      girderWidth_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *外底板宽度 修改614为数组
     * </pre>
     *
     * <code>repeated double girderWidth = 8;</code>
     */
    public Builder addGirderWidth(double value) {
      ensureGirderWidthIsMutable();
      girderWidth_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *外底板宽度 修改614为数组
     * </pre>
     *
     * <code>repeated double girderWidth = 8;</code>
     */
    public Builder addAllGirderWidth(
        java.lang.Iterable<? extends java.lang.Double> values) {
      ensureGirderWidthIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, girderWidth_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *外底板宽度 修改614为数组
     * </pre>
     *
     * <code>repeated double girderWidth = 8;</code>
     */
    public Builder clearGirderWidth() {
      girderWidth_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }

    private double materialYieldLimit_ ;
    /**
     * <pre>
     *new614----------------
     *材料类型 改为材料屈服极限
     * </pre>
     *
     * <code>double materialYieldLimit = 9;</code>
     */
    public double getMaterialYieldLimit() {
      return materialYieldLimit_;
    }
    /**
     * <pre>
     *new614----------------
     *材料类型 改为材料屈服极限
     * </pre>
     *
     * <code>double materialYieldLimit = 9;</code>
     */
    public Builder setMaterialYieldLimit(double value) {
      
      materialYieldLimit_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *new614----------------
     *材料类型 改为材料屈服极限
     * </pre>
     *
     * <code>double materialYieldLimit = 9;</code>
     */
    public Builder clearMaterialYieldLimit() {
      
      materialYieldLimit_ = 0D;
      onChanged();
      return this;
    }

    private boolean isCustomLoad_ ;
    /**
     * <pre>
     *new614----------------
     *是否采用自定义载荷
     * </pre>
     *
     * <code>bool isCustomLoad = 10;</code>
     */
    public boolean getIsCustomLoad() {
      return isCustomLoad_;
    }
    /**
     * <pre>
     *new614----------------
     *是否采用自定义载荷
     * </pre>
     *
     * <code>bool isCustomLoad = 10;</code>
     */
    public Builder setIsCustomLoad(boolean value) {
      
      isCustomLoad_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *new614----------------
     *是否采用自定义载荷
     * </pre>
     *
     * <code>bool isCustomLoad = 10;</code>
     */
    public Builder clearIsCustomLoad() {
      
      isCustomLoad_ = false;
      onChanged();
      return this;
    }

    private double midArchWaveMoment_ ;
    /**
     * <pre>
     **
     * 中拱-波浪弯矩
     * </pre>
     *
     * <code>double midArchWaveMoment = 11;</code>
     */
    public double getMidArchWaveMoment() {
      return midArchWaveMoment_;
    }
    /**
     * <pre>
     **
     * 中拱-波浪弯矩
     * </pre>
     *
     * <code>double midArchWaveMoment = 11;</code>
     */
    public Builder setMidArchWaveMoment(double value) {
      
      midArchWaveMoment_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 中拱-波浪弯矩
     * </pre>
     *
     * <code>double midArchWaveMoment = 11;</code>
     */
    public Builder clearMidArchWaveMoment() {
      
      midArchWaveMoment_ = 0D;
      onChanged();
      return this;
    }

    private double midArchImpactMoment_ ;
    /**
     * <pre>
     **
     * 中拱-砰击弯矩
     * </pre>
     *
     * <code>double midArchImpactMoment = 12;</code>
     */
    public double getMidArchImpactMoment() {
      return midArchImpactMoment_;
    }
    /**
     * <pre>
     **
     * 中拱-砰击弯矩
     * </pre>
     *
     * <code>double midArchImpactMoment = 12;</code>
     */
    public Builder setMidArchImpactMoment(double value) {
      
      midArchImpactMoment_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 中拱-砰击弯矩
     * </pre>
     *
     * <code>double midArchImpactMoment = 12;</code>
     */
    public Builder clearMidArchImpactMoment() {
      
      midArchImpactMoment_ = 0D;
      onChanged();
      return this;
    }

    private double midArchShear_ ;
    /**
     * <pre>
     **
     * 中拱-剪力
     * </pre>
     *
     * <code>double midArchShear = 13;</code>
     */
    public double getMidArchShear() {
      return midArchShear_;
    }
    /**
     * <pre>
     **
     * 中拱-剪力
     * </pre>
     *
     * <code>double midArchShear = 13;</code>
     */
    public Builder setMidArchShear(double value) {
      
      midArchShear_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 中拱-剪力
     * </pre>
     *
     * <code>double midArchShear = 13;</code>
     */
    public Builder clearMidArchShear() {
      
      midArchShear_ = 0D;
      onChanged();
      return this;
    }

    private double midArchDraught_ ;
    /**
     * <pre>
     **添加614
     * 中拱-吃水
     * </pre>
     *
     * <code>double midArchDraught = 14;</code>
     */
    public double getMidArchDraught() {
      return midArchDraught_;
    }
    /**
     * <pre>
     **添加614
     * 中拱-吃水
     * </pre>
     *
     * <code>double midArchDraught = 14;</code>
     */
    public Builder setMidArchDraught(double value) {
      
      midArchDraught_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     **添加614
     * 中拱-吃水
     * </pre>
     *
     * <code>double midArchDraught = 14;</code>
     */
    public Builder clearMidArchDraught() {
      
      midArchDraught_ = 0D;
      onChanged();
      return this;
    }

    private double midVerticalWaveMoment_ ;
    /**
     * <pre>
     **
     * 中垂-波浪弯矩
     * </pre>
     *
     * <code>double midVerticalWaveMoment = 15;</code>
     */
    public double getMidVerticalWaveMoment() {
      return midVerticalWaveMoment_;
    }
    /**
     * <pre>
     **
     * 中垂-波浪弯矩
     * </pre>
     *
     * <code>double midVerticalWaveMoment = 15;</code>
     */
    public Builder setMidVerticalWaveMoment(double value) {
      
      midVerticalWaveMoment_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 中垂-波浪弯矩
     * </pre>
     *
     * <code>double midVerticalWaveMoment = 15;</code>
     */
    public Builder clearMidVerticalWaveMoment() {
      
      midVerticalWaveMoment_ = 0D;
      onChanged();
      return this;
    }

    private double midVerticalImpactMoment_ ;
    /**
     * <pre>
     **
     * 中垂-砰击弯矩
     * </pre>
     *
     * <code>double midVerticalImpactMoment = 16;</code>
     */
    public double getMidVerticalImpactMoment() {
      return midVerticalImpactMoment_;
    }
    /**
     * <pre>
     **
     * 中垂-砰击弯矩
     * </pre>
     *
     * <code>double midVerticalImpactMoment = 16;</code>
     */
    public Builder setMidVerticalImpactMoment(double value) {
      
      midVerticalImpactMoment_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 中垂-砰击弯矩
     * </pre>
     *
     * <code>double midVerticalImpactMoment = 16;</code>
     */
    public Builder clearMidVerticalImpactMoment() {
      
      midVerticalImpactMoment_ = 0D;
      onChanged();
      return this;
    }

    private double midVerticalShear_ ;
    /**
     * <pre>
     **
     * 中垂-剪力
     * </pre>
     *
     * <code>double midVerticalShear = 17;</code>
     */
    public double getMidVerticalShear() {
      return midVerticalShear_;
    }
    /**
     * <pre>
     **
     * 中垂-剪力
     * </pre>
     *
     * <code>double midVerticalShear = 17;</code>
     */
    public Builder setMidVerticalShear(double value) {
      
      midVerticalShear_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 中垂-剪力
     * </pre>
     *
     * <code>double midVerticalShear = 17;</code>
     */
    public Builder clearMidVerticalShear() {
      
      midVerticalShear_ = 0D;
      onChanged();
      return this;
    }

    private double midVerticalDraught_ ;
    /**
     * <pre>
     **添加614
     * 中垂-吃水
     * </pre>
     *
     * <code>double midVerticalDraught = 18;</code>
     */
    public double getMidVerticalDraught() {
      return midVerticalDraught_;
    }
    /**
     * <pre>
     **添加614
     * 中垂-吃水
     * </pre>
     *
     * <code>double midVerticalDraught = 18;</code>
     */
    public Builder setMidVerticalDraught(double value) {
      
      midVerticalDraught_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     **添加614
     * 中垂-吃水
     * </pre>
     *
     * <code>double midVerticalDraught = 18;</code>
     */
    public Builder clearMidVerticalDraught() {
      
      midVerticalDraught_ = 0D;
      onChanged();
      return this;
    }

    private java.util.List<java.lang.Double> xiancethick_ = java.util.Collections.emptyList();
    private void ensureXiancethickIsMutable() {
      if (!((bitField0_ & 0x00040000) == 0x00040000)) {
        xiancethick_ = new java.util.ArrayList<java.lang.Double>(xiancethick_);
        bitField0_ |= 0x00040000;
       }
    }
    /**
     * <pre>
     **添加614
     * 舷侧中和轴附近板的厚度
     * </pre>
     *
     * <code>repeated double xiancethick = 19;</code>
     */
    public java.util.List<java.lang.Double>
        getXiancethickList() {
      return java.util.Collections.unmodifiableList(xiancethick_);
    }
    /**
     * <pre>
     **添加614
     * 舷侧中和轴附近板的厚度
     * </pre>
     *
     * <code>repeated double xiancethick = 19;</code>
     */
    public int getXiancethickCount() {
      return xiancethick_.size();
    }
    /**
     * <pre>
     **添加614
     * 舷侧中和轴附近板的厚度
     * </pre>
     *
     * <code>repeated double xiancethick = 19;</code>
     */
    public double getXiancethick(int index) {
      return xiancethick_.get(index);
    }
    /**
     * <pre>
     **添加614
     * 舷侧中和轴附近板的厚度
     * </pre>
     *
     * <code>repeated double xiancethick = 19;</code>
     */
    public Builder setXiancethick(
        int index, double value) {
      ensureXiancethickIsMutable();
      xiancethick_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     **添加614
     * 舷侧中和轴附近板的厚度
     * </pre>
     *
     * <code>repeated double xiancethick = 19;</code>
     */
    public Builder addXiancethick(double value) {
      ensureXiancethickIsMutable();
      xiancethick_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     **添加614
     * 舷侧中和轴附近板的厚度
     * </pre>
     *
     * <code>repeated double xiancethick = 19;</code>
     */
    public Builder addAllXiancethick(
        java.lang.Iterable<? extends java.lang.Double> values) {
      ensureXiancethickIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, xiancethick_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     **添加614
     * 舷侧中和轴附近板的厚度
     * </pre>
     *
     * <code>repeated double xiancethick = 19;</code>
     */
    public Builder clearXiancethick() {
      xiancethick_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00040000);
      onChanged();
      return this;
    }

    private int numGirder_ ;
    /**
     * <pre>
     *龙骨数量
     * </pre>
     *
     * <code>int32 numGirder = 20;</code>
     */
    public int getNumGirder() {
      return numGirder_;
    }
    /**
     * <pre>
     *龙骨数量
     * </pre>
     *
     * <code>int32 numGirder = 20;</code>
     */
    public Builder setNumGirder(int value) {
      
      numGirder_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *龙骨数量
     * </pre>
     *
     * <code>int32 numGirder = 20;</code>
     */
    public Builder clearNumGirder() {
      
      numGirder_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:com.iscas.biz.calculation.grpc.Sigma1Request)
  }

  // @@protoc_insertion_point(class_scope:com.iscas.biz.calculation.grpc.Sigma1Request)
  private static final com.iscas.biz.calculation.grpc.Sigma1Request DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.iscas.biz.calculation.grpc.Sigma1Request();
  }

  public static com.iscas.biz.calculation.grpc.Sigma1Request getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Sigma1Request>
      PARSER = new com.google.protobuf.AbstractParser<Sigma1Request>() {
    public Sigma1Request parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new Sigma1Request(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Sigma1Request> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Sigma1Request> getParserForType() {
    return PARSER;
  }

  public com.iscas.biz.calculation.grpc.Sigma1Request getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

