// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: calculation.proto

package com.iscas.biz.calculation.grpc;

public interface Sigma4EntityOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.iscas.biz.calculation.grpc.Sigma4Entity)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *中拱支座
   * </pre>
   *
   * <code>double zhonggongZhizuo = 1;</code>
   */
  double getZhonggongZhizuo();

  /**
   * <pre>
   *中拱跨中
   * </pre>
   *
   * <code>double zhonggongKuazhong = 2;</code>
   */
  double getZhonggongKuazhong();

  /**
   * <pre>
   *中垂支座
   * </pre>
   *
   * <code>double zhongchuiZhizuo = 3;</code>
   */
  double getZhongchuiZhizuo();

  /**
   * <pre>
   *中垂跨中
   * </pre>
   *
   * <code>double zhongchuiKuazhong = 4;</code>
   */
  double getZhongchuiKuazhong();

  /**
   * <pre>
   *许用应力
   * </pre>
   *
   * <code>double allowStress = 5;</code>
   */
  double getAllowStress();

  /**
   * <pre>
   *合成许用应力
   * </pre>
   *
   * <code>double combineAllowStress = 6;</code>
   */
  double getCombineAllowStress();

  /**
   * <pre>
   *合成中拱支座上纤维
   * </pre>
   *
   * <code>double combineZhonggongZhizuoUp = 7;</code>
   */
  double getCombineZhonggongZhizuoUp();

  /**
   * <pre>
   *合成中拱支座下纤维
   * </pre>
   *
   * <code>double combineZhonggongZhizuoDown = 8;</code>
   */
  double getCombineZhonggongZhizuoDown();

  /**
   * <pre>
   *合成中拱跨中上纤维
   * </pre>
   *
   * <code>double combineZhonggongKuazhongUp = 9;</code>
   */
  double getCombineZhonggongKuazhongUp();

  /**
   * <pre>
   *合成中拱支座下纤维
   * </pre>
   *
   * <code>double combineZhonggongKuazhongDown = 10;</code>
   */
  double getCombineZhonggongKuazhongDown();

  /**
   * <pre>
   *合成中垂支座上纤维
   * </pre>
   *
   * <code>double combineZhongchuiZhizuoUp = 11;</code>
   */
  double getCombineZhongchuiZhizuoUp();

  /**
   * <pre>
   *合成中拱支座下纤维
   * </pre>
   *
   * <code>double combineZhongchuiZhizuoDown = 12;</code>
   */
  double getCombineZhongchuiZhizuoDown();

  /**
   * <pre>
   *合成中垂跨中上纤维
   * </pre>
   *
   * <code>double combineZhongchuiKuazhongUp = 13;</code>
   */
  double getCombineZhongchuiKuazhongUp();

  /**
   * <pre>
   *合成中拱支座下纤维
   * </pre>
   *
   * <code>double combineZhongchuiKuazhongDown = 14;</code>
   */
  double getCombineZhongchuiKuazhongDown();
}
