// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: calculation.proto

package com.iscas.biz.calculation.grpc;

/**
 * Protobuf type {@code com.iscas.biz.calculation.grpc.Sigma2Entity}
 */
public  final class Sigma2Entity extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.iscas.biz.calculation.grpc.Sigma2Entity)
    Sigma2EntityOrBuilder {
  // Use Sigma2Entity.newBuilder() to construct.
  private Sigma2Entity(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Sigma2Entity() {
    zhonggongZhizuoShang_ = 0D;
    zhonggongZhizuoXia_ = 0D;
    zhonggongKuazhongShang_ = 0D;
    zhonggongKuazhongXia_ = 0D;
    zhongchuiZhizuoShang_ = 0D;
    zhongchuiZhizuoXia_ = 0D;
    zhongchuiKuazhongShang_ = 0D;
    zhongchuiKuazhongXia_ = 0D;
    combineZhonggongZhizuoShang_ = 0D;
    combineZhonggongZhizuoXia_ = 0D;
    combineZhonggongKuazhongShang_ = 0D;
    combineZhonggongKuazhongXia_ = 0D;
    combineZhongchuiZhizuoShang_ = 0D;
    combineZhongchuiZhizuoXia_ = 0D;
    combineZhongchuiKuazhongShang_ = 0D;
    combineZhongchuiKuazhongXia_ = 0D;
    combineAllowStress_ = 0D;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private Sigma2Entity(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 9: {

            zhonggongZhizuoShang_ = input.readDouble();
            break;
          }
          case 17: {

            zhonggongZhizuoXia_ = input.readDouble();
            break;
          }
          case 25: {

            zhonggongKuazhongShang_ = input.readDouble();
            break;
          }
          case 33: {

            zhonggongKuazhongXia_ = input.readDouble();
            break;
          }
          case 41: {

            zhongchuiZhizuoShang_ = input.readDouble();
            break;
          }
          case 49: {

            zhongchuiZhizuoXia_ = input.readDouble();
            break;
          }
          case 57: {

            zhongchuiKuazhongShang_ = input.readDouble();
            break;
          }
          case 65: {

            zhongchuiKuazhongXia_ = input.readDouble();
            break;
          }
          case 73: {

            combineZhonggongZhizuoShang_ = input.readDouble();
            break;
          }
          case 81: {

            combineZhonggongZhizuoXia_ = input.readDouble();
            break;
          }
          case 89: {

            combineZhonggongKuazhongShang_ = input.readDouble();
            break;
          }
          case 97: {

            combineZhonggongKuazhongXia_ = input.readDouble();
            break;
          }
          case 105: {

            combineZhongchuiZhizuoShang_ = input.readDouble();
            break;
          }
          case 113: {

            combineZhongchuiZhizuoXia_ = input.readDouble();
            break;
          }
          case 121: {

            combineZhongchuiKuazhongShang_ = input.readDouble();
            break;
          }
          case 129: {

            combineZhongchuiKuazhongXia_ = input.readDouble();
            break;
          }
          case 137: {

            combineAllowStress_ = input.readDouble();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.iscas.biz.calculation.grpc.CalculationProto.internal_static_com_iscas_biz_calculation_grpc_Sigma2Entity_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.iscas.biz.calculation.grpc.CalculationProto.internal_static_com_iscas_biz_calculation_grpc_Sigma2Entity_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.iscas.biz.calculation.grpc.Sigma2Entity.class, com.iscas.biz.calculation.grpc.Sigma2Entity.Builder.class);
  }

  public static final int ZHONGGONGZHIZUOSHANG_FIELD_NUMBER = 1;
  private double zhonggongZhizuoShang_;
  /**
   * <pre>
   *中拱支座上纤维
   * </pre>
   *
   * <code>double zhonggongZhizuoShang = 1;</code>
   */
  public double getZhonggongZhizuoShang() {
    return zhonggongZhizuoShang_;
  }

  public static final int ZHONGGONGZHIZUOXIA_FIELD_NUMBER = 2;
  private double zhonggongZhizuoXia_;
  /**
   * <pre>
   *中拱支座下纤维
   * </pre>
   *
   * <code>double zhonggongZhizuoXia = 2;</code>
   */
  public double getZhonggongZhizuoXia() {
    return zhonggongZhizuoXia_;
  }

  public static final int ZHONGGONGKUAZHONGSHANG_FIELD_NUMBER = 3;
  private double zhonggongKuazhongShang_;
  /**
   * <pre>
   *中拱跨中上纤维
   * </pre>
   *
   * <code>double zhonggongKuazhongShang = 3;</code>
   */
  public double getZhonggongKuazhongShang() {
    return zhonggongKuazhongShang_;
  }

  public static final int ZHONGGONGKUAZHONGXIA_FIELD_NUMBER = 4;
  private double zhonggongKuazhongXia_;
  /**
   * <pre>
   *中拱跨中下纤维
   * </pre>
   *
   * <code>double zhonggongKuazhongXia = 4;</code>
   */
  public double getZhonggongKuazhongXia() {
    return zhonggongKuazhongXia_;
  }

  public static final int ZHONGCHUIZHIZUOSHANG_FIELD_NUMBER = 5;
  private double zhongchuiZhizuoShang_;
  /**
   * <pre>
   *中垂支座上纤维
   * </pre>
   *
   * <code>double zhongchuiZhizuoShang = 5;</code>
   */
  public double getZhongchuiZhizuoShang() {
    return zhongchuiZhizuoShang_;
  }

  public static final int ZHONGCHUIZHIZUOXIA_FIELD_NUMBER = 6;
  private double zhongchuiZhizuoXia_;
  /**
   * <pre>
   *中垂支座下纤维
   * </pre>
   *
   * <code>double zhongchuiZhizuoXia = 6;</code>
   */
  public double getZhongchuiZhizuoXia() {
    return zhongchuiZhizuoXia_;
  }

  public static final int ZHONGCHUIKUAZHONGSHANG_FIELD_NUMBER = 7;
  private double zhongchuiKuazhongShang_;
  /**
   * <pre>
   *中垂跨中上纤维
   * </pre>
   *
   * <code>double zhongchuiKuazhongShang = 7;</code>
   */
  public double getZhongchuiKuazhongShang() {
    return zhongchuiKuazhongShang_;
  }

  public static final int ZHONGCHUIKUAZHONGXIA_FIELD_NUMBER = 8;
  private double zhongchuiKuazhongXia_;
  /**
   * <pre>
   *中垂跨中下纤维
   * </pre>
   *
   * <code>double zhongchuiKuazhongXia = 8;</code>
   */
  public double getZhongchuiKuazhongXia() {
    return zhongchuiKuazhongXia_;
  }

  public static final int COMBINEZHONGGONGZHIZUOSHANG_FIELD_NUMBER = 9;
  private double combineZhonggongZhizuoShang_;
  /**
   * <pre>
   *合成中拱支座上纤维
   * </pre>
   *
   * <code>double combineZhonggongZhizuoShang = 9;</code>
   */
  public double getCombineZhonggongZhizuoShang() {
    return combineZhonggongZhizuoShang_;
  }

  public static final int COMBINEZHONGGONGZHIZUOXIA_FIELD_NUMBER = 10;
  private double combineZhonggongZhizuoXia_;
  /**
   * <pre>
   *合成中拱支座下纤维
   * </pre>
   *
   * <code>double combineZhonggongZhizuoXia = 10;</code>
   */
  public double getCombineZhonggongZhizuoXia() {
    return combineZhonggongZhizuoXia_;
  }

  public static final int COMBINEZHONGGONGKUAZHONGSHANG_FIELD_NUMBER = 11;
  private double combineZhonggongKuazhongShang_;
  /**
   * <pre>
   *合成中拱跨中上纤维
   * </pre>
   *
   * <code>double combineZhonggongKuazhongShang = 11;</code>
   */
  public double getCombineZhonggongKuazhongShang() {
    return combineZhonggongKuazhongShang_;
  }

  public static final int COMBINEZHONGGONGKUAZHONGXIA_FIELD_NUMBER = 12;
  private double combineZhonggongKuazhongXia_;
  /**
   * <pre>
   *合成中拱跨中下纤维
   * </pre>
   *
   * <code>double combineZhonggongKuazhongXia = 12;</code>
   */
  public double getCombineZhonggongKuazhongXia() {
    return combineZhonggongKuazhongXia_;
  }

  public static final int COMBINEZHONGCHUIZHIZUOSHANG_FIELD_NUMBER = 13;
  private double combineZhongchuiZhizuoShang_;
  /**
   * <pre>
   *合成中垂支座上纤维
   * </pre>
   *
   * <code>double combineZhongchuiZhizuoShang = 13;</code>
   */
  public double getCombineZhongchuiZhizuoShang() {
    return combineZhongchuiZhizuoShang_;
  }

  public static final int COMBINEZHONGCHUIZHIZUOXIA_FIELD_NUMBER = 14;
  private double combineZhongchuiZhizuoXia_;
  /**
   * <pre>
   *合成中垂支座下纤维
   * </pre>
   *
   * <code>double combineZhongchuiZhizuoXia = 14;</code>
   */
  public double getCombineZhongchuiZhizuoXia() {
    return combineZhongchuiZhizuoXia_;
  }

  public static final int COMBINEZHONGCHUIKUAZHONGSHANG_FIELD_NUMBER = 15;
  private double combineZhongchuiKuazhongShang_;
  /**
   * <pre>
   *合成中垂跨中上纤维
   * </pre>
   *
   * <code>double combineZhongchuiKuazhongShang = 15;</code>
   */
  public double getCombineZhongchuiKuazhongShang() {
    return combineZhongchuiKuazhongShang_;
  }

  public static final int COMBINEZHONGCHUIKUAZHONGXIA_FIELD_NUMBER = 16;
  private double combineZhongchuiKuazhongXia_;
  /**
   * <pre>
   *合成中垂跨中下纤维
   * </pre>
   *
   * <code>double combineZhongchuiKuazhongXia = 16;</code>
   */
  public double getCombineZhongchuiKuazhongXia() {
    return combineZhongchuiKuazhongXia_;
  }

  public static final int COMBINEALLOWSTRESS_FIELD_NUMBER = 17;
  private double combineAllowStress_;
  /**
   * <pre>
   *合成许用应力
   * </pre>
   *
   * <code>double combineAllowStress = 17;</code>
   */
  public double getCombineAllowStress() {
    return combineAllowStress_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (zhonggongZhizuoShang_ != 0D) {
      output.writeDouble(1, zhonggongZhizuoShang_);
    }
    if (zhonggongZhizuoXia_ != 0D) {
      output.writeDouble(2, zhonggongZhizuoXia_);
    }
    if (zhonggongKuazhongShang_ != 0D) {
      output.writeDouble(3, zhonggongKuazhongShang_);
    }
    if (zhonggongKuazhongXia_ != 0D) {
      output.writeDouble(4, zhonggongKuazhongXia_);
    }
    if (zhongchuiZhizuoShang_ != 0D) {
      output.writeDouble(5, zhongchuiZhizuoShang_);
    }
    if (zhongchuiZhizuoXia_ != 0D) {
      output.writeDouble(6, zhongchuiZhizuoXia_);
    }
    if (zhongchuiKuazhongShang_ != 0D) {
      output.writeDouble(7, zhongchuiKuazhongShang_);
    }
    if (zhongchuiKuazhongXia_ != 0D) {
      output.writeDouble(8, zhongchuiKuazhongXia_);
    }
    if (combineZhonggongZhizuoShang_ != 0D) {
      output.writeDouble(9, combineZhonggongZhizuoShang_);
    }
    if (combineZhonggongZhizuoXia_ != 0D) {
      output.writeDouble(10, combineZhonggongZhizuoXia_);
    }
    if (combineZhonggongKuazhongShang_ != 0D) {
      output.writeDouble(11, combineZhonggongKuazhongShang_);
    }
    if (combineZhonggongKuazhongXia_ != 0D) {
      output.writeDouble(12, combineZhonggongKuazhongXia_);
    }
    if (combineZhongchuiZhizuoShang_ != 0D) {
      output.writeDouble(13, combineZhongchuiZhizuoShang_);
    }
    if (combineZhongchuiZhizuoXia_ != 0D) {
      output.writeDouble(14, combineZhongchuiZhizuoXia_);
    }
    if (combineZhongchuiKuazhongShang_ != 0D) {
      output.writeDouble(15, combineZhongchuiKuazhongShang_);
    }
    if (combineZhongchuiKuazhongXia_ != 0D) {
      output.writeDouble(16, combineZhongchuiKuazhongXia_);
    }
    if (combineAllowStress_ != 0D) {
      output.writeDouble(17, combineAllowStress_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (zhonggongZhizuoShang_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(1, zhonggongZhizuoShang_);
    }
    if (zhonggongZhizuoXia_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, zhonggongZhizuoXia_);
    }
    if (zhonggongKuazhongShang_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(3, zhonggongKuazhongShang_);
    }
    if (zhonggongKuazhongXia_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(4, zhonggongKuazhongXia_);
    }
    if (zhongchuiZhizuoShang_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(5, zhongchuiZhizuoShang_);
    }
    if (zhongchuiZhizuoXia_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(6, zhongchuiZhizuoXia_);
    }
    if (zhongchuiKuazhongShang_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(7, zhongchuiKuazhongShang_);
    }
    if (zhongchuiKuazhongXia_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(8, zhongchuiKuazhongXia_);
    }
    if (combineZhonggongZhizuoShang_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(9, combineZhonggongZhizuoShang_);
    }
    if (combineZhonggongZhizuoXia_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(10, combineZhonggongZhizuoXia_);
    }
    if (combineZhonggongKuazhongShang_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(11, combineZhonggongKuazhongShang_);
    }
    if (combineZhonggongKuazhongXia_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(12, combineZhonggongKuazhongXia_);
    }
    if (combineZhongchuiZhizuoShang_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(13, combineZhongchuiZhizuoShang_);
    }
    if (combineZhongchuiZhizuoXia_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(14, combineZhongchuiZhizuoXia_);
    }
    if (combineZhongchuiKuazhongShang_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(15, combineZhongchuiKuazhongShang_);
    }
    if (combineZhongchuiKuazhongXia_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(16, combineZhongchuiKuazhongXia_);
    }
    if (combineAllowStress_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(17, combineAllowStress_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.iscas.biz.calculation.grpc.Sigma2Entity)) {
      return super.equals(obj);
    }
    com.iscas.biz.calculation.grpc.Sigma2Entity other = (com.iscas.biz.calculation.grpc.Sigma2Entity) obj;

    boolean result = true;
    result = result && (
        java.lang.Double.doubleToLongBits(getZhonggongZhizuoShang())
        == java.lang.Double.doubleToLongBits(
            other.getZhonggongZhizuoShang()));
    result = result && (
        java.lang.Double.doubleToLongBits(getZhonggongZhizuoXia())
        == java.lang.Double.doubleToLongBits(
            other.getZhonggongZhizuoXia()));
    result = result && (
        java.lang.Double.doubleToLongBits(getZhonggongKuazhongShang())
        == java.lang.Double.doubleToLongBits(
            other.getZhonggongKuazhongShang()));
    result = result && (
        java.lang.Double.doubleToLongBits(getZhonggongKuazhongXia())
        == java.lang.Double.doubleToLongBits(
            other.getZhonggongKuazhongXia()));
    result = result && (
        java.lang.Double.doubleToLongBits(getZhongchuiZhizuoShang())
        == java.lang.Double.doubleToLongBits(
            other.getZhongchuiZhizuoShang()));
    result = result && (
        java.lang.Double.doubleToLongBits(getZhongchuiZhizuoXia())
        == java.lang.Double.doubleToLongBits(
            other.getZhongchuiZhizuoXia()));
    result = result && (
        java.lang.Double.doubleToLongBits(getZhongchuiKuazhongShang())
        == java.lang.Double.doubleToLongBits(
            other.getZhongchuiKuazhongShang()));
    result = result && (
        java.lang.Double.doubleToLongBits(getZhongchuiKuazhongXia())
        == java.lang.Double.doubleToLongBits(
            other.getZhongchuiKuazhongXia()));
    result = result && (
        java.lang.Double.doubleToLongBits(getCombineZhonggongZhizuoShang())
        == java.lang.Double.doubleToLongBits(
            other.getCombineZhonggongZhizuoShang()));
    result = result && (
        java.lang.Double.doubleToLongBits(getCombineZhonggongZhizuoXia())
        == java.lang.Double.doubleToLongBits(
            other.getCombineZhonggongZhizuoXia()));
    result = result && (
        java.lang.Double.doubleToLongBits(getCombineZhonggongKuazhongShang())
        == java.lang.Double.doubleToLongBits(
            other.getCombineZhonggongKuazhongShang()));
    result = result && (
        java.lang.Double.doubleToLongBits(getCombineZhonggongKuazhongXia())
        == java.lang.Double.doubleToLongBits(
            other.getCombineZhonggongKuazhongXia()));
    result = result && (
        java.lang.Double.doubleToLongBits(getCombineZhongchuiZhizuoShang())
        == java.lang.Double.doubleToLongBits(
            other.getCombineZhongchuiZhizuoShang()));
    result = result && (
        java.lang.Double.doubleToLongBits(getCombineZhongchuiZhizuoXia())
        == java.lang.Double.doubleToLongBits(
            other.getCombineZhongchuiZhizuoXia()));
    result = result && (
        java.lang.Double.doubleToLongBits(getCombineZhongchuiKuazhongShang())
        == java.lang.Double.doubleToLongBits(
            other.getCombineZhongchuiKuazhongShang()));
    result = result && (
        java.lang.Double.doubleToLongBits(getCombineZhongchuiKuazhongXia())
        == java.lang.Double.doubleToLongBits(
            other.getCombineZhongchuiKuazhongXia()));
    result = result && (
        java.lang.Double.doubleToLongBits(getCombineAllowStress())
        == java.lang.Double.doubleToLongBits(
            other.getCombineAllowStress()));
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ZHONGGONGZHIZUOSHANG_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getZhonggongZhizuoShang()));
    hash = (37 * hash) + ZHONGGONGZHIZUOXIA_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getZhonggongZhizuoXia()));
    hash = (37 * hash) + ZHONGGONGKUAZHONGSHANG_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getZhonggongKuazhongShang()));
    hash = (37 * hash) + ZHONGGONGKUAZHONGXIA_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getZhonggongKuazhongXia()));
    hash = (37 * hash) + ZHONGCHUIZHIZUOSHANG_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getZhongchuiZhizuoShang()));
    hash = (37 * hash) + ZHONGCHUIZHIZUOXIA_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getZhongchuiZhizuoXia()));
    hash = (37 * hash) + ZHONGCHUIKUAZHONGSHANG_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getZhongchuiKuazhongShang()));
    hash = (37 * hash) + ZHONGCHUIKUAZHONGXIA_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getZhongchuiKuazhongXia()));
    hash = (37 * hash) + COMBINEZHONGGONGZHIZUOSHANG_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getCombineZhonggongZhizuoShang()));
    hash = (37 * hash) + COMBINEZHONGGONGZHIZUOXIA_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getCombineZhonggongZhizuoXia()));
    hash = (37 * hash) + COMBINEZHONGGONGKUAZHONGSHANG_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getCombineZhonggongKuazhongShang()));
    hash = (37 * hash) + COMBINEZHONGGONGKUAZHONGXIA_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getCombineZhonggongKuazhongXia()));
    hash = (37 * hash) + COMBINEZHONGCHUIZHIZUOSHANG_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getCombineZhongchuiZhizuoShang()));
    hash = (37 * hash) + COMBINEZHONGCHUIZHIZUOXIA_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getCombineZhongchuiZhizuoXia()));
    hash = (37 * hash) + COMBINEZHONGCHUIKUAZHONGSHANG_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getCombineZhongchuiKuazhongShang()));
    hash = (37 * hash) + COMBINEZHONGCHUIKUAZHONGXIA_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getCombineZhongchuiKuazhongXia()));
    hash = (37 * hash) + COMBINEALLOWSTRESS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getCombineAllowStress()));
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.iscas.biz.calculation.grpc.Sigma2Entity parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.iscas.biz.calculation.grpc.Sigma2Entity parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.iscas.biz.calculation.grpc.Sigma2Entity parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.iscas.biz.calculation.grpc.Sigma2Entity parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.iscas.biz.calculation.grpc.Sigma2Entity parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.iscas.biz.calculation.grpc.Sigma2Entity parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.iscas.biz.calculation.grpc.Sigma2Entity parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.iscas.biz.calculation.grpc.Sigma2Entity parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.iscas.biz.calculation.grpc.Sigma2Entity parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.iscas.biz.calculation.grpc.Sigma2Entity parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.iscas.biz.calculation.grpc.Sigma2Entity prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.iscas.biz.calculation.grpc.Sigma2Entity}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.iscas.biz.calculation.grpc.Sigma2Entity)
      com.iscas.biz.calculation.grpc.Sigma2EntityOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.iscas.biz.calculation.grpc.CalculationProto.internal_static_com_iscas_biz_calculation_grpc_Sigma2Entity_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.iscas.biz.calculation.grpc.CalculationProto.internal_static_com_iscas_biz_calculation_grpc_Sigma2Entity_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.iscas.biz.calculation.grpc.Sigma2Entity.class, com.iscas.biz.calculation.grpc.Sigma2Entity.Builder.class);
    }

    // Construct using com.iscas.biz.calculation.grpc.Sigma2Entity.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      zhonggongZhizuoShang_ = 0D;

      zhonggongZhizuoXia_ = 0D;

      zhonggongKuazhongShang_ = 0D;

      zhonggongKuazhongXia_ = 0D;

      zhongchuiZhizuoShang_ = 0D;

      zhongchuiZhizuoXia_ = 0D;

      zhongchuiKuazhongShang_ = 0D;

      zhongchuiKuazhongXia_ = 0D;

      combineZhonggongZhizuoShang_ = 0D;

      combineZhonggongZhizuoXia_ = 0D;

      combineZhonggongKuazhongShang_ = 0D;

      combineZhonggongKuazhongXia_ = 0D;

      combineZhongchuiZhizuoShang_ = 0D;

      combineZhongchuiZhizuoXia_ = 0D;

      combineZhongchuiKuazhongShang_ = 0D;

      combineZhongchuiKuazhongXia_ = 0D;

      combineAllowStress_ = 0D;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.iscas.biz.calculation.grpc.CalculationProto.internal_static_com_iscas_biz_calculation_grpc_Sigma2Entity_descriptor;
    }

    public com.iscas.biz.calculation.grpc.Sigma2Entity getDefaultInstanceForType() {
      return com.iscas.biz.calculation.grpc.Sigma2Entity.getDefaultInstance();
    }

    public com.iscas.biz.calculation.grpc.Sigma2Entity build() {
      com.iscas.biz.calculation.grpc.Sigma2Entity result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.iscas.biz.calculation.grpc.Sigma2Entity buildPartial() {
      com.iscas.biz.calculation.grpc.Sigma2Entity result = new com.iscas.biz.calculation.grpc.Sigma2Entity(this);
      result.zhonggongZhizuoShang_ = zhonggongZhizuoShang_;
      result.zhonggongZhizuoXia_ = zhonggongZhizuoXia_;
      result.zhonggongKuazhongShang_ = zhonggongKuazhongShang_;
      result.zhonggongKuazhongXia_ = zhonggongKuazhongXia_;
      result.zhongchuiZhizuoShang_ = zhongchuiZhizuoShang_;
      result.zhongchuiZhizuoXia_ = zhongchuiZhizuoXia_;
      result.zhongchuiKuazhongShang_ = zhongchuiKuazhongShang_;
      result.zhongchuiKuazhongXia_ = zhongchuiKuazhongXia_;
      result.combineZhonggongZhizuoShang_ = combineZhonggongZhizuoShang_;
      result.combineZhonggongZhizuoXia_ = combineZhonggongZhizuoXia_;
      result.combineZhonggongKuazhongShang_ = combineZhonggongKuazhongShang_;
      result.combineZhonggongKuazhongXia_ = combineZhonggongKuazhongXia_;
      result.combineZhongchuiZhizuoShang_ = combineZhongchuiZhizuoShang_;
      result.combineZhongchuiZhizuoXia_ = combineZhongchuiZhizuoXia_;
      result.combineZhongchuiKuazhongShang_ = combineZhongchuiKuazhongShang_;
      result.combineZhongchuiKuazhongXia_ = combineZhongchuiKuazhongXia_;
      result.combineAllowStress_ = combineAllowStress_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.iscas.biz.calculation.grpc.Sigma2Entity) {
        return mergeFrom((com.iscas.biz.calculation.grpc.Sigma2Entity)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.iscas.biz.calculation.grpc.Sigma2Entity other) {
      if (other == com.iscas.biz.calculation.grpc.Sigma2Entity.getDefaultInstance()) return this;
      if (other.getZhonggongZhizuoShang() != 0D) {
        setZhonggongZhizuoShang(other.getZhonggongZhizuoShang());
      }
      if (other.getZhonggongZhizuoXia() != 0D) {
        setZhonggongZhizuoXia(other.getZhonggongZhizuoXia());
      }
      if (other.getZhonggongKuazhongShang() != 0D) {
        setZhonggongKuazhongShang(other.getZhonggongKuazhongShang());
      }
      if (other.getZhonggongKuazhongXia() != 0D) {
        setZhonggongKuazhongXia(other.getZhonggongKuazhongXia());
      }
      if (other.getZhongchuiZhizuoShang() != 0D) {
        setZhongchuiZhizuoShang(other.getZhongchuiZhizuoShang());
      }
      if (other.getZhongchuiZhizuoXia() != 0D) {
        setZhongchuiZhizuoXia(other.getZhongchuiZhizuoXia());
      }
      if (other.getZhongchuiKuazhongShang() != 0D) {
        setZhongchuiKuazhongShang(other.getZhongchuiKuazhongShang());
      }
      if (other.getZhongchuiKuazhongXia() != 0D) {
        setZhongchuiKuazhongXia(other.getZhongchuiKuazhongXia());
      }
      if (other.getCombineZhonggongZhizuoShang() != 0D) {
        setCombineZhonggongZhizuoShang(other.getCombineZhonggongZhizuoShang());
      }
      if (other.getCombineZhonggongZhizuoXia() != 0D) {
        setCombineZhonggongZhizuoXia(other.getCombineZhonggongZhizuoXia());
      }
      if (other.getCombineZhonggongKuazhongShang() != 0D) {
        setCombineZhonggongKuazhongShang(other.getCombineZhonggongKuazhongShang());
      }
      if (other.getCombineZhonggongKuazhongXia() != 0D) {
        setCombineZhonggongKuazhongXia(other.getCombineZhonggongKuazhongXia());
      }
      if (other.getCombineZhongchuiZhizuoShang() != 0D) {
        setCombineZhongchuiZhizuoShang(other.getCombineZhongchuiZhizuoShang());
      }
      if (other.getCombineZhongchuiZhizuoXia() != 0D) {
        setCombineZhongchuiZhizuoXia(other.getCombineZhongchuiZhizuoXia());
      }
      if (other.getCombineZhongchuiKuazhongShang() != 0D) {
        setCombineZhongchuiKuazhongShang(other.getCombineZhongchuiKuazhongShang());
      }
      if (other.getCombineZhongchuiKuazhongXia() != 0D) {
        setCombineZhongchuiKuazhongXia(other.getCombineZhongchuiKuazhongXia());
      }
      if (other.getCombineAllowStress() != 0D) {
        setCombineAllowStress(other.getCombineAllowStress());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.iscas.biz.calculation.grpc.Sigma2Entity parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.iscas.biz.calculation.grpc.Sigma2Entity) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private double zhonggongZhizuoShang_ ;
    /**
     * <pre>
     *中拱支座上纤维
     * </pre>
     *
     * <code>double zhonggongZhizuoShang = 1;</code>
     */
    public double getZhonggongZhizuoShang() {
      return zhonggongZhizuoShang_;
    }
    /**
     * <pre>
     *中拱支座上纤维
     * </pre>
     *
     * <code>double zhonggongZhizuoShang = 1;</code>
     */
    public Builder setZhonggongZhizuoShang(double value) {
      
      zhonggongZhizuoShang_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *中拱支座上纤维
     * </pre>
     *
     * <code>double zhonggongZhizuoShang = 1;</code>
     */
    public Builder clearZhonggongZhizuoShang() {
      
      zhonggongZhizuoShang_ = 0D;
      onChanged();
      return this;
    }

    private double zhonggongZhizuoXia_ ;
    /**
     * <pre>
     *中拱支座下纤维
     * </pre>
     *
     * <code>double zhonggongZhizuoXia = 2;</code>
     */
    public double getZhonggongZhizuoXia() {
      return zhonggongZhizuoXia_;
    }
    /**
     * <pre>
     *中拱支座下纤维
     * </pre>
     *
     * <code>double zhonggongZhizuoXia = 2;</code>
     */
    public Builder setZhonggongZhizuoXia(double value) {
      
      zhonggongZhizuoXia_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *中拱支座下纤维
     * </pre>
     *
     * <code>double zhonggongZhizuoXia = 2;</code>
     */
    public Builder clearZhonggongZhizuoXia() {
      
      zhonggongZhizuoXia_ = 0D;
      onChanged();
      return this;
    }

    private double zhonggongKuazhongShang_ ;
    /**
     * <pre>
     *中拱跨中上纤维
     * </pre>
     *
     * <code>double zhonggongKuazhongShang = 3;</code>
     */
    public double getZhonggongKuazhongShang() {
      return zhonggongKuazhongShang_;
    }
    /**
     * <pre>
     *中拱跨中上纤维
     * </pre>
     *
     * <code>double zhonggongKuazhongShang = 3;</code>
     */
    public Builder setZhonggongKuazhongShang(double value) {
      
      zhonggongKuazhongShang_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *中拱跨中上纤维
     * </pre>
     *
     * <code>double zhonggongKuazhongShang = 3;</code>
     */
    public Builder clearZhonggongKuazhongShang() {
      
      zhonggongKuazhongShang_ = 0D;
      onChanged();
      return this;
    }

    private double zhonggongKuazhongXia_ ;
    /**
     * <pre>
     *中拱跨中下纤维
     * </pre>
     *
     * <code>double zhonggongKuazhongXia = 4;</code>
     */
    public double getZhonggongKuazhongXia() {
      return zhonggongKuazhongXia_;
    }
    /**
     * <pre>
     *中拱跨中下纤维
     * </pre>
     *
     * <code>double zhonggongKuazhongXia = 4;</code>
     */
    public Builder setZhonggongKuazhongXia(double value) {
      
      zhonggongKuazhongXia_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *中拱跨中下纤维
     * </pre>
     *
     * <code>double zhonggongKuazhongXia = 4;</code>
     */
    public Builder clearZhonggongKuazhongXia() {
      
      zhonggongKuazhongXia_ = 0D;
      onChanged();
      return this;
    }

    private double zhongchuiZhizuoShang_ ;
    /**
     * <pre>
     *中垂支座上纤维
     * </pre>
     *
     * <code>double zhongchuiZhizuoShang = 5;</code>
     */
    public double getZhongchuiZhizuoShang() {
      return zhongchuiZhizuoShang_;
    }
    /**
     * <pre>
     *中垂支座上纤维
     * </pre>
     *
     * <code>double zhongchuiZhizuoShang = 5;</code>
     */
    public Builder setZhongchuiZhizuoShang(double value) {
      
      zhongchuiZhizuoShang_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *中垂支座上纤维
     * </pre>
     *
     * <code>double zhongchuiZhizuoShang = 5;</code>
     */
    public Builder clearZhongchuiZhizuoShang() {
      
      zhongchuiZhizuoShang_ = 0D;
      onChanged();
      return this;
    }

    private double zhongchuiZhizuoXia_ ;
    /**
     * <pre>
     *中垂支座下纤维
     * </pre>
     *
     * <code>double zhongchuiZhizuoXia = 6;</code>
     */
    public double getZhongchuiZhizuoXia() {
      return zhongchuiZhizuoXia_;
    }
    /**
     * <pre>
     *中垂支座下纤维
     * </pre>
     *
     * <code>double zhongchuiZhizuoXia = 6;</code>
     */
    public Builder setZhongchuiZhizuoXia(double value) {
      
      zhongchuiZhizuoXia_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *中垂支座下纤维
     * </pre>
     *
     * <code>double zhongchuiZhizuoXia = 6;</code>
     */
    public Builder clearZhongchuiZhizuoXia() {
      
      zhongchuiZhizuoXia_ = 0D;
      onChanged();
      return this;
    }

    private double zhongchuiKuazhongShang_ ;
    /**
     * <pre>
     *中垂跨中上纤维
     * </pre>
     *
     * <code>double zhongchuiKuazhongShang = 7;</code>
     */
    public double getZhongchuiKuazhongShang() {
      return zhongchuiKuazhongShang_;
    }
    /**
     * <pre>
     *中垂跨中上纤维
     * </pre>
     *
     * <code>double zhongchuiKuazhongShang = 7;</code>
     */
    public Builder setZhongchuiKuazhongShang(double value) {
      
      zhongchuiKuazhongShang_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *中垂跨中上纤维
     * </pre>
     *
     * <code>double zhongchuiKuazhongShang = 7;</code>
     */
    public Builder clearZhongchuiKuazhongShang() {
      
      zhongchuiKuazhongShang_ = 0D;
      onChanged();
      return this;
    }

    private double zhongchuiKuazhongXia_ ;
    /**
     * <pre>
     *中垂跨中下纤维
     * </pre>
     *
     * <code>double zhongchuiKuazhongXia = 8;</code>
     */
    public double getZhongchuiKuazhongXia() {
      return zhongchuiKuazhongXia_;
    }
    /**
     * <pre>
     *中垂跨中下纤维
     * </pre>
     *
     * <code>double zhongchuiKuazhongXia = 8;</code>
     */
    public Builder setZhongchuiKuazhongXia(double value) {
      
      zhongchuiKuazhongXia_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *中垂跨中下纤维
     * </pre>
     *
     * <code>double zhongchuiKuazhongXia = 8;</code>
     */
    public Builder clearZhongchuiKuazhongXia() {
      
      zhongchuiKuazhongXia_ = 0D;
      onChanged();
      return this;
    }

    private double combineZhonggongZhizuoShang_ ;
    /**
     * <pre>
     *合成中拱支座上纤维
     * </pre>
     *
     * <code>double combineZhonggongZhizuoShang = 9;</code>
     */
    public double getCombineZhonggongZhizuoShang() {
      return combineZhonggongZhizuoShang_;
    }
    /**
     * <pre>
     *合成中拱支座上纤维
     * </pre>
     *
     * <code>double combineZhonggongZhizuoShang = 9;</code>
     */
    public Builder setCombineZhonggongZhizuoShang(double value) {
      
      combineZhonggongZhizuoShang_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *合成中拱支座上纤维
     * </pre>
     *
     * <code>double combineZhonggongZhizuoShang = 9;</code>
     */
    public Builder clearCombineZhonggongZhizuoShang() {
      
      combineZhonggongZhizuoShang_ = 0D;
      onChanged();
      return this;
    }

    private double combineZhonggongZhizuoXia_ ;
    /**
     * <pre>
     *合成中拱支座下纤维
     * </pre>
     *
     * <code>double combineZhonggongZhizuoXia = 10;</code>
     */
    public double getCombineZhonggongZhizuoXia() {
      return combineZhonggongZhizuoXia_;
    }
    /**
     * <pre>
     *合成中拱支座下纤维
     * </pre>
     *
     * <code>double combineZhonggongZhizuoXia = 10;</code>
     */
    public Builder setCombineZhonggongZhizuoXia(double value) {
      
      combineZhonggongZhizuoXia_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *合成中拱支座下纤维
     * </pre>
     *
     * <code>double combineZhonggongZhizuoXia = 10;</code>
     */
    public Builder clearCombineZhonggongZhizuoXia() {
      
      combineZhonggongZhizuoXia_ = 0D;
      onChanged();
      return this;
    }

    private double combineZhonggongKuazhongShang_ ;
    /**
     * <pre>
     *合成中拱跨中上纤维
     * </pre>
     *
     * <code>double combineZhonggongKuazhongShang = 11;</code>
     */
    public double getCombineZhonggongKuazhongShang() {
      return combineZhonggongKuazhongShang_;
    }
    /**
     * <pre>
     *合成中拱跨中上纤维
     * </pre>
     *
     * <code>double combineZhonggongKuazhongShang = 11;</code>
     */
    public Builder setCombineZhonggongKuazhongShang(double value) {
      
      combineZhonggongKuazhongShang_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *合成中拱跨中上纤维
     * </pre>
     *
     * <code>double combineZhonggongKuazhongShang = 11;</code>
     */
    public Builder clearCombineZhonggongKuazhongShang() {
      
      combineZhonggongKuazhongShang_ = 0D;
      onChanged();
      return this;
    }

    private double combineZhonggongKuazhongXia_ ;
    /**
     * <pre>
     *合成中拱跨中下纤维
     * </pre>
     *
     * <code>double combineZhonggongKuazhongXia = 12;</code>
     */
    public double getCombineZhonggongKuazhongXia() {
      return combineZhonggongKuazhongXia_;
    }
    /**
     * <pre>
     *合成中拱跨中下纤维
     * </pre>
     *
     * <code>double combineZhonggongKuazhongXia = 12;</code>
     */
    public Builder setCombineZhonggongKuazhongXia(double value) {
      
      combineZhonggongKuazhongXia_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *合成中拱跨中下纤维
     * </pre>
     *
     * <code>double combineZhonggongKuazhongXia = 12;</code>
     */
    public Builder clearCombineZhonggongKuazhongXia() {
      
      combineZhonggongKuazhongXia_ = 0D;
      onChanged();
      return this;
    }

    private double combineZhongchuiZhizuoShang_ ;
    /**
     * <pre>
     *合成中垂支座上纤维
     * </pre>
     *
     * <code>double combineZhongchuiZhizuoShang = 13;</code>
     */
    public double getCombineZhongchuiZhizuoShang() {
      return combineZhongchuiZhizuoShang_;
    }
    /**
     * <pre>
     *合成中垂支座上纤维
     * </pre>
     *
     * <code>double combineZhongchuiZhizuoShang = 13;</code>
     */
    public Builder setCombineZhongchuiZhizuoShang(double value) {
      
      combineZhongchuiZhizuoShang_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *合成中垂支座上纤维
     * </pre>
     *
     * <code>double combineZhongchuiZhizuoShang = 13;</code>
     */
    public Builder clearCombineZhongchuiZhizuoShang() {
      
      combineZhongchuiZhizuoShang_ = 0D;
      onChanged();
      return this;
    }

    private double combineZhongchuiZhizuoXia_ ;
    /**
     * <pre>
     *合成中垂支座下纤维
     * </pre>
     *
     * <code>double combineZhongchuiZhizuoXia = 14;</code>
     */
    public double getCombineZhongchuiZhizuoXia() {
      return combineZhongchuiZhizuoXia_;
    }
    /**
     * <pre>
     *合成中垂支座下纤维
     * </pre>
     *
     * <code>double combineZhongchuiZhizuoXia = 14;</code>
     */
    public Builder setCombineZhongchuiZhizuoXia(double value) {
      
      combineZhongchuiZhizuoXia_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *合成中垂支座下纤维
     * </pre>
     *
     * <code>double combineZhongchuiZhizuoXia = 14;</code>
     */
    public Builder clearCombineZhongchuiZhizuoXia() {
      
      combineZhongchuiZhizuoXia_ = 0D;
      onChanged();
      return this;
    }

    private double combineZhongchuiKuazhongShang_ ;
    /**
     * <pre>
     *合成中垂跨中上纤维
     * </pre>
     *
     * <code>double combineZhongchuiKuazhongShang = 15;</code>
     */
    public double getCombineZhongchuiKuazhongShang() {
      return combineZhongchuiKuazhongShang_;
    }
    /**
     * <pre>
     *合成中垂跨中上纤维
     * </pre>
     *
     * <code>double combineZhongchuiKuazhongShang = 15;</code>
     */
    public Builder setCombineZhongchuiKuazhongShang(double value) {
      
      combineZhongchuiKuazhongShang_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *合成中垂跨中上纤维
     * </pre>
     *
     * <code>double combineZhongchuiKuazhongShang = 15;</code>
     */
    public Builder clearCombineZhongchuiKuazhongShang() {
      
      combineZhongchuiKuazhongShang_ = 0D;
      onChanged();
      return this;
    }

    private double combineZhongchuiKuazhongXia_ ;
    /**
     * <pre>
     *合成中垂跨中下纤维
     * </pre>
     *
     * <code>double combineZhongchuiKuazhongXia = 16;</code>
     */
    public double getCombineZhongchuiKuazhongXia() {
      return combineZhongchuiKuazhongXia_;
    }
    /**
     * <pre>
     *合成中垂跨中下纤维
     * </pre>
     *
     * <code>double combineZhongchuiKuazhongXia = 16;</code>
     */
    public Builder setCombineZhongchuiKuazhongXia(double value) {
      
      combineZhongchuiKuazhongXia_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *合成中垂跨中下纤维
     * </pre>
     *
     * <code>double combineZhongchuiKuazhongXia = 16;</code>
     */
    public Builder clearCombineZhongchuiKuazhongXia() {
      
      combineZhongchuiKuazhongXia_ = 0D;
      onChanged();
      return this;
    }

    private double combineAllowStress_ ;
    /**
     * <pre>
     *合成许用应力
     * </pre>
     *
     * <code>double combineAllowStress = 17;</code>
     */
    public double getCombineAllowStress() {
      return combineAllowStress_;
    }
    /**
     * <pre>
     *合成许用应力
     * </pre>
     *
     * <code>double combineAllowStress = 17;</code>
     */
    public Builder setCombineAllowStress(double value) {
      
      combineAllowStress_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *合成许用应力
     * </pre>
     *
     * <code>double combineAllowStress = 17;</code>
     */
    public Builder clearCombineAllowStress() {
      
      combineAllowStress_ = 0D;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:com.iscas.biz.calculation.grpc.Sigma2Entity)
  }

  // @@protoc_insertion_point(class_scope:com.iscas.biz.calculation.grpc.Sigma2Entity)
  private static final com.iscas.biz.calculation.grpc.Sigma2Entity DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.iscas.biz.calculation.grpc.Sigma2Entity();
  }

  public static com.iscas.biz.calculation.grpc.Sigma2Entity getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Sigma2Entity>
      PARSER = new com.google.protobuf.AbstractParser<Sigma2Entity>() {
    public Sigma2Entity parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new Sigma2Entity(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Sigma2Entity> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Sigma2Entity> getParserForType() {
    return PARSER;
  }

  public com.iscas.biz.calculation.grpc.Sigma2Entity getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

