// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: calculation.proto

package com.iscas.biz.calculation.grpc;

public interface BuoyancyRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.iscas.biz.calculation.grpc.BuoyancyRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *邦戎曲线路径
   * </pre>
   *
   * <code>string brojeanFilePath = 1;</code>
   */
  java.lang.String getBrojeanFilePath();
  /**
   * <pre>
   *邦戎曲线路径
   * </pre>
   *
   * <code>string brojeanFilePath = 1;</code>
   */
  com.google.protobuf.ByteString
      getBrojeanFilePathBytes();

  /**
   * <pre>
   *静水力曲线文件路径
   * </pre>
   *
   * <code>string buoyancycurveFilePath = 2;</code>
   */
  java.lang.String getBuoyancycurveFilePath();
  /**
   * <pre>
   *静水力曲线文件路径
   * </pre>
   *
   * <code>string buoyancycurveFilePath = 2;</code>
   */
  com.google.protobuf.ByteString
      getBuoyancycurveFilePathBytes();

  /**
   * <pre>
   *核校精度 两个double值 第一个排水量精度  第二个重心精度
   * </pre>
   *
   * <code>repeated double precision = 3;</code>
   */
  java.util.List<java.lang.Double> getPrecisionList();
  /**
   * <pre>
   *核校精度 两个double值 第一个排水量精度  第二个重心精度
   * </pre>
   *
   * <code>repeated double precision = 3;</code>
   */
  int getPrecisionCount();
  /**
   * <pre>
   *核校精度 两个double值 第一个排水量精度  第二个重心精度
   * </pre>
   *
   * <code>repeated double precision = 3;</code>
   */
  double getPrecision(int index);

  /**
   * <pre>
   *校核目标 0-极限 1-巡航
   * </pre>
   *
   * <code>int32 target = 4;</code>
   */
  int getTarget();

  /**
   * <pre>
   *平均吃水
   * </pre>
   *
   * <code>double tm = 5;</code>
   */
  double getTm();

  /**
   * <pre>
   *尾吃水
   * </pre>
   *
   * <code>double ta = 6;</code>
   */
  double getTa();

  /**
   * <pre>
   *船首吃水
   * </pre>
   *
   * <code>double tf = 7;</code>
   */
  double getTf();
}
