// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: calculation.proto

package com.iscas.biz.calculation.grpc;

public interface WaveLoadRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.iscas.biz.calculation.grpc.WaveLoadRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *波高(m)
   * </pre>
   *
   * <code>double height = 1;</code>
   */
  double getHeight();
}
